### ISSUE TITLE
Support for Alexa Conversations

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1011]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Hi! Have you ever considered to add support for Alexa Conversations?

Currently it's generally available for en-US, while it's in beta for en-AU, en-CA, en-IN, en-GB and de-DE. More info [here](https://developer.amazon.com/en-US/docs/alexa/conversations/about-alexa-conversations.html).

I could start working on this when I'll have some free time.

**Comment by jankoenig** [comment]
Thanks! We're currently evaluating this for Jovo `v4`. We'll keep you posted here.

**Comment by m-ripper** [comment]
Hello @acerbisgianluca,

Since #1140 was merged and published you should be able to use Alexa Conversations.

For more information how to use it, feel free to take a look at the related [docs](https://www.jovo.tech/marketplace/platform-alexa/alexa-conversations).
