### ISSUE TITLE
I get an error with Stages if I follow the v4 docs

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1035]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Having this object in `jovo.project.js`:
```
const project = new ProjectConfig({
  defaultStage: 'dev',
  stages: {
    dev: {
      endpoint: '${JOVO_WEBHOOK_URL}',
      plugins: [
        new GoogleAssistantCli({ projectId: 'XXXXX' }),
        new AlexaCli({ locales: { en: ['en-GB'] } }),
      ],
    },
  },
});
```

Build should finish correctly

## Current Behavior

I get this error: `›  Plugin [object Object] is not an instance of JovoCliPlugin.`
when `jovov4 build` or `jovov4 build -stage dev`

### Error log
```
x Error: --------------------------------------------------------------------------------
›
› Message:
›  Plugin [object Object] is not an instance of JovoCliPlugin.
› Module:
›  JovoCliCore
› Details:
›  Make sure your plugin inherits JovoCliPlugin provided by @jovotech/cli-core
›
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

## Your Environment

Default .ts template with core, googleassistant and alexa platforms.
Using @jovotech/cli: 4.0.0-beta.6
* Operating System:
Windows 10

**Comment by rubenaeg** [comment]
I thought I removed that check already. Will be fixed with the next release, thanks for flagging :+1:
