### ISSUE TITLE
askProfile attribute of AlexaCliConfig has no effect when using jovov4 build

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1039]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When having:
```
const project = new ProjectConfig({
	endpoint: '${JOVO_WEBHOOK_URL}',
	plugins: [
		new AlexaCli({ locales: { en: [ 'en-GB' ] }, askProfile: 'test' }),
	],
});
```
The resulting code of `/build/platform.alexa/.ask/ask-states.json`:

```
{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "test": {
      "skillId": "",
      "skillMetadata": {
        "lastDeployHash": ""
      },
      "code": {}
    }
  }
}
```

## Current Behavior

The resulting code of `/build/platform.alexa/.ask/ask-states.json` has 'default':
```
{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillId": "",
      "skillMetadata": {
        "lastDeployHash": ""
      },
      "code": {}
    }
  }
}

```
and the error message is empty

### Error log
```
eploying Alexa Skill
  ✓ Updating Alexa Skill project [ASK profile: apd-local]
    Skill Name: LOCAL - Universidad de Murcia (es-ES) 
    Skill ID: amzn1.ask.skill.8959d4a0-d411-4ca1-84fe-46e8064f4376
    x en-GB

x Error: --------------------------------------------------------------------------------
›
› Message:
› Module:
›  JovoCliCore
›
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

## Your Environment

Default .ts template with core, googleassistant and alexa platforms.
Using @jovotech/cli: 4.0.0-beta.6
* Operating System:
Windows 10

**Comment by rubenaeg** [comment]
Thanks for flagging this, I just added a PR that addresses this bug.

**Comment by jrglg** [comment]
Hi @rubenaeg, I noticed some stuff changed in `@jovotech/platform-alexa^4.0.0-beta.7` and now the `askProfile` of AlexaCliConfig is used correctly in `ask-states.json`, but the `default` profile is added at the end of the file too and deploy is failing because of that. Thank you

**Comment by rubenaeg** [comment]
The changes are not deployed yet, so nothing should've changed. How exactly did you notice that it's now being used properly?

**Comment by rubenaeg** [comment]
Btw `jovov4 deploy:platform` is already using the correct ASK profile, not from `ask-states.json` though, but rather from your `jovo.project.js` or `--project-id`, which you can pass to the command. The only thing that's missing is that `jovov4 build` is adding the profile to the ASK configuration, which you would only need for native operations inside the platform folder.

**Comment by jrglg** [comment]
You are right. I didn't delete `/build` folder so the askProfile were there before build. My mistake!
