### ISSUE TITLE
Jovo webhook Not working

### ISSUE THREAD

**Issue by Dipankershah** [jovotech/jovo-framework#1131]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Webhook is not working

## Current Behavior
I'm getting  https://webhook.jovo.cloud/2e37ed75-e74f-4306-9cbf-XXXXXXX type webhook URL but it's not working on Alexa as webhook. But when I try my local host by ngrok, Then ngrok URL was working fine. I don't know maybe it's because you have a new version of JOVO (4) now. But I haven't updated anything. Please check that error.

## Your Environment

* Jovo Framework version used: 3.6.0
* Operating System: M1 Mac

**Comment by aswetlow** [comment]
Hey @Dipankershah 

Yes, we released v4 yesterday. If you're using Jovo v3, the webhook URL starts with `webhookv3.jovo.cloud` 

Here's more info: https://www.jovo.tech/docs/migration-from-v3#use-v4-and-v3-in-parallel

**Comment by Dipankershah** [comment]
Thanks, @aswetlow the very quick response. Ohh it's on the docs. I haven't checked it properly then.
