### ISSUE TITLE
Cannot install V4.0.0

### ISSUE THREAD

**Issue by EeeDotZee** [jovotech/jovo-framework#1132]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I've tried to download the latest 4.0.0 version to create a new v4.0.0 project and migrate my v3 project. I installed the new version via npm I'd like to access the v4 jovo-cli with the jovo command

## Current Behavior
After running `npm install -g @jovotech/cli` i get the message `WARN You can now use "jovo" to call the Jovo CLI @v4.` which should be fine, but then if i run `jovo run` it says my version is still at `jovo-cli/3.2.1` and if create a new project and do jovo run it warns me that i should consider updating to v4... well that's what i'm trying to do here haha.

## Your Environment
* Jovo Framework version used: 4.0.0
* Operating System: MacOS 11.5.2

**Comment by rubenaeg** [comment]
Can you try manually uninstalling the Jovo CLI v3 using `npm uninstall -g jovo-cli` and install v4 again?

**Comment by EeeDotZee** [comment]
> Can you try manually uninstalling the Jovo CLI v3 using `npm uninstall -g jovo-cli` and install v4 again?

Unfortunately that didn't work either. Still shows version 3.2.1 when i do `jovo help`

**Comment by rubenaeg** [comment]
Do you get an error message when installing `@jovotech/cli`? It seems odd to me that although you're uninstalling v3 of the Jovo CLI, it is still installed after installing `@jovotech/cli`, because nowhere in the process is v3 installed again.

**Comment by EeeDotZee** [comment]
Turned out i also had to do the uninstall without the `-g` aswell, don't really know why. The v4 was already installed but the command line always accessed the wrong one for some reason.
Problem is solved now on my side and can be closed.
