### ISSUE TITLE
Handler extremely slow

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1168]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior

Hi, the following is a handler I have in my voice app:
```
@Intents('SetDestinationIntent')
    async setDestinationIntent(): Promise<void> {
        this.$send(this.$t('gather_destination_component.ask_for_destination'));

        return this.$delegate(GatherDestinationComponent, {
            resolve: {
                destination: this.setDestination,
            },
        });
    }
```
The problem is that it takes 4/5 seconds to run on a Google Cloud Function (256mb of memory). The LAUNCH handler, for example, takes only half a second and does nothing (it only sends "Hello!", so it's very similar to this function, except the delegate call).

It's inside a global component and nothing runs before it (hooks, retrieving of user data, etc.), so there aren't any external calls in the middle of the process which could add delay.

Is there something wrong with the first `this.$send` which is not awaited (in the documentation it's done in the same way)? Thanks.

## Your Environment

* Jovo Framework version used: 4.1.0
* Operating System: Windows 10

**Comment by acerbisgianluca** [comment]
The problem seems to be the `$delegate`. It tries to call the `START` handler on `GatherDestinationComponent` which doesn't exist because it would be empty. If I add the `START` handler, which does nothing, the response is returned immediately.

Also, I don't understand why the `$delegate` tries to immediately execute the `START` handler. `$delegate` is something that will be called on the next invocation, isn't it? I'm thinking about the delegate as the `followUpState` of Jovo 3, am I wrong? 
With the delegate, I can't even specify a handler to be called, as opposed to the `$redirect`, which immediately run the handler (or START if not provided).

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 

Looks like it works as intended. `$delegate` redirects to the `START()` handler of the specified component. https://www.jovo.tech/docs/handlers#start
We should add this information to the "Delegate to Components" chapter as well.  cc @jankoenig
