### ISSUE TITLE
Card isn't converted to APL on Alexa

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1172]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

This is the Alexa Plugin confiration:
```
new AlexaPlatform({
            output: {
                genericOutputToApl: true,
            },
            intentMap: {
                ....
            },
        })
```
And this is the output template I return from the build method:
```
{
  message: '.....',
  reprompt: '.....',
  card: {
            title: 'MotorMouth',
            content: '.....',
        }
}
```
I also created a method in the output class which concats all the previous card content, since I usually call `this.$send` many times in the handlers and I want only one card in the output that contains all the text responses and not just the last one. The function is:
```
private buildCard(content: string): Card {
        const prevContent = this.$output[this.$output.length - 1]?.card?.content ?? '';

        return {
            title: 'MotorMouth',
            content: removeSSML(prevContent + content).trim(),
        };
    }
```
Probably I could also use a hook on the `response.start` event and iterate all the output array, but this solution works as well.

After this, I expect the card to be converted to an APL document in the response to Alexa.

## Current Behavior

Currently, the response contains a standard card:
```
{
  "outputSpeech": {...},
  "reprompt": {...},
  "card": {
				"type": "Standard",
				"title": "MotorMouth",
				"text": "......."
			}
}
```
So, actually the function which concats all the content works, the problem is that the Alexa Output strategy doesn't convert the card to APL.

## Your Environment

* Jovo Framework version used: 4.1.0
* Operating System: Windows 10

**Comment by m-ripper** [comment]
Hello there,

Please make sure the APL interface is enabled for the skill. 

In case this does not resolve your issue, just let me know.

**Comment by acerbisgianluca** [comment]
Oh, you're right. My bad
