### ISSUE TITLE
Message speech is trimmed on Google Assistant

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1176]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Other... Please describe:
- [ ] Documentation issue or request

## Expected Behavior

Speech hasn't a characters limit on Google AFAIK. Just the text has a limit of 640 characters. So I expect the text to be trimmed, but not the speech property.

Reference: [Google docs](https://developers.google.com/assistant/conversational/prompts-simple#SimpleResponseProperties)

## Current Behavior

The speech property is sanitized here:
https://github.com/jovotech/jovo-framework/blob/05f0a4b7308a358a9eaa8de3535773b6419e1d8e/platforms/platform-googleassistant/src/output/GoogleAssistantOutputTemplateConverterStrategy.ts#L41
and trimmed here:
https://github.com/jovotech/jovo-framework/blob/05f0a4b7308a358a9eaa8de3535773b6419e1d8e/output/src/OutputTemplateConverterStrategy.ts#L157

### Error log
```
$output.message was trimmed due to exceeding the limit of 640 characters.
```

## Your Environment

* Jovo Framework version used: 4.1.0
* Operating System: Windows 10

**Comment by acerbisgianluca** [comment]
The default max length is set to `TEXT_MAX_LENGTH`:
https://github.com/jovotech/jovo-framework/blob/05f0a4b7308a358a9eaa8de3535773b6419e1d8e/platforms/platform-googleassistant/src/output/GoogleAssistantOutputTemplateConverterStrategy.ts#L59-L64

Here, calling `sanitizeMessage` with a much higher value for the maxLength parameter, should fix this issue:
https://github.com/jovotech/jovo-framework/blob/05f0a4b7308a358a9eaa8de3535773b6419e1d8e/platforms/platform-googleassistant/src/output/GoogleAssistantOutputTemplateConverterStrategy.ts#L41

**Comment by aswetlow** [comment]
You're right. 

`speech` and `text` should be sanitized separately.

cc  @m-ripper

**Comment by m-ripper** [comment]
This issue should be fixed with the update that is coming today.

Closing for now. If it still occurs, feel free to re-open.
