### ISSUE TITLE
$session.isNew is always false on Google Assistant

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1177]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Other... Please describe:
- [ ] Documentation issue or request

## Expected Behavior

`this.$session.isNew` is always `false` on Google Assistant even if the session is new. In that case, I expect it to be `true`.

The problem is here: https://github.com/jovotech/jovo-framework/blob/05f0a4b7308a358a9eaa8de3535773b6419e1d8e/platforms/platform-googleassistant/src/GoogleAssistantRequest.ts#L102-L104

`this.getSessionData()` returns `session.params` which is `{}` when the session is new, but `!{}` is `false`.

## Current Behavior

`this.$session.isNew` is always `false`, even if `this.getSessionData()` returns `{}`.

## Your Environment

* Jovo Framework version used: 4.1.0
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 
Thanks for flagging. Yes, I can reproduce it. Preparing a fix.

**Comment by aswetlow** [comment]
We published the fix.
