### ISSUE TITLE
What kind of data can I store in this.$session.data?

### ISSUE THREAD

**Issue by alexanderkoller** [jovotech/jovo-framework#1195]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I would like to reuse the connection to a [JSPyBridge](https://github.com/extremeheat/JSPyBridge) Python interpreter throughout a Jovo session. This is an object that console.log prints as follows:

```
<module 'test.py' from '/Users/koller/Documents/workspace/cookbook/jovo/jovotest/python/test.py'>
```

If I store the object in `this.$session.data.python` in the START handler of a component, [as described in the Jovo documentation](https://www.jovo.tech/docs/data), and then retrieve it in some other handler, I expect to get the same "module" object back.

## Current Behavior

Instead, when I run the Jovo skill in the local Jovo debugger, I get an object that prints like this:
```
{ ffid: 1 }
```

Are there limitations to what kinds of data can be can be stored in `$session.data`? Could you document this more precisely?

Is there a workaround that would allow me to store a Javascript object in a safe place that persists across the lifetime of the Jovo process? Perhaps I could put the object into a global dictionary and then access it via a string key that I can persist in `$session.data`?

**Comment by aswetlow** [comment]
> In that case, I have to associate each session-specific object with a unique identifier for the current session. Is there a platform-independent method to get a session identifier from the request? Or can I use a field of the user metadata for this?

Yes, you can use `jovo.$session.id` in any hook.

> Also, I'd need to clean up the contents of this.$app.data after each invocation of the skill ends. Is there a handler that gets called when the session ends (skill is stopped, etc.)? I've seen LAUNCH/START, but couldn't find anything analogous for the end.

There's no method for this, but you could hook into a middleware and check if `listen` is set to false. 

```typescript
app.hook('after.response.output', (jovo) => {
  if (jovo.$output[jovo.$output.length-1].listen) {
   // session ended
   }
});
```
I haven't tested it myself. And be aware, this might not work if you use native responses.

**Comment by alexanderkoller** [comment]
Thanks, I will try that out. I'm closing the issue for now, thanks for your help!
