### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1214]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Feature requests

MongoDb integration would be nice. Many advantages over Dynamodb, such as **being able to search JSON fields easily** and more flexibility in model changes.

In [MongoDB Atlas docs](https://docs.atlas.mongodb.com/best-practices-connecting-from-aws-lambda/) there is one point that is important: Create the MongoClient object once.

Thank you.

**Comment by jankoenig** [comment]
Thank you. This is not on our immediate roadmap and would be a great community contribution!

If anyone wants to get started with this, let us know.

Two resources that should be helpful for this:
- The `v4` integration for DynamoDb, which can serve as a good example for getting started: https://github.com/jovotech/jovo-framework/tree/v4/latest/integrations/db-dynamodb
- The `v3` integration for MongoDB: https://github.com/jovotech/jovo-framework/tree/v3/latest/jovo-integrations/jovo-db-mongodb

**Comment by jrglg** [comment]
I'm not clear on how to handle the instance of the connection.

According to [this](https://docs.atlas.mongodb.com/best-practices-connecting-from-aws-lambda/#connection-examples), possible deployment in Lambda should be considered. As it was in version 3, several connections were opened and it was not ideal.

The problem is that I don't know much about the language, and I'm not sure about the following:

1. whether we should provide the connection explicitly through an access like "this.$db". To me this makes sense because Jovo will open a connection to update the date of users last connection, and possible changes to "this.$user.data"... If, in addition, another use case requires access to the database, the connection should be reused.

2. How is this handled across different AWS Lambda invocations? As I understand it, a lot of benefit could be gained by initiating the connection outside the handler.

3. I'm not clear how to maintain the connection in Node.js. I don't know if it could work with a Singleton.
 Would option 1 be better? or you could do it directly from the MongoDb module. Would the latter work?

I'm already coding this but advise would be great.

**Comment by jrglg** [comment]
Hi @jankoenig @aswetlow 

I found a weird issue when trying to use the helper methods under `this.$mongoDb`:

```typescript
  async LAUNCH() {
    const db= await this.$mongoDb.getDb(); // throws error
    const users = await this.$mongoDb.getCollection(); // throws error
    const client= await this.$mongoDb.getClient(); // throws error
```

The error is:

```
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at Proxy.then (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at Proxy.then (<anonymous>)
```

Does this happen to you?

**Comment by jankoenig** [comment]
Are you using it together with the Jovo Debugger? If yes, you need to add `$mongoDb` to the `ignoredProperties` array like explained here: https://www.jovo.tech/marketplace/db-mongodb#configuration

**Comment by jrglg** [comment]
Oh yes, I didn't see that part.

Thank you very much

**Comment by jankoenig** [comment]
Great. Thanks for the contribution @jrglg 🎉
