### ISSUE TITLE
Add multiple directives in the same response

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-framework#1219]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

How can I send multiple directives in the same response?
instead of adding only one song like this:
```
return this.$send(AudioPlayerPlayOutput, {
    audioItem: {
      stream: {
        url: 'https://s3.amazonaws.com/jovo-songs/song1.mp3',
      },
    },
  })
```
How can I add multiple AudioPlayer directives in the response?

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 4.0.3
* Operating System:10.15.5

**Comment by alvarocardenasc** [comment]
@aswetlow  But the problem with that is that in the 'PlaybackNearlyFinished' request doesn't come with session data.
How can I know what is the next song that should play?

**Comment by aswetlow** [comment]
You can store the information in the database. `this.$user.data.currentTrack = '...mp3'`;

**Comment by alvarocardenasc** [comment]
oo you're right thanks.

**Comment by alvarocardenasc** [comment]
I can't get data from this.$user.data in AudioPlayer.PlaybackNearlyFinished It looks like is empty {}

**Comment by jankoenig** [comment]
Closing this, as the data issue is discussed in a different thread (#1220)
