### ISSUE TITLE
AlexaCli options (askProfile and skillId) aren't used by jovo cli

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1222]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

If I run `jovo get:platform alexa --stage dev --clean`, the cli should use the `mm` ask profile and directly get the skill with the id provided in the config object.

This is the initialization of the AlexaCli plugin:

```
new AlexaCli({
                    skillId: process.env.DEV_SKILL_ID,
                    askProfile: 'mm',
                    locales: {
                        en: ['en-US'],
                    },
                    files: {
                        'skill-package/skill.json': {
                            manifest: {
                                apis: {
                                    custom: {
                                        endpoint: {
                                            uri: process.env.DEV_WEBHOOK_URL,
                                            sslCertificateType: 'Wildcard',
                                        },
                                    },
                                },
                            },
                        },
                    },
                })
```

This works if I run `jovo get:platform alexa --stage dev --clean --ask-profile mm --skill-id XXXXXX`.

## Current Behavior

The cli uses the `default` ask profile, instead of `mm`, and get a list of all the skills linked to that profile, instead of the skill with id `process.env.DEV_SKILL_ID`.

## Your Environment

* Jovo Framework version used: 4.2.0
* Operating System: Windows 10

**Comment by jankoenig** [comment]
Thank you! We'll take a look

**Comment by jankoenig** [comment]
Thank you again for flagging! This was fixed a while ago. Closing this now.
