### ISSUE TITLE
Show account linking card for alexa

### ISSUE THREAD

**Issue by NLueg** [jovotech/jovo-framework#1231]
Hey there! I just wanted to migrate from v3 to v4 to have the cool new component structure.
Unfortunately, I struggle at the beginning with integrating the Alexa account linking.

## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The account linking should be documented for v4.

## Current Behavior

The method `showAccountLinkingCard` doesn't seem to exist anymore, and I also don't found any documentation about showing the card.

## Your Environment

* Jovo Framework version used: 4.2.1

**Comment by jankoenig** [comment]
Hey there!

For features like this, you can use the [`nativeResponse` feature](https://www.jovo.tech/marketplace/platform-alexa/output#native-response) that allows you to add output elements exactly in the way as they should end up in the response JSON.

For example, an account linking card could be displayed using output like this:

```typescript
{
  message: `I've sent a card to your Alexa app.`,
  listen: false, // close the session
  platforms: {
    alexa: {
      nativeResponse: {
        response: {
          card: {
             type: 'LinkAccount'
          }
        }
      }
    }
  }
}
```

We're probably going to add convenience [output classes](https://www.jovo.tech/docs/output-classes) for this in the future, similar to the [permission consent card](https://www.jovo.tech/marketplace/platform-alexa/reminders#permissions-consent-card).

If anyone in the community wants to tackle this, that would be cool

**Comment by rmtuckerphx** [comment]
I'm working on it

**Comment by Tanmaybhujade** [comment]
Add AccountLinkCardOutput for Alexa

**Comment by rmtuckerphx** [comment]
@jankoenig This has been released. Who can close the issue?

**Comment by NLueg** [comment]
I can 😄 thank you for adding this @rmtuckerphx !
