### ISSUE TITLE
Lambda function not calling

### ISSUE THREAD

**Issue by Dipankershah** [jovotech/jovo-framework#1232]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Lambda function always timeout and not returning any response

## Current Behavior

Lambda function always timeout and not returning any response. I used your doc and set 
context.callbackWaitsForEmptyEventLoop = false;

But nothing works. Please help me. I'm using .js file format not .ts for project

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 4.0.0
* Operating System: Mac

**Comment by jankoenig** [comment]
Hi,

How are you deploying to Lambda?

**Comment by Dipankershah** [comment]
I solved the error. Actually when I'm using Twilio liberty then I get the error. Otherwise, it's working good.
