### ISSUE TITLE
Does @jovotech/filebuilder really belong to devDependencies?

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1240]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Other... Please describe: Not sure if a bug

## Problem
I use the `--production` flag (npm 6) when installing global packages in CI with this command:
`npm install --production --unsafe-perm=true -g --cache .npm_global_cache --prefer-offline $PNPM $ASK_CLI $GACTIONS_CLI $JOVO_CLI`

and `--prod` flag in pnpm, like this:
`pnpm install --prod --frozen-lockfile --prefer-offline`

The problem is this error when building the model:

```
x Error: --------------------------------------------------------------------------------
›                                                                                 
› Message:
›  Could not load project configuration.
›                                                                                 
› Module:
›  JovoCliCore
›                                                                                 
› Details:
›  Cannot find module '@jovotech/filebuilder'
›  Require stack:
›  - /builds/cidu/apd/node_modules/.pnpm/@jovotech+platform-googleassistant@4.2.1_4dfad7c2b7f98c8b51fcb4ffa585ec2f/node_modules/@jovotech/platform-googleassistant/dist/cjs/cli/hooks/BuildHook.js
›  - /builds/cidu/apd/node_modules/.pnpm/@jovotech+platform-googleassistant@4.2.1_4dfad7c2b7f98c8b51fcb4ffa585ec2f/node_modules/@jovotech/platform-googleassistant/dist/cjs/cli/index.js
›  - /builds/cidu/apd/node_modules/.pnpm/@jovotech+platform-googleassistant@4.2.1_4dfad7c2b7f98c8b51fcb4ffa585ec2f/node_modules/@jovotech/platform-googleassistant/dist/cjs/index.js
›  - /builds/cidu/apd/jovo.project.js
›  - /builds/cidu/apd/.npm_global_cache/lib/node_modules/@jovotech/cli/node_modules/@jovotech/cli-core/dist/ProjectConfig.js
›  - /builds/cidu/apd/.npm_global_cache/lib/node_modules/@jovotech/cli/node_modules/@jovotech/cli-core/dist/index.js
›  - /builds/cidu/apd/.npm_global_cache/lib/node_modules/@jovotech/cli/dist/index.js
›  - /builds/cidu/apd/.npm_global_cache/lib/node_modules/@jovotech/cli/bin/run
›                                                                                 
›                                                                                 
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

I think `@jovotech/filebuilder` should be in production dependencies.

Please correct me if I'm wrong.

Thank you.

## Your Environment

* Jovo Framework version used: 4.2.1
* Operating System: Docker node:14-alpine image.

**Comment by jankoenig** [comment]
Hi @jrglg,

The `build` and `deploy` commands are usually used in development environments, not in production deployments. This is why things like the FileBuilder and the `cli-core` package that are used for the project config are dev dependencies.

Does it fix your problem if you add `cli-core` to the production dependencies?

**Comment by jrglg** [comment]
Hey, the problem persists with `cli-core` in prod dependencies. Same log. I had to add both to production dependencies for it to work.

Taking advantage of the fact that Alex has fixed the spinner problem in CI, perhaps a `--ci` option can be implemented for this type of situation. So the jovo build command could be used to deploy to production. (If not, which one would you use?)

Thank you

**Comment by jrglg** [comment]
Excuse me for so many messages, I just remembered that the step to production of the models is contemplated to be done through the internal mechanisms of Conversational Actions and Alexa Skills. Although in my case, in addition to that, I keep separated skills and gcloud projects for stages.

I don't know if I explain correctly.

I'm closing this anyway.

Thanks.
