### ISSUE TITLE
Documentation for Entities Validation ?

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-framework#1244]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

### Error log
```
```

Where is the documentation for entity validation for v4?

here is for v3:
https://v3.jovo.tech/docs/routing/input#validation

## Your Environment

* Jovo Framework version used: 4.1.3
* Operating System: 10.15.5

**Comment by jankoenig** [comment]
I'm going to add documentation for this soon. Until then, here's an example: https://community.jovo.tech/t/what-would-be-the-right-way-to-use-delegate-and-resolve/1775/3?u=jan

**Comment by jankoenig** [comment]
Thank you @alvarocardenasc. The documentation can now be found here: https://www.jovo.tech/docs/entities#slot-filling and https://www.jovo.tech/docs/entities#entity-validation
