### ISSUE TITLE
can't save persistent data for Google Assistant

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-framework#1249]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:

## Current Behavior

I cant save persistent data for Google Assistant.  (this.$user.data or  this.$googleAssistant.$user.params)
The user verificationStatus is always as GUEST

### Error log
```
"user": {
    "locale": "en-US",
    "params": {},
    "accountLinkingStatus": "NOT_LINKED",
    "verificationStatus": "GUEST",
    "packageEntitlements": [],
    "gaiamint": "",
    "permissions": [],
    "lastSeenTime": "2022-02-21T23:26:04Z"
  }
```
What I'm missing?
I'm using a google nest hub device for testing too.

## Your Environment

* Jovo CLI version used: 4.1.3
* Operating System:  10.15.5

**Comment by jankoenig** [comment]
Closing this for now as this doesn't seem like a Jovo problem (the Google Assistant request identifies the user as `GUEST`).

For questions about platforms, we recommend using their respective support channels or the Jovo community forum: https://community.jovo.tech/
