### ISSUE TITLE
Media model Google Assistant missing attributes

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-framework#1265]
## I'm submitting a...

- [x] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

```
export declare class Media {
    mediaType: MediaTypeLike;
    startOffset: string;
    optionalMediaControls?: OptionalMediaControlsLike[];
    firstMediaObjectIndex?:Number ///MISSING
    repeatMode:string; ////MISSING
    mediaObjects: MediaObject[];
}
```

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 4.1.3 
* Operating System:  macOS 10.15.5

**Comment by jankoenig** [comment]
Hi @alvarocardenasc,

Thank you. Feel free to open a PR with the update.

**Comment by jankoenig** [comment]
Closing this for now. Google Actions will shut down soon and we're not planning to add new features for this platform.
