### ISSUE TITLE
Button property on table should be optional

### ISSUE THREAD

**Issue by OriginalJef** [jovotech/jovo-framework#1272]
https://github.com/jovotech/jovo-framework/blob/52912f7a73ebfd05cd7848d3195402cc37421008/platforms/platform-googleassistant/src/output/models/content/Table.ts#L43

as listed in de docs, the button prop is optional:
https://developers.google.com/assistant/conversational/prompts-rich

**Comment by aswetlow** [comment]
Thanks! Would you like to make a PR?

**Comment by jankoenig** [comment]
Thanks for flagging this @OriginalJef. And for the fix @aswetlow 🎉
