### ISSUE TITLE
Need AudioPlayer for google assistant documentation

### ISSUE THREAD

**Issue by Dipankershah** [jovotech/jovo-framework#1276]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

AudioPlayer for google assistant documentation needed

## Current Behavior

Currently, we don't have any documentation for google assistant documentation

- Jovo Framework version used: 4.x.x
- Operating System:

**Comment by jankoenig** [comment]
Thank you. Currently, we don't offer convenience output classes for Google Action Media Response.

However, it is possible to build this feature yourself using the `nativeResponse` property: https://www.jovo.tech/marketplace/platform-googleassistant/output#nativeresponse

Here's a discussion about this in the community forum: https://community.jovo.tech/t/jovo-4-google-media-response/1805

**Comment by Dipankershah** [comment]
Ok thank you

**Comment by jankoenig** [comment]
Since Google is sunsetting Conversational Actions, we are not planning on convenience methods for this feature. Learn more here: https://community.jovo.tech/t/google-conversational-actions-sunset/1892
