### ISSUE TITLE
Lex SLU makes extra call to AWS when input is audio

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#1282]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

The processAudio function makes an AWS API call using RecognizeUtteranceCommand.
The processText function makes an AWS API call using RecognizeTextCommand.

Both RecognizeUtteranceCommandOutput and RecognizeTextCommandOutput have the same values:
- interpretations
- messages
- sessionId
- sessionState

## Expected Behavior

It is inefficient and costly $$ to make 2 API calls to AWS when only 1 is needed.
If config.asr is set to true, then only processAudio needs to be called and the NluData can be built with that result. 
No need to call processText.

If config.asr is set to false, then processText should be called.

## Current Behavior

processText is called after processAudio

### Error Log

No error

## Your Environment

- Jovo Framework version used: 4.2.8
- Operating System: Windows 10 10.0.22000

**Comment by jankoenig** [comment]
Thank you @rmtuckerphx! Your PR was merged and released today
