### ISSUE TITLE
Lex SLU should add additional values to NluData: messages, sessionState

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#1283]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

Lex can take control of slot filling and uses the following values:
- messages - defined in Lex to prompt the user for slots or for confirmation
- intent.state - determines the different states of an intent(ReadyForFulfillment, Failed, InProgress)
- sessionState - includes dialog managment including the action and slot to elicit

## Expected Behavior

I would expect the following values to be available from this.$input.nlu:

```
nluData.resolved = response.interpretations[0];
nluData.matches = response.interpretations;
nluData.messages = response.messages;
nluData.sessionState = response.sessionState;
```

That way they can be used in an intent like this:

```
  BookHotel() {
    const resolved = this.$input.nlu?.resolved as any;
    if (resolved.intent.state === 'ReadyForFulfillment') {

      // make api call

      return this.$send({
        message: "The room has been booked!",
      });
    }

    if (resolved.intent.state === 'Failed') {
      return this.$send({
        message: "No worries. Maybe next time.",
      });
    }

    // intent.state equals 'InProgress'

    const messages = this.$input.nlu?.messages as any[];
    const output: OutputTemplate = {
      message: messages[0].content,
    };

    const quickReplies: {[key: string]: any} = {
      RoomType: ['king', 'queen', 'deluxe']
    };

    const sessionState = this.$input.nlu?.sessionState as any;
    if (sessionState.dialogAction.type === 'ElicitSlot') {
      const slotToElicit:string = sessionState.dialogAction.slotToElicit;
      if (quickReplies[slotToElicit]) {
        output.quickReplies = quickReplies[slotToElicit];
      }
    }

    return this.$send(output);
  }
```

## Current Behavior

There is currently no way to access:
- messages
- intent.state
- sessionState

### Error Log

No error

## Your Environment

- Jovo Framework version used: 4.2.8
- Operating System: Windows 10 10.0.22000

**Comment by jankoenig** [comment]
Thank you @rmtuckerphx! Your PR was merged and released today
