### ISSUE TITLE
Using START handler with decorators gives Duplicate global intent error

### ISSUE THREAD

**Issue by fbublitz** [jovotech/jovo-framework#1284]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [] Other :

I have used the default START handler of components and annotated it with decorators like so:

```
@Global()  
@Intents('intent_x')  
async START() {  
        //some code
}  
```
i have done this in two different components and the intent names in the ```@Intent()``` decorator are different. 
But it leads to error: _DuplicateGlobalIntentsError: Duplicate global intent names detected:_
saying that START is the duplicate global intent.

Is this expected behavior? Meaning the default START handler should not be annotated?

**update**
writing it like this also leads to the same error
```
@Handle({ global: true, intents: ['intent_x'] })
async START() { 
   ...
}
```
using another (but equal) handler name in the two components also leads to the same error, which qualifies it as a bug in my opinion.
Since the actual intent names that should be matched are different in the two components, there is no ambiguity, that the routing algorithm can run into.
```
@Handle({ global: true, intents: ['intent_x'] })
  async myHandlerName() {
```

### Error Log

```
If you have an error log, please paste it here.
```

## Your Environment

- Jovo Framework version used: 4.2.5
- Operating System: ubuntu 20.04
- node: 16.14.2

**Comment by jankoenig** [comment]
Hi @fbublitz, thanks for flagging!

Setting the intent global instead of the whole handler should solve the issue:

```typescript
@Handle({ intents: [ { name: 'intent_x', global: true } ] })
async START() { 
   ...
}
```

**Comment by jankoenig** [comment]
Thank you @fbublitz, I added a note here: https://www.jovo.tech/docs/handlers#start
