### ISSUE TITLE
Provide a way to get <component>.<handler> path in event middleware 'event.ComponentTreeNode.executeHandler'

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#1292]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

As part of `event.ComponentTreeNode.executeHandler` also provide the handler that is being called.

Some of this is provided as part of the $route but that is not updated for $redirect and $delegate:

```
"resolved": {
     "component": "GlobalComponent",
     "handler": "PizzaIntent",
     "global": true
   },
```

## Expected Behavior

On every event middleware for `event.ComponentTreeNode.executeHandler`, I would like access to the handler as well as the component. This doesn't provide it:

```
jovo.$handleRequest?.activeComponentNode?.path?.join('.')
```

I want to be able to log and use the `<component>.<handler>` string for all of these:
- "GlobalComponent.LAUNCH"
- "GlobalComponent.PizzaIntent"
- "LoveHatePizzaComponent.START"
- "LoveHatePizzaComponent.lovesPizza"

Specifically, I am writing a view engine and I want to automatically set a request value:

```
this.$data.handlerPath = `${component}.${handler}`
```

This can then be used as part of the criteria for selecting output templates.

Providing a method that can always be called in `event.ComponentTreeNode.executeHandler` that would return the `handlerPath` is one solution.

## Current Behavior

Access to the handler value is not available.

### Error Log
No error

## Your Environment

- Jovo Framework version used: 4.2.8
- Operating System: Windows 10 10.0.22000

**Comment by rmtuckerphx** [comment]
Do you have any insights @jtfell, @aswetlow, @jankoenig ?

**Comment by jankoenig** [comment]
Thank you! @aswetlow had a great idea how to solve this.

With the latest release (https://github.com/jovotech/jovo-framework/releases/tag/2022-05-17-patch), you can now access a `payload` using event middlewares. Learn more here https://www.jovo.tech/docs/handlers#middlewares and here: https://www.jovo.tech/docs/middlewares#event-middlewares
