### ISSUE TITLE
The response.tts middleware doesn't trigger from Jovo Debugger

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#1333]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When using a plugin that takes action during the `response.tts` middleware it should fire either when the request comes from a web client or the Jovo Debugger.

## Current Behavior

Currently the trigger doesn't happen with the Jovo Debugger but it does with the web client.

The `mount` function is called and line 36 executes which sets up the use of the middleware. But line 37 doesn't execute when using the Jovo Debugger.

![image](https://user-images.githubusercontent.com/247472/170874381-c973b6ce-51fb-437d-8038-7672128325da.png)

### Error Log

No error shows in terminal.

## Your Environment

@jovotech/cli: 4.1.6 

Jovo packages of the current project :
  - @jovotech/cli-command-build: 4.1.6  
  - @jovotech/cli-command-deploy: 4.1.6  
  - @jovotech/cli-command-get: 4.1.6  
  - @jovotech/cli-command-new: 4.1.6  
  - @jovotech/cli-command-run: 4.1.7  
  - @jovotech/cli-core: 4.1.7  
  - @jovotech/common: 4.2.9  
  - @jovotech/db-filedb: 4.2.15  
  - @jovotech/filebuilder: 0.0.1
  - @jovotech/framework: 4.2.15
  - @jovotech/model: 4.0.0
  - @jovotech/model-nlpjs: 4.0.0
  - @jovotech/nlu-nlpjs: 4.2.15
  - @jovotech/output: 4.2.11
  - @jovotech/platform-core: 4.2.15
  - @jovotech/platform-web: 4.2.15
  - @jovotech/plugin-debugger: 4.2.16
  - @jovotech/server-express: 4.2.15

Environment:
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD

**Comment by rmtuckerphx** [comment]
@aswetlow Are all middlewares supposed to work when using the Jovo Debugger as the client?

**Comment by aswetlow** [comment]
Hey @rmtuckerphx 

Good question. This is indeed a problem right now. Preparing a fix for that.

**Comment by aswetlow** [comment]
The fix is published. Here's the snippet for your code:


```
plugins: [
    new CorePlatform({
      plugins: [
        new TtsPlugin(),
      ]
    }),
    new JovoDebugger({plugins: [new TtsPlugin()]}),
  ],

```

**Comment by jankoenig** [comment]
Thank you for the fix @aswetlow!

Closing this for now. Let us know if the issue persists @rmtuckerphx. Thanks for flagging!
