### ISSUE TITLE
:bug: Staged configuration not applied for BasicLogging

### ISSUE THREAD

**Issue by rubenaeg** [jovotech/jovo-framework#1335]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When configuring the `logging` property in my `app.<stage>.ts`, the `app` instance should take that configuration into account when logging requests and responses.

## Current Behavior

Since the `BasicLogging` plugin is instantiated in the constructor of the app, configuration provided by `app.configure()` is ignored.

```typescript
  constructor(config?: AppInitConfig) {
    // ...
    if (typeof this.config.logging === 'boolean' && this.config.logging) {
      this.use(new BasicLogging({ request: true, response: true }));
    } else if (typeof this.config.logging === 'object') {
      if (this.config.logging.logger) {
        _merge(Logger.config, this.config.logging.logger);
      }
      this.use(new BasicLogging(this.config.logging));
    }
    // ...
  }
```

### Error Log

```
If you have an error log, please paste it here.
```

## Your Environment

- Jovo Framework version used: 4.2.15
- Jovo CLI version used: 4.1.6
- Operating System: Ubuntu 22.04 LTS, 64-bit system

**Comment by rubenaeg** [comment]
A possible solution would be to initialize the `BasicLogging` plugin in `app.initialize()`, since it's not used before and is only responsible for logging requests and responses, which per design can only occur later in the pipeline.

**Comment by jankoenig** [comment]
Thank you @rubenaeg! Your approach makes sense. What do you think @aswetlow?

**Comment by aswetlow** [comment]
Thanks @rubenaeg Yes, it can be moved to `app.initialize()`

**Comment by jankoenig** [comment]
Thank you for the PR @rubenaeg 🎉 

The fix was released today: https://github.com/jovotech/jovo-framework/releases/tag/2022-06-16-patch
