### ISSUE TITLE
Google Conversational Actions sunsetting June 13, 2023

### ISSUE THREAD

**Issue by robinvandenb** [jovotech/jovo-framework#1352]
Recently Google announced that they're sunsetting Conversational Actions on June 13, 2023. Which is what is used by Jovo v4.
Is there any news on possible solutions, migrations and/or re-introduction of v3 support on Dialogflow ES?

**Comment by jrglg** [comment]
Correct me if I'm wrong, but what's the point of having Dialogflow?  the
purpose of Google CA was to allow integration with Google Assistant.

I think now its time to use Jovo Core for other integrations like Alexa,
Lex, Instagram, Web Clients etc.

App Actions is the new solution. Anyone tried it? Has Jovo anything to do
there?

**Comment by jankoenig** [comment]
Hi @robinvandenb, I posted some thoughts here: https://community.jovo.tech/t/google-conversational-actions-sunset/1892
