### ISSUE TITLE
Missing `input` property in StoredElementHistory

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1354]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Is this interface missing `input` property? (https://www.jovo.tech/docs/data#history)

```
export interface StoredElementHistory extends StoredElement {
    size?: number;
    asr?: StoredElement | boolean;
    state?: StoredElement | boolean;
    output?: StoredElement | boolean;
    nlu?: StoredElement | boolean;
    request?: StoredElement | boolean;
    response?: StoredElement | boolean;
}
```

## Your Environment

- Jovo Framework version used: latest
- Operating System:

**Comment by jankoenig** [comment]
Thank you @jrglg! The fix was released last week
