### ISSUE TITLE
Card gets lost if native response with directives is present

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#1356]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I created an output class which returns a single output template with:
- a message
- a reprompt
- a card (which will be converted to an APL document)
- a `platforms.alexa.nativeResponse.response.directives` array which contains a Dialog.ElicitSlot directive

What I expect is a response with an outputSpeech, a reprompt and 2 directives (the dialog one and the apl render document one).

## Current Behavior

Currently I only get an outputSpeech, a reprompt and only one directive (the dialog one), so it seems that the card gets lost or overwritten by the nativeResponse's directive.

Note: cards get correclty trasformend into an APL document in all other cases.

## Your Environment

- Jovo Framework version used: 4.2.2
- Operating System: PopOs

**Comment by jankoenig** [comment]
Hi @acerbisgianluca,

Thanks for flagging this. Could you create a repository with a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? This would help us investigate the issue more quickly.

Thank you,
Jan

**Comment by acerbisgianluca** [comment]
Hey @jankoenig, sure!

Here it's https://github.com/vocalime-base/jovo-issue-1356. Just run `npm test` and you'll see the problem I'm facing.

**Comment by acerbisgianluca** [comment]
@jankoenig I think that this issue is also affecting dynamic entities.

If I use the `listen` property to set dynamic entities, while at the same time adding an APLA directive in the `nativeResponse`, only the APLA directive appears in the output.

The problem in both cases seems to be the merge between the sanitized Jovo output and the native response object, which appears to take the precedence.

**Comment by acerbisgianluca** [comment]
Awesome, it works now! Thanks
