### ISSUE TITLE
Platform Alexa - ConnectionAskForPermissionConsentOutput inputs mismatch

### ISSUE THREAD

**Issue by bayont** [jovotech/jovo-framework#1359]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Code
[`According to Amazon Developer Docs`](https://developer.amazon.com/en-US/docs/alexa/custom-skills/use-voice-forward-consent.html#how-to-initiate)
```js
...
input: {
   '@type': 'AskForPermissionsConsentRequest',
   '@version': '2',
   'permissionScopes': this.options.permissionScopes
},
...
```

## Current Code
[`jovo-framework code problem`](https://github.com/jovotech/jovo-framework/blob/726eb02291ce0b396f8982b1392f71646b111f0d/platforms/platform-alexa/src/output/templates/ConnectionAskForPermissionConsentOutput.ts#L44-L45)
```js
...
input: {
   '@type': 'PrintWebPageRequest',
   '@version': '1',
   'permissionScopes': this.options.permissionScopes
},
...
```

**Comment by jankoenig** [comment]
Thank you for flagging @bayont!

Interested in submitting a PR with the fix? The file can be found here: https://github.com/jovotech/jovo-framework/blob/v4/dev/platforms/platform-alexa/src/output/templates/ConnectionAskForPermissionConsentOutput.ts

You can learn more here: https://www.jovo.tech/docs/contributing#pr-workflow

Thanks!
Jan

**Comment by jankoenig** [comment]
Thank you for the fix @bayont 🎉 

It was released here: https://github.com/jovotech/jovo-framework/releases/tag/2022-06-28-patch
