### ISSUE TITLE
Error mongodb-client-encryption at bundle script

### ISSUE THREAD

**Issue by jrglg** [jovotech/jovo-framework#1381]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Other... Please describe:

## Current Behavior

Error thrown at `build` script:

![image](https://user-images.githubusercontent.com/52841892/180431589-5ef34009-c060-48d5-a443-096b22fa37f6.png)

I don't know much about it. Should we add `mongodb-client-encryption` in MongoDb integration?

I don't know the implications of `--external:mongodb-client-encryption`

### Error Log

```
> esbuild --bundle --outfile=bundle/index.js --sourcemap --minify --keep-names --platform=node --target=node14 --format=cjs  --external:aws-sdk --external:@oclif/* --external:@jovotech/cli* --external:@alexa/* "src/app.desarrollo.ts"
✘ [ERROR] Could not resolve "mongodb-client-encryption"
    node_modules/.pnpm/mongodb@4.8.0/node_modules/mongodb/lib/utils.js:1126:42:
      1126 │ ... mongodbClientEncryption = require('mongodb-client-encryption');
           ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "mongodb-client-encryption" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
1 error
npm ERR! code ELIFECYCLE```

## Your Environment

<!--- Include as many relevant details about the environment where the bug was discovered -->

- Jovo Framework version used: 4.2.20
- Operating System: Win10, Gitlab pipeline, everywhere

**Comment by jankoenig** [comment]
I would recommend adding `--external:mongodb-client-encryption` to the `bundle` script (similar to e.g. `--external:aws-sdk`)

**Comment by jankoenig** [comment]
@jrglg did `--external:mongodb-client-encryption` help? If so, we can add this to the documentation and close this issue. Thanks!

**Comment by jrglg** [comment]
Yes it worked.

I'll let you know if anything fails in the future

Thank you

**Comment by jankoenig** [comment]
Thank you @jrglg! I added a note about this to the MongoDb integration docs: https://www.jovo.tech/marketplace/db-mongodb#deployment
