### ISSUE TITLE
xhr poll error https://webhook.jovo.cloud/ Certificate has Expired

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-framework#1383]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:

## Expected Behavior

jovo run

## Current Behavior

Could not connect to socket server at https://webhook.jovo.cloud: xhr poll error.

### Error Log

```
Could not connect to socket server at https://webhook.jovo.cloud: xhr poll error.
```

## Your Environment

- Jovo Framework version used: 4.1.3
- Operating System: MacOs 12.5

![image](https://user-images.githubusercontent.com/26212386/180671900-9572b7b6-c6c4-4ef7-8b64-8fee1c82db10.png)

**Comment by bayont** [comment]
![image](https://user-images.githubusercontent.com/25829941/180713078-636b3de7-1f48-4d0c-8571-76612182008a.png)

SSL certificate expired yesterday, so give them some time to regenerate a new one :wink:

**Comment by aswetlow** [comment]
Fixed...

My bad... I will set up a renewal cronjob and it won't happen again.
