### ISSUE TITLE
Documentation on $delegate call parameter config outdated

### ISSUE THREAD

**Issue by fbublitz** [jovotech/jovo-framework#1399]
## I'm submitting a bug report jovo.$delegate documentation

 

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
The documentation advertises that when making a $delegate call like this

```typescript
yourHandler() {
  return this.$delegate(YesNoComponent, {
    resolve: { yes: this.onYes },
  -->config: { myProperty: 'myValue' }
  });
}
```
the object handed in at property **config** would be available within the component that was delegated to 
under `this.config`
## Current Behavior
Instead it is available under `this.$component.config`.

This cost me quite some time today.

**Comment by jankoenig** [comment]
Thank you @fbublitz! I updated the docs accordingly
