### ISSUE TITLE
CanFulfillIntentRequest failed with version 4.3.1

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-framework#1426]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

With version 4.3.1 Request of type CanFulfillIntentRequest are map to type INTENT
![Capture d’écran 2022-09-28 à 15 46 11](https://user-images.githubusercontent.com/6285221/192795575-2938500a-5d16-435e-9dfc-caa4f8f6cba1.png)

With version 4.3.0 the same request is map correctly with the type  CanFulfillIntentRequest
![Capture d’écran 2022-09-28 à 15 49 25](https://user-images.githubusercontent.com/6285221/192796241-36218d9f-3e56-476e-899c-a1ac6b64d88c.png)

With version 4.3.0 
    jovo.$input.type will return  'CanFulfillIntentRequest'
With version 4.3.1 
    jovo.$input.type will return  'INTENT'

**Comment by jankoenig** [comment]
Thank you @kouz75! Working on a fix

**Comment by jankoenig** [comment]
The fix was just released: https://github.com/jovotech/jovo-framework/releases/tag/2022-09-28-patch
