### ISSUE TITLE
Jovo 4.5.0 Error in JovoDebugger dependency makes it unusable

### ISSUE THREAD

**Issue by fbublitz** [jovotech/jovo-framework#1470]
## I'm submitting a bug report
I dont know if you can do anything about this, but since Jovo 4.5.0 when using Jovo Debugger, any request leads to a Maximum _call stack size exceeded_ error, rooting in one of the libraries it is using.

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Jovo Debugger should be usable

## Current Behavior
When using Jovo Debugger, any request (tried LAUNCH and Intent requests) leads to a Maximum _call stack size exceeded_ error, rooting in one of the libraries it is using.
This is introduced in Jovo 4.5.0 because i checked with Jovo 4.4.0 and it was fine.
As can be seen from the Error Log the library **has-binary2** throws the error, which is a dependency of the **socket.io-client**
**socket.io-client** is only used by JovoDebugger package and the jovo cli run command in my project

from npm list
├─┬ @jovotech/plugin-debugger@4.5.0
│ ├── @jovotech/framework@4.5.0 deduped
│ ├── @jovotech/nlu-nlpjs@4.5.0 deduped
│ ├── @jovotech/platform-core@4.5.0 deduped
│ ├─┬ @nlpjs/lang-de@4.23.4
│ │ └── @nlpjs/core@4.23.4 deduped
│ ├─┬ @nlpjs/lang-en@4.23.4
│ │ ├── @nlpjs/core@4.23.4 deduped
│ │ └── @nlpjs/lang-en-min@4.23.4
│ ├─┬ @nlpjs/lang-es@4.23.4
│ │ └── @nlpjs/core@4.23.4 deduped
│ ├─┬ @nlpjs/lang-fr@4.23.4
│ │ └── @nlpjs/core@4.23.4 deduped
│ ├─┬ @nlpjs/lang-it@4.23.4
│ │ └── @nlpjs/core@4.23.4 deduped
│ ├── fast-deep-equal@3.1.3
│ ├── lodash.clonedeep@4.5.0 deduped
│ ├─┬ open@8.4.0
│ │ ├── define-lazy-prop@2.0.0
│ │ ├── is-docker@2.2.1
│ │ └── is-wsl@2.2.0
│ ├─┬ **socket.io-client@2.5.0**
│ │ ├── backo2@1.0.2
│ │ ├── component-bind@1.0.0
│ │ ├── component-emitter@1.3.0
│ │ ├── debug@3.1.0
│ │ ├── engine.io-client@3.5.3
│ │ ├── **has-binary2@1.0.3**
│ │ ├── indexof@0.0.1
│ │ ├── parseqs@0.0.6
│ │ ├── parseuri@0.0.6
│ │ ├── socket.io-parser@3.3.2
│ │ └── to-array@0.1.4
│ └── uuid@8.3.2

### Error Log
RangeError: Maximum call stack size exceeded
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:30:20)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)
    at hasBinary (myProjectRoot/node_modules/has-binary2/index.js:58:59)

```
If you have an error log, please paste it here.
```

## Your Environment

- Jovo Framework version used: 4.5.0
- Operating System: ubuntu 22.04

**Comment by aswetlow** [comment]
Hey @fbublitz 

I can't reproduce it with this setup: 

```
jovo new v450
cd v450
jovo run
```
```typescript
// GlobalComponent.ts
@Global()
@Component()
export class GlobalComponent extends BaseComponent {

  constructor(jovo:Jovo, options: UnknownObject | undefined, private orderService: OrderService) {
    super(jovo, options);
  }

  LAUNCH() {
    this.orderService.performOrder();
    return this.$redirect(LoveHatePizzaComponent);
  }
}
```

app.ts
```typescript
...
 providers: [OrderService],
...
```

OrderService.ts 
```typescript
import { Injectable } from "@jovotech/framework";

@Injectable()
export class OrderService {
    performOrder() {
        console.log('order performed');
        
    }
}
```

**Comment by fbublitz** [comment]
True, cannot reproduce in a more basic project either. Must be an unlucky interaction with one of our libraries.
