### ISSUE TITLE
Jovo Debugger stopped showing $output

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#1540]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

In the past, the Jovo Debugger showed `output` entries in the Lifecycle list

## Current Behavior

The `$output` nodes are not being shown:

Tried both of these configurations:

```
// app.dev.ts
new JovoDebugger({
  ignoredProperties: ['$app', '$handleRequest', '$platform', '$dew'],
}),
```

```
// app.dev.ts
new JovoDebugger({
  includedProperties: [...DEFAULT_INCLUDED_PROPERTIES],
}),
```
Here are the values for:
```
DEFAULT_INCLUDED_PROPERTIES [
  '$request',  '$id',
  '$input',    '$history',
  '$device',   '$session',
  '$entities', '$cms',
  '$route',    '$user',
  '$data',     '$output',
  '$response'
]
```

Also, the documentation needs to be updated to explain how both `includedProperties` and `ignoredProperties` work together.

### Error Log

No error log.

## Your Environment

- Jovo Framework version used: 4.5.5
- Operating System: Windows 11

**Comment by jankoenig** [comment]
Thank you @rmtuckerphx! @aswetlow fixed this with the latest release
