### ISSUE TITLE
entity key, value, id all the same for Google home

### ISSUE THREAD

**Issue by prodigylabs** [jovotech/jovo-framework#219]
## I'm submitting a...

- [X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Expected behaviour from documentation is as follows
"The value is the original input value (what the user said), and the key is the value of the entity it is being resolved to"

## Current Behavior

The key , value and id all contain the same string (this the resolved entity). The value does not contain the original input

My entity is called "theItem", here is the output from console.log ('Item = ' + JSON.stringify(theItem) )

Item = {"name":"theItem","key":"pool tarp","value":"pool tarp","id":"pool tarp"}

"pool tarp" is the resolved value, the actual user input is "pool liner"
this is printed elsewhere in log

"outputContexts": [
		{
			"name": "projects/xxx-xxx-xxx-xxx/agent/sessions/1234567890/contexts/google_assistant_input_type_voice",
			"parameters": {
				"Item": "pool tarp",
				"Item.original": "pool liner"
			}
		},
### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by jankoenig** [comment]
Should be fixed with `v2`
