### ISSUE TITLE
Jovo throws an error when using the Lambda function through Amazon API gateway with a Map Template

### ISSUE THREAD

**Issue by apanagos** [jovotech/jovo-framework#234]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When making a call through Google Home that is routed through Amazon API Gateway to a Lambda function the handleLambda function should pick up and use the event.body.

## Current Behavior

In jovo.js line 106, it detects that a body is present as is the case for using Map Template, but the code assumes that this is a string instead of a JSON object and tries to parse it. This throws an error.

```
    /**
     * Handles request from lambda
     * @param {*} event
     * @param {*} context
     * @param {*} callback
     * @return {Jovo}
     */
    handleLambda(event, context, callback) {
        this.event = event;
        this.context = context;
        this.callback = callback;

        this.response = callback;

        if (event.body) {
>>>        this.requestObj = JSON.parse(event.body);
            this.apiGateway = true;
        } else {
            this.requestObj = event;
        }

        // prevent from saving locally on lambda
        if (this.app.moduleDatabase.databaseInstances.file) {
            this.config.saveUserOnResponseEnabled = false;
        }
        this.type = BaseApp.TYPE_ENUM.LAMBDA;

        return this;
    }

```
That line should probably be:
**_this.releaseObj = event.body;_**

Unless of course there are other scenarios where event .body is passed as a string. If that is the case then probably a test to see if it is an or a string and an appropriate conversion.

### Error log
```
If you have an error log, please paste it here.
2018-08-17T01:42:17.702Z	c59dee60-a1be-11e8-9c2a-c7bd0a652615	SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at Jovo.handleLambda (/var/task/node_modules/jovo-framework/lib/jovo.js:106:36)
at BaseApp.handleLambda (/var/task/node_modules/jovo-framework/lib/app.js:275:14)
at exports.handler (/var/task/index.js:37:9)
```

## Your Environment

* Jovo Framework version used: 1.x.x
1.4.3
* Operating System:
Running on Lambda

**Comment by aswetlow** [comment]
Hey @apanagos 

Haven't worked with Map Templates yet. Without, `event.body` is a string. I will add a type check.
I can't reproduce this issue though.

**Comment by apanagos** [comment]
Thanks Alex, 

Here is some more information.
In my main Lamba function i have the following (index.js)
```
exports.handler = (event, context, callback) => {
    if(process.env.STAGE!="production")
    {
        console.debug("EVENT [%s]",JSON.stringify(event));
    }
    app.handleLambda(event, context, callback);
};
```

The event variable is an object and I have to use Stringify so it makes sense, since it is a JSON object that event.body is also an object.
I have attached the results from above both for using API Gateway with and with out a Map Template.
The reason I am using the Map Template is that in the Google Action I can add headers and here translate those headers into JSON so I can use in the application. This way I can distinguish between Google Actions coming to the same back end since Google does not send an ID for the app like Alexa sends the skill ID.


[with_map.txt](https://github.com/jovotech/jovo-framework-nodejs/files/2297476/with_map.txt)
[without_map.txt](https://github.com/jovotech/jovo-framework-nodejs/files/2297477/without_map.txt)

**Comment by jankoenig** [comment]
Thanks @apanagos, adding this to the list for `v2`
