### ISSUE TITLE
Support AWS X-Ray Tracing of AWS calls

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#238]
## I'm submitting a...
- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other

## Expected Behavior
Allow a way in configuration to provide an AWS object wrapped with X-Ray to allow for automatic downstream tracing of all AWS calls (DynamoDB, S3, Polly, etc.) or a configuration option to turn on X-Ray tracing.

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-tracing.html

```JavaScript
// lib/integrations/db/dynamoDb.js

var AWSXRay = require('aws-xray-sdk-core');
this.aws = AWSXRay.captureAWS(require('aws-sdk'));

this.dynamoClient = new this.aws.DynamoDB();
this.docClient = new this.aws.DynamoDB.DocumentClient({
    convertEmptyValues: true,
});
```

## Current Behavior
The require statement aws-sdk is not accessible via configuration.

### Error log
n/a

## Your Environment
* Jovo Framework version used: 1.4.1
* Operating System: Windows 10 Pro

**Comment by aswetlow** [comment]
Thanks for the request @rmtuckerphx 
I will put it on my v2 list.

**Comment by aswetlow** [comment]
Added support in v2.1
