### ISSUE TITLE
Support DynamoDB Accelerator Write-Through Caching

### ISSUE THREAD

**Issue by TheCJGCJG** [jovotech/jovo-framework#246]
## I'm submitting a...
- [ ] Bug report
- [ X ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
DynamoDB Accelerator is a write through cache supported by the AWS-SDK (though no X-Ray support) that allows for intelligent, in-memory caching of requests. This could be useful for storing of the sessions that Jovo uses. It's very easy to implement. Using the npm package 'amazon-dax-client'
and replacing the dynamoDB client with.

```
  docClient = new DynamoDB.DocumentClient({ service: new AmaxonDaxClient({ ...config.aws, endpoints: ['dax-url.eu-west-1.aws.amazon.com'] }) })
```

**Comment by aswetlow** [comment]
Added support in v2.1
