### ISSUE TITLE
Typescript scaffolding

### ISSUE THREAD

**Issue by yagooar** [jovotech/jovo-framework#272]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Running `jovo init` should allow to add a flag that will generate a typescript project, instead of the standard js one. Eg:

```bash
jovo init --flavor=typescript
```

This will generate all necessary files and add the correct dependencies (e.g for the type definitions) in order to write a `Jovo` project using typescript.

**Comment by jankoenig** [comment]
Hi @yagooar, thanks! We're launching `v2` of the framework next month, which will be in typescript. Adding this to the the todo list, probably for `jovo new` though.

**Comment by yagooar** [comment]
Great stuff. And thanks btw, Jovo is such a nice tool! Is there a page I can look up the upcoming changes in v2? Starting a project soon and want to avoid having to throw too much of the code away once the new API is released.

**Comment by jankoenig** [comment]
Thanks! Most changes will be under the hood (more modular, easier to extend), so there won't be many things to change, most of them at the app config level, not the intent handling.

Interested in joining our Slack? We're sharing our progress there: https://www.jovo.tech/community

**Comment by jankoenig** [comment]
Hi @yagooar, it's finally here: https://github.com/jovotech/jovo-sample-voice-app-typescript
