### ISSUE TITLE
Support for Actions Transactions (Digital Goods)

### ISSUE THREAD

**Issue by renatoalencar** [jovotech/jovo-framework#277]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

As described [here](https://developers.google.com/actions/transactions/digital/dev-guide-digital), the framework should support the following steps (or at least the step #):

1. Setup a JWT client in order to access the Actions on Google API;
2. Retrieve the digital goods associated with the package name;
3. Determine the actual user's existing goods through the field `user.packageEntitlements`;
4. Trigger the intent `actions.intent.COMPLETE_PURCHASE` with its respective parameters;
5. Receive an `actions.intent.COMPLETE_PURCHASE` intent with the purchase status available.

## Your Environment

* Jovo Framework version used: 1.4.12
* Operating System: macOS High Sierra 10.13.4

I would be glad to provide a PR if you guys accept this.

**Comment by jankoenig** [comment]
Thanks @renatoalencar, a PR would be great!

**Comment by jankoenig** [comment]
This is a great idea @renatoalencar. You can already check out the `v2` branch here if you're interested: https://github.com/jovotech/jovo-framework-nodejs/tree/v2

**Comment by renatoalencar** [comment]
Great

**Comment by renatoalencar** [comment]
## So, this is how I implemented Transactions

I based only on the documentation of the Transactions API for Actions on Google and just for digital goods, not for physical goods. We have to do some extra work to adapt this to Physical Goods.

First we need to start by following the steps on [this documentation](https://developers.google.com/actions/transactions/digital/dev-guide-digital) to link your Android app (yes, I must have a Android app published on Play Store in order to do this), they explicit tell this on the documentation:

> Note: You don't need to have a public Android app to sell digital goods in your Action. If you don't currently have an Android app listed in the Play store, create a blank APK with the BILLING permission and use it to create a release (including closed beta or other non-public options) in the Play console. Learn more about creating an APK on the Android documentation.

But if you're dealing with physical goods, it looks like there is no need for a Android app.

Then, after linking your Android app with your Actions on Google app you will need to grab information about the available products for your app from the transactions API, in order to this you'll also need to generate a service account key.

```js
const path = require('path')
const { JovoClazz } = require('jovo-framework')
const { google } = require('googleapis')
const request = require('request-promise-native')

const config = require('./util').getConfig()

function getJWTClient() {
  return google.auth.getClient({
      keyFile: path.resolve(__dirname, '..', 'service-account.json'),
      scopes: [ 'https://www.googleapis.com/auth/actions.purchases.digital' ],
  })
}

async function getSubscriptions(conversationId, skus) {
  const jwtClient = await getJWTClient()
  const { access_token } = await jwtClient.authorize()

  const subscriptions = await request.post(`https://actions.googleapis.com/v3/packages/${config.packageName}/skus:batchGet`, {
    auth: {
      bearer: access_token,
    },
    json: true,
    body: {
      conversationId,
      skuType: 'SKU_TYPE_SUBSCRIPTION',
      ids: skus
    }
  })

  return subscriptions
}

JovoClazz.prototype.getSubscriptions = async function (skus) {
  const conversationId = this.googleAction()
                             .getRequest()
                             .getGoogleActionRequest()
                             .getConversationId()
  const subscriptions = await getSubscriptions(conversationId, skus)

  return subscriptions.skus
}
```

With this information, you show it to the user and then after select it you dispatch a `actions.intent.COMPLETE_PURCHASE` intent with the selected `skuId`.

```js
const { GoogleAction } = require('jovo-framework')
const { GoogleActionResponseV2 } = require('jovo-framework/lib/platforms/googleaction/googleActionResponseV2')

GoogleActionResponseV2.prototype.completePurchase = function (skuId) {
  this.responseObj = {
    'payload': {
        'fulfillmentText': 'purchase',
        'google': {
            'expectUserResponse': true,
            'systemIntent': {
                'intent': 'actions.intent.COMPLETE_PURCHASE',
                'inputValueData': {
                    '@type': 'type.googleapis.com/google.actions.transactions.v3.CompletePurchaseValueSpec',
                    'skuId': skuId,
                },
            },
            'inputPrompt': {
                'initialPrompts': [
                    {
                        'textToSpeech': 'PLACEHOLDER',
                    },
                ],
                'noInputPrompts': [],
            },
        },
    },
    'outputContext': this.responseObj.outputContext,
  };

  return this;
}

GoogleAction.prototype.completePurchase = function (skuType, id, packageName) {
  this.response.completePurchase({
    skuType,
    id,
    packageName
  })
  this.jovo.emit('respond', this.jovo)
}
```

The user is prompted with the selected purchase and since the user continue the purchase flow, you have to handle the purchase status following [this part of the guide](https://developers.google.com/actions/transactions/digital/dev-guide-digital#4_describe_the_purchase_status).

```js
JovoClazz.prototype.getPurchaseValue = function () {
  const context = this.googleAction()
            .getRequest()
            .queryResult
            .outputContexts
            .find((context) => /actions_intent_complete_purchase$/.test(context.name))
  
  return context.parameters.COMPLETE_PURCHASE_VALUE
}
```

This implementation follow the version 1 of Jovo, for the version to there is some adaptations that is needed to do. Like a said before, I didn't implemented it for physical goods, only for digital goods.

**Comment by renatoalencar** [comment]
Since @aswetlow build the Physical Goods implementation, now we can build digital goods. So, where do we put it? Digital Goods is a little bit different, so I think we could create some kind of module or separated class.

**Comment by jankoenig** [comment]
Thank you! 🎉
