### ISSUE TITLE
Manage port for unit test

### ISSUE THREAD

**Issue by JordanMontel** [jovotech/jovo-framework#295]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

We can run our skill on a specific port.
It will be great to run unit test on the same port and not only on port 3000.

For development a suggestion was made on slack by editing line 63 in the file jovo-framework.lib/tools/testSuites.js and change the hardcoded port.

**Comment by jankoenig** [comment]
Thanks @JordanMontel. This definitely makes sense and we will look into it for `v2`

**Comment by aswetlow** [comment]
This should work (in v2)
```
const conversation = testSuite.conversation({
      httpOptions: { 
             port: PORT 
      }
});
```

**Comment by jankoenig** [comment]
Hi @JordanMontel, also added it to the Docs: https://www.jovo.tech/docs/unit-testing#conversation-configuration

Closing this now. Let us know if you run into any problems
