### ISSUE TITLE
What is Jovo v2 Pattern for getIntentName in NEW_SESSION?

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#308]
## I'm submitting a...
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Code sample
```js
\\ jovo v1
  NEW_SESSION() {

    this.toIntent(this.getIntentName());
  },
```

## Expected Behavior
New session will be forwarded to LAUNCH if conversation mode or to the specific intent if one-shot mode.

## Current Behavior
The code sample does not work. The call to `this.getIntentName()` returns `undefined`.

### Error log
None

## Your Environment

* Jovo Framework version used: 2.0.3
* Operating System: Windows 10

**Comment by rmtuckerphx** [comment]
Looks like `this.getIntentName()` is not needed.

If I have the following handlers defined:

```js
app.setHandler({
    NEW_USER() {
        console.log('NEW_USER');
    },

    NEW_SESSION() {
        console.log('NEW_SESSION');
    },

    LAUNCH() {
        console.log('LAUNCH');
    },
```

They will be called in the following order:

```
NEW_USER
NEW_SESSION
LAUNCH
```

**Comment by jankoenig** [comment]
Thanks @rmtuckerphx. Yes, the new handler execution goes through all the intents step by step, no redirects are needed. Updating the code example. Also, adding `this.getIntentName()` back to the Jovo context for backwards compatibility (it's also in `this.$request.getIntentName` now)

**Comment by jankoenig** [comment]
Didn't find a better place for now, but added it to all the intents where it makes sense in the docs: https://www.jovo.tech/docs/routing/intents#new_session

Thank you!

**Comment by jankoenig** [comment]
Added "Intent Hierarchy" here: https://www.jovo.tech/docs/routing/intents#intent-hierarchy

**Comment by rmtuckerphx** [comment]
Love it!

Change:
LAUNCH (other other intent that is called)

To:
LAUNCH (or any other intent that is called)

**Comment by jankoenig** [comment]
Uff, you're right. Thank you! Done
