### ISSUE TITLE
Empty response when using async/await

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#309]
## I'm submitting a...

- [x] Bug report

## Expected Behavior
The handler to wait on the await before returning a response.

## Current Behavior
The response returns before the await completes.

The code starts as hello-world template and I added some user and session handlers as well as an async/await:

```js
'use strict';

// ------------------------------------------------------------------
// APP INITIALIZATION
// ------------------------------------------------------------------

const { App } = require('jovo-framework');
const { Alexa } = require('jovo-platform-alexa');
const { GoogleAssistant } = require('jovo-platform-googleassistant');
const { JovoDebugger } = require('jovo-plugin-debugger');
const { FileDb } = require('jovo-db-filedb');

const app = new App();

app.use(
    new Alexa(),
    new GoogleAssistant(),
    new JovoDebugger(),
    new FileDb()
);


// ------------------------------------------------------------------
// APP LOGIC
// ------------------------------------------------------------------

app.setHandler({
    NEW_USER() {
        console.log('NEW_USER');
    },

    NEW_SESSION() {
        console.log('NEW_SESSION');
    },

    LAUNCH() {
        console.log('LAUNCH');

        this.toIntent('HelloWorldIntent');
    },

    async HelloWorldIntent() {
        console.log('HelloWorldIntent');
        
        console.log('before await');
        await wait(1000);
        console.log('after await');

        this.ask('Hello World! What\'s your name?', 'Please tell me your name.');

        console.log('end of handler');
    },

    MyNameIsIntent() {
        console.log('MyNameIsIntent');

        this.tell('Hey ' + this.$inputs.name.value + ', nice to meet you!');
    },
});

module.exports.app = app;

const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
```

### Error log
The Console output is:
```
NEW_USER
NEW_SESSION
LAUNCH
HelloWorldIntent
before await
{
	"version": "1.0",
	"response": {
		"shouldEndSession": true
	},
	"sessionAttributes": {}
}
after await
end of handler
```

Looks like if I explicitly `await` the call to `this.toIntent` then it works:
```js
  async LAUNCH() {
    console.log('LAUNCH');

    await this.toIntent('HelloWorldIntent');
  },
```
It there a way for that to happen in the framework and not the skill code?

## Your Environment
* Jovo Framework version used: 2.0.3
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Hey @rmtuckerphx!
I couldn't do it without the await. The handle method needs to know wether there's an async call or not. 
It needs the await or a return before toIntent.

Happy Holidays :)

**Comment by jankoenig** [comment]
Thanks @rmtuckerphx. Here are several things we did to make sure that people don't run into this problem:

* Added `return` statements to all `toIntent` operations in the Jovo Docs
* Added `return` statements to all `toIntent` operations in Jovo Templates
* Added a Jovo Tutorial for async API calls: https://www.jovo.tech/tutorials/api-call

Closing this now. Thanks for pointing this out
