### ISSUE TITLE
Document adding to config and accessing in code

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#310]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I often include a config file in my skills even if they are directing to environment variables. Jovo v2 includes a config file (in fact multiple that can be merged).

I found that I can use the Jovo config file in my handlers and am looking for a convention or approved approach.

Add an `app` section to the `config.js` file to group my config values:

```js
module.exports = {
  logging: true,

  intentMap: {
    'AMAZON.StopIntent': 'StopCancelIntent',
    'AMAZON.CancelIntent': 'StopCancelIntent',
    'AMAZON.HelpIntent': 'HelpIntent',
    'AMAZON.RepeatIntent': 'RepeatIntent',
    'AMAZON.YesIntent': 'YesIntent',
    'AMAZON.NoIntent': 'NoIntent',
    'AMAZON.FallbackIntent': 'FallbackIntent',
  },

  intentsToSkipUnhandled: ['END', 'HelpIntent', 'RepeatIntent'],

  user: {
    context: {
      enabled: true,
    },
    metaData: {
      enabled: true,
    },
  },

  app: {
    publicS3Bucket: process.env.VOICEAPP_PUBLIC_S3BUCKET,
    environmentName: process.env.STAGE,
  },
};
```

Access the config in my handlers:

```js
const bucket = this.$app.config.app.publicS3Bucket;
const isLogging = this.$app.config.logging;
```

With this approach, I could also access any config values for integrations, plugins, or Jovo but that will likely be less common.

An alternate approach would be to expose it right off `this`:

```js
const bucket = this.$config.app.publicS3Bucket;
const isLogging = this.$config.logging;
```

I also use the `dotenv` library during local testing and a `.env` file that is NOT checked into source control.
Since it is needed only for local, I require the module in `index.js` only for Jovo Webhook:

```js
// ExpressJS (Jovo Webhook)
if (process.argv.indexOf('--webhook') > -1) {

  // use .env file only for local
  // eslint-disable-next-line global-require
  require('dotenv').config();



  const port = process.env.PORT || 3000;
  Webhook.jovoApp = app;

  Webhook.listen(port, () => {
    console.info(`Local server listening on port ${port}.`);
  });

  Webhook.post('/webhook', async (req, res) => {
    await app.handle(new ExpressJS(req, res));
  });
}
```

## Current Behavior
No documentation, official approach, or conventions.

### Error log
None

## Your Environment
* Jovo Framework version used: 2.0.3
* Operating System: Windows 10

**Comment by jankoenig** [comment]
Thanks @rmtuckerphx, this makes a lot of sense. I like the idea of making it accessible through `this.$config`.

As a best practice, we considered a `custom` section in the `config.js`:
```javascript
module.exports = {
  logging: true,

  custom: {
    // Your config goes here
  },
};
```

I also like the idea of using `app` instead of `custom`. We should definitely make sure that both don't interfere with other configurations in Jovo

**Comment by jankoenig** [comment]
Thanks a lot @rmtuckerphx, this is now exposed in `this.$app.$config` and documented here: https://www.jovo.tech/docs/config-js#accessing-configurations

Let us know if you have any additional questions.
