### ISSUE TITLE
Multiple directives bug

### ISSUE THREAD

**Issue by morfeusys** [jovotech/jovo-framework#317]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
When I use `this.$alexaSkill.addDirective` and `this.$alexaSkill.$audioPlayer` both custom directive and AudioPlayer directive should appear in a single array of directives in response.

## Current Behavior
Now only Player directive appears in response.

## Your Environment
Jovo Framework 2.0.4
Mac OS X

**Comment by aswetlow** [comment]
Thanks! We fixed it.
