### ISSUE TITLE
Alexa doesn't render a card

### ISSUE THREAD

**Issue by morfeusys** [jovotech/jovo-framework#326]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
When using showImageCard or Alexa specific showStandardCard function, the card should immediately appear in Alexa app.

## Current Behavior
The card doesn't appear in Alexa app.

### Error log
When using jovo local webhook, jovo outputs a correct response with properly composed card field inside the response object. But in Amazon Alexa console there is another output without the card field.

## Your Environment
* Jovo Framework version used: 2.0.4
* Operating System: Mac OS X

**Comment by jankoenig** [comment]
Hey there. Which version of `jovo-platform-alexa` are you using? We fixed a bug in the recent update

**Comment by morfeusys** [comment]
@jankoenig hi! Great! How can I get a version of this package? I just installed jovo-framework 2.0.4

**Comment by morfeusys** [comment]
@jankoenig yes, you're right! fixed in 2.0.3 alexa integration.

**Comment by jankoenig** [comment]
great!
