### ISSUE TITLE
Metadata methods don't work in Alexa player

### ISSUE THREAD

**Issue by morfeusys** [jovotech/jovo-framework#328]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
`
this.$alexaSkill.$audioPlayer
    .setTitle('First Track')
    .setSubtitle('A simple subtitle')
    .addArtwork('https://www.somewhere.com/image.png')
    .addBackground('https://www.somewhere.com/background.jpg')
    // The above method calls need to be before play()
    .play(url, token);
`

Should add title, subtitle, artwork and background image to metadata of the player in Alexa.

## Current Behavior
Doesn't add metadata filed to response.

## Your Environment
* Jovo Framework version used: 2.0.4
* Operating System: Mac OS X

**Comment by aswetlow** [comment]
Fixed! Thanks @morfeusys !
