### ISSUE TITLE
Jovo keeps saying I'm setting everything up

### ISSUE THREAD

**Issue by geethurajasekharan** [jovotech/jovo-framework#329]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:
 Not sure if its actually a bug or i'm doing it wrong..

## Current Behavior

Whatever i try to do with jovo, it says "I'm setting it up" and then nothing. I was able to create a new project though. 

### Error log
```
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo run
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo build
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ node src/index.js
############################################
#  Local FileDB ./../db/db.json created!  #
############################################

geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo run src/index.js
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo build src/index.js
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo run
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ cd src
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill/src$ jovo run
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo get alexaSkill --skill-id amzn1.ask.skill.e36f10d7-0ca8-4c6d-acb7-39c28a91147a
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo get alexaSkill -s  amzn1.ask.skill.e36f10d7-0ca8-4c6d-acb7-39c28a91147a
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo build
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo build --platform alexaSkill
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ node src/index.js --webhook
Local server listening on port 3000.
^Cgeethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ jovo
I'm setting everything up
geethu@geethu-VirtualBox:/mnt/SourceCode/mobi-voice-alexa-video/video-skill$ sudo jovo
[sudo] password for geethu: 
I'm setting everything up
```

## Your Environment

* Jovo Framework version used: 2.x.x
 "jovo-db-filedb": "^2.0.2-beta.6",
    "jovo-framework": "^2.0.2-beta.6",
    "jovo-platform-alexa": "^2.0.2-beta.6",
    "jovo-platform-googleassistant": "^2.0.2-beta.6",
    "jovo-plugin-debugger": "^2.0.2-beta.6"
* Operating System: Unix

**Comment by jankoenig** [comment]
Hi there! Could you tell me which version of the Jovo CLI you're using? `jovo -v`

**Comment by jankoenig** [comment]
Hi there. Somehow, this doesn't show the image. Could you try again?

**Comment by geethurajasekharan** [comment]
Sure, attaching the image.
[image: jovo-v.jpg]

**Comment by jankoenig** [comment]
still can't see an image. could you just copy the text in the console output?

**Comment by geethurajasekharan** [comment]
Are you not able to open the image attachment? It just says "I'm setting
everything up".

**Comment by jankoenig** [comment]
Could you try to reinstall it:

```sh
# Uninstall first
$ sudo rm jovo-cli -g

# Reinstall
$ sudo install jovo-cli -g
```

**Comment by jankoenig** [comment]
Hi @geethurajasekharan, any news?

**Comment by geethurajasekharan** [comment]
I'm so sorry i didnt check my email for some time. I moved on to a few
other high priority tasks that came up. I didnt try re-installing jovo yet.
I can try it out later. you can close this ticket, i'll raise a new one if
it doesnt work for me. I'm suggesting this because we have a couple of apps
that needs to reach the customer in a few months and we're racing against
the clock!

Thanks a ton for looking into my problem.

Regards,
Geethu

**Comment by jankoenig** [comment]
ok sounds good
