### ISSUE TITLE
Official Doc page button URL mistake

### ISSUE THREAD

**Issue by Daniel-Chin** [jovotech/jovo-framework#337]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

On https://www.jovo.tech/docs/, under "Basic Concepts", the "Routing" button should link to https://www.jovo.tech/docs/routing. 
## Current Behavior

The button currently links to https://www.jovo.tech/docs/logic, which does not have content. 
Is it a website refactor mistake?

**Comment by jankoenig** [comment]
Thank you, fixed!
