### ISSUE TITLE
reminder api not responding alwas 

### ISSUE THREAD

**Issue by patadia** [jovotech/jovo-framework#340]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [-] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
 in reminder api it should set reminder 

## Current Behavior

from reminder api i got something went wrong error in catch ...

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by patadia** [comment]
all was from example of remider api 
https://github.com/jovotech/jovo-framework/tree/master/examples/01_alexa/reminders-api

**Comment by jankoenig** [comment]
What error does it show?

**Comment by patadia** [comment]
it workes  when i deploy to alexa developer console  and test..
thanks
