### ISSUE TITLE
request-promise require works good with webhook and simulator but when i buid deploy and upload to aws lamda and test function it will give me an error

### ISSUE THREAD

**Issue by patadia** [jovotech/jovo-framework#343]
## I'm submitting a...

- [-] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

when i build and deploy build folder which contains node modules should be add the request and request promise in it

## Current Behavior

when i upload bundel.zip to aws lamda and test 
it gives error 

### Error log
```
{
  "errorMessage": "Cannot find module 'request-promise'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:474:25)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/app.js:12:13)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)"
  ]
}

If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.x.x
* Operating System:mac

**Comment by jankoenig** [comment]
Hi there. Seems like you upgraded to gulp version `4.0`. The previous version of Jovo only supported gulp `3.9`, but we've upgraded to version 4. To update, please go into your project director and use the `jovo update` command to update to the latest packages
