### ISSUE TITLE
Port AlexaResponse.isDialogXXX functions to v2

### ISSUE THREAD

**Issue by IGx89** [jovotech/jovo-framework#347]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Desired Behavior
Would it be possible to bring back all the res.isDialogXXX functions to Jovo v2 that were in v1? Examples: isDialogDelegate, isDialogElicitSlot, etc. I've ported my app to v2 but still have a number of unit tests commented out due to this missing functionality. If there's a different/better way to do the same thing in v2 I'd love to know -- had no luck finding it yet.

I'd roll my own but there's a decent amount of logic in the original methods (https://github.com/jovotech/jovo-framework/blob/v1/lib/platforms/alexaSkill/alexaResponse.js#L904) that it seems better suited to the framework.

Thanks!

**Comment by aswetlow** [comment]
I can do it next week. But feel free to make a pull request 😅

**Comment by aswetlow** [comment]
Added in v2.1
