### ISSUE TITLE
Multiple google reprompts not working in V2.0.11

### ISSUE THREAD

**Issue by natrixx** [jovotech/jovo-framework#359]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
```
this.$googleAction
          .displayText(googleDisplayText)
          .ask(speechOutputGoogle, ['reprompt', 'reprompt', 'genericClosingMessage']);
```
Should output: 

```
"noInputPrompts": [
                {
                    "ssml": "<speak>reprompt</speak>"
                },
                {
                    "ssml": "<speak>reprompt</speak>"
                },
                {
                    "ssml": "<speak>genericClosingMessage</speak>"
                }
            ]
```

## Current Behavior
currently outputs:

```
"noInputPrompts": [
  {
          "ssml": "<speak>reprompt,reprompt,genericClosingMessage</speak>"
  }
],
```

## Your Environment
* Jovo CLI Version: 2.0.10

Jovo packages of current project:
  jovo-cms-i18next: 2.0.9
  jovo-core: 2.0.9
  jovo-db-dynamodb: 2.0.10
  jovo-db-filedb: 2.0.10
  jovo-framework: 2.0.11
  jovo-platform-alexa: 2.0.12
  jovo-platform-dialogflow: 2.0.10
  jovo-platform-googleassistant: 2.0.12
  jovo-plugin-debugger: 2.0.9

**Comment by jankoenig** [comment]
Should be fixed! Please run `jovo update` in your project directory and try it again. Reopen if the issue still persists. Thanks!
