### ISSUE TITLE
jovo deploy --target zip failing

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#363]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

jovo deploy --target zip should create a bundle.zip file in the root directory of a jovo project. 

## Current Behavior

The command fails and returns: 
![image](https://user-images.githubusercontent.com/40079313/51616021-40893500-1ef7-11e9-9cef-66f4e9ba2f23.png)

### Error log
```
If you have an error log, please paste it here.
```
![image](https://user-images.githubusercontent.com/40079313/51616052-4e3eba80-1ef7-11e9-8c27-2a1c61ef6934.png)

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System: Ubuntu
* Node: v8.10.0
* gulp: v4.0.0

**Comment by jankoenig** [comment]
Hi @VoiceFirstTech, which versions of the Jovo packages are you using? You can find out by doing `jovo -v`

**Comment by jankoenig** [comment]
We just did some more testing. It should work after updating your Jovo packages with `jovo update` and also update to gulp 4. Let me know if the issue still persists. Closing it for now.
