### ISSUE TITLE
Doc page bookmark mistake

### ISSUE THREAD

**Issue by Daniel-Chin** [jovotech/jovo-framework#365]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

On page https://www.jovo.tech/tutorials/deploy-dialogflow-agent, 22:13 2019/Jan/24, 
All the bookmark links don't work due to typos. 

For example, the link
https://www.jovo.tech/tutorials/deploy-dialogflow-agent#step-3-deploying-your-agent-with-the-jovo-cli
should be
https://www.jovo.tech/tutorials/deploy-dialogflow-agent#step-3:-deploying-your-agent-with-the-jovo-cli
(A column symbol is missing.)

**Comment by jankoenig** [comment]
Thank you! Fixed
