### ISSUE TITLE
Alexa / Google Home notification feature

### ISSUE THREAD

**Issue by mrcasablr** [jovotech/jovo-framework#367]
## I'm submitting a...
- [ x] Feature request

## Expected Behavior
Just checking if Alexa / Google Home notification feature is on the roadmap with a ETA? I'm new to google home/alexa and not a seasoned developer to contribute this feature. 

Planning to use jovotech to build a cross platform skill for an app that will include a capability to announce key notifications based on events (for example, there is delivery scheduled in the next 60 minutes, would you like to accept it?).  The actions would be yes/no. There are other capabilities that user will interact with that can be built with capabilities already available on jovotech. This request is specifically for the notification capability.

**Comment by Droppix** [comment]
Great,impatient!

**Comment by jankoenig** [comment]
@Droppix, here are the Docs for Alexa Proactive Events: https://www.jovo.tech/docs/amazon-alexa/proactive-events

**Comment by jankoenig** [comment]
Push Notifications for Google Assistant now work as well 🎉  
https://www.jovo.tech/docs/google-assistant/notifications
