### ISSUE TITLE
Error overwriting port

### ISSUE THREAD

**Issue by lehiarteaga** [jovotech/jovo-framework#372]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
As docs says 'Port' should be overwritten using the flag -p or --port in the 'jovo run' command or using the ENV variable PORT or .env file

## Current Behavior
After creating a new project, i run the jovo run -p 8000 to change the default port (3000) but the port doesn't change. also if i overwrite it using a .env file it shows the success message: Local server listening on port 8000. but it breaks after the launch showing the next log:

Edit: i already checked and the port is not in use.

### Error log
```
Your server must be running for your tests to work.
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3000}
unhandledRejection
{}
Error: connect ECONNREFUSED 127.0.0.1:3000
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3000}
Error: connect ECONNREFUSED 127.0.0.1:3000
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

## Your Environment

* Jovo CLI Version: 2.0.10
* Jovo packages of current project:
  jovo-cms-i18next: 2.0.11
  jovo-core: 2.0.11
  jovo-db-filedb: 2.0.12
  jovo-framework: 2.0.13
  jovo-platform-alexa: 2.0.15
  jovo-platform-dialogflow: 2.0.12
  jovo-platform-googleassistant: 2.0.14
  jovo-plugin-debugger: 2.0.11
* Operating System: OS X - mojave

**Comment by aswetlow** [comment]
Hey @lehiarteaga 
Yeah, looks like a bug.

Workaround for now:

(1)
use ENV `PORT`

or (2)
use ENV `JOVO_PORT`
Change src/index.js line 7 to `const port = process.env.JOVO_PORT || 3000;`
`jovo run -- --port 8000`

**Comment by aswetlow** [comment]
The CLI is fixed.
`jovo run --port 8000` should work now. Please change line 7 in `src/index.js` in your project to `const port = process.env.JOVO_PORT || 3000;`

**Comment by lehiarteaga** [comment]
Thanks
