### ISSUE TITLE
I18n Translations broken with jovo-framework@2.0.13

### ISSUE THREAD

**Issue by internetofvoice** [jovotech/jovo-framework#373]
## I'm submitting a...
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
console.log(this.t("test")) should translate 'test' to 'Hello World' from src/i18n/de-DE.json with contents like 
```
{
    "translation": {
        "test": "Hello World"
    }
}
```
In jovo-framework@2.0.12 this works as expected. Reproducable by exchangeing all  node_modules/jovo* directories from jovo-framework@2.0.13 with jovo-framework@2.0.12 and vice versa.

## Current Behavior
After updating [1] to jovo-framework@2.0.13, translation does not occur, i.e. console.log(this.t("test")) logs 'test' instead of 'Hello World'

[1] My update process looked like this:
```
$ npm update
+ jovo-framework@2.0.13
+ jovo-db-filedb@2.0.12
+ jovo-platform-alexa@2.0.15
+ jovo-platform-googleassistant@2.0.14
+ jovo-plugin-debugger@2.0.11
updated 8 packages and audited 24420 packages in 12.305s
```

### Error log
(none)

## Your Environment
* Jovo Framework version used:  jovo-framework@2.0.13
* Operating System: Debian Linux (Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux)

TIA & best regards, 
Alex.

**Comment by jankoenig** [comment]
Hi @internetofvoice!
I just tried it and it still works for me. If you create a fresh new project with `jovo new <directory> --template i18n`, does it work? Maybe there was an issue with updating the packages

**Comment by internetofvoice** [comment]
Hi Jan,

creating a new project worked perfectly. After throwing my project files in, the problem persists. 

But it's obviously on my side: by using the jovo debugger, I see requests send with locale: "en-US", but I provided just de-DE model & i18n files. After copying their contents to en-US files, everything worked fine. Perhaps I missed something in the setup process for de-DE projects and it accidentially worked with earlier jovo versions. 

So thanks for your quick reply and well, case closed.. :-)

Best rgds,
Alex.

**Comment by internetofvoice** [comment]
Reopening: the problem seems to be in the communication between the jovo debugger and jovo framework in the backend. Steps to reproduce:

´´´ 
$ jovo new test --locale de-DE --template i18n
$ cd test/
$ mv src/i18n/en-US.json src/i18n/de-DE.json
$ jovo build && jovo run
´´´ 
When opening the debugger, with older jovo versions, debugger sends requests with de-DE and the current sends en-US, for which we just "removed" (renamed) the i18n file. I made some quick & dirty screenshots:
![older jovo version](https://user-images.githubusercontent.com/30470240/52007901-c72dab80-24cf-11e9-8cb8-61d4f9a24810.png)
![current jovo version](https://user-images.githubusercontent.com/30470240/52007902-c72dab80-24cf-11e9-8ad0-74cb6b08c220.png)

**Comment by internetofvoice** [comment]
Digging a little deeper: after the steps described as above, we end up with a project that has only de-DE.json files for model and i18n. In this case, enforcing de-DE will also not work:
```config.js
   i18n: {
      lng: "de-DE",
      fallbackLng: "de-DE",
   },    
```
A possible workaround - only useful for projects that support one language - is to push the i18n/de-DE.json underneath en-US requests via config.js:
```config.js
   i18n: {
      resources: {
         'en-US': require('./i18n/de-DE'),
         'de-DE': require('./i18n/de-DE'),
      },
      lng: "de-DE",
      fallbackLng: "de-DE",
   },    
```

**Comment by aswetlow** [comment]
Hey @internetofv 
There was a bug in the JovoDebugger Plugin. We just published the fixed module.

**Comment by internetofvoice** [comment]
Hi Alex,

confirmed: after doing npm update, the problem is gone.

Thanks a lot!
