### ISSUE TITLE
followUpState not working on Alexa

### ISSUE THREAD

**Issue by cumom** [jovotech/jovo-framework#385]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Follow up state works find on Google, but I can't get it to work on Alexa.
```
app.setHandler({
  LAUNCH() {
    this.followUpState('NewState').ask('Say yes or no.');
  },
  AMAZON: {
    YesIntent() {
      this.tell("Why did this happen?");
    },
  },
  NewState: {
    YesIntent() {
      this.tell("It worked.");
    },
  },
});
```

## Current Behavior

The handler for AMAZON.YesIntent is used instead of FollowUpState.YesIntent.

### Error log
```
# The request log shows _JOVO_STATE_ is included (properly?) in the request.
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "...",
		"application": {
			"applicationId": "..."
		},
		"attributes": {
			"_JOVO_STATE_": "NewState"
		},
		"user": {
			"userId": "..."
		}
	},
	"context": {
		"AudioPlayer": {
			"offsetInMilliseconds": 259912,
			"token": "...",
			"playerActivity": "STOPPED"
		},
		"System": {
			"application": {
				"applicationId": "..."
			},
			"user": {
				"userId": "..."
			},
			"device": {
				"deviceId": "...",
				"supportedInterfaces": {
					"AudioPlayer": {}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "..."
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 346,
					"arcMinuteHeight": 216,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1280,
			"pixelHeight": 800,
			"dpi": 160,
			"currentPixelWidth": 1280,
			"currentPixelHeight": 800,
			"touch": [
				"SINGLE"
			],
			"keyboard": []
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "...",
		"timestamp": "2019-02-19T02:59:33Z",
		"locale": "en-US",
		"intent": {
			"name": "AMAZON.YesIntent",
			"confirmationStatus": "NONE"
		}
	}
}
```

## Your Environment

* Jovo Framework version used:
$ jovo --version
Jovo CLI Version: 2.0.15
Jovo packages of current project:
  jovo-cli: 2.0.15
  jovo-cli-core: 2.0.10
  jovo-cli-deploy-lambda: 2.0.11
  jovo-cli-platform-alexa: 2.0.12
  jovo-cli-platform-google: 2.0.10
  jovo-cms-i18next: 2.0.13
  jovo-core: 2.0.13
  jovo-db-dynamodb: 2.0.14
  jovo-db-filedb: 2.0.14
  jovo-framework: 2.0.15
  jovo-platform-alexa: 2.0.18
  jovo-platform-dialogflow: 2.0.15
  jovo-platform-googleassistant: 2.0.17
  jovo-plugin-debugger: 2.0.14
  jovo-webhook-connector: 2.0.4

* Operating System:
Darwin imac5k...comcast.net 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
(MacOS)

**Comment by jankoenig** [comment]
Hey there! Hm, the State is saved in the request. Did you map `AMAZON.YesIntent` to `YesIntent` like explained here? https://www.jovo.tech/docs/routing/intents#intentmap

Amazon's built-in intents are also usually referenced like this:

```js
// This
"AMAZON.YesIntent"() {
      this.tell("Why did this happen?");
  },

// Instead of
AMAZON: {
    YesIntent() {
      this.tell("Why did this happen?");
    },
  },
```

Is this helpful?

**Comment by cumom** [comment]
Thanks jankoenig! After diving into the code, I realized that I could do this:
  NewState: {
    'AMAZON.YesIntent'() {
      this.tell("It worked.");
    },
    YesIntent() {
      this.tell("It worked.");
    }
  }
It's the YesIntent **inside** of the NewState that wasn't getting handled.

Making the developer write or explicitly redirect <State>.AMAZON.<Intent> to <State>.<Intent> for all states and intents seems to defeat the purpose of a framework designed to support both platforms. I'm not sure how to put intents inside of state in the intentMap, so I'll just use the redundancy approach above for now.

Feel free to consider my PR.

**Comment by jankoenig** [comment]
You don't need to consider states in the intentmap, you could just do:

```js
// config.js file
intentMap: {
        'AMAZON.StopIntent': 'END',
        'AMAZON.YesIntent': 'YesIntent'
},
```
And then this would work:
```js
  NewState: {
    YesIntent() {
      this.tell("It worked.");
    }
  }
```

**Comment by jankoenig** [comment]
AMAZON built-in intents and Dialogflow intents work differently very often, so we can't cut out the `AMAZON` part but need to do explicit mapping.

Learn more about different language models here: https://www.jovo.tech/tutorials/alexa-model-to-dialogflow

I hope this helps

**Comment by jankoenig** [comment]
Thanks for closing this issue, glad it was resolved.

If you like what we doing, you can support this project by giving us a star here on GitHub ⭐ or by spreading the word. Thank you 🙌
