### ISSUE TITLE
Proactive Events Does Not Alert Devices

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#399]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Triggering the Alexa Proactive Events API should cause all devices with the skill enabled to display the `AMAZON.MessageAlert.Activated` notification to the customer. 

## Current Behavior

Devices with the skill enabled did not display `AMAZON.MessageAlert.Activated` notification although the intent is triggered.

There are no error messages. That's the most disturbing part.
* We have used the Jovo CLI to publish an update to the Alexa Skills Manifest
We have the proactive events Jovo Project stored in AWS Lambda :cloud:
* We have the AWS API Gateway address as the `uri`: `{API-GATEWAY-ADDRESS}` in project.js :link:
* We have added `hostname`: `{API-GATEWAY-ADDRESS} to the request.js file  :link:
* We have deployed the Alexa Skill Manifest to developer.amazon.com using the Jovo CLI: `jovo build -p alexaSkill --deploy --target info`
* When we run the node file, a notification does not come up on our dot. 

### Error log
```
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.0000000-0000-0000-0000-00000000000",
        "application": {
            "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
        },
        "attributes": {},
        "user": {
            "userId": "amzn1.account.AM3B00000000000000000000000"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
            },
            "user": {
                "userId": "amzn1.account.AM3B00000000000000000000000"
            },
            "device": {
                "deviceId": "amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA",
                "supportedInterfaces": {
                    "AudioPlayer": {}
                }
            },
            "apiEndpoint": "https://api.amazonalexa.com"
        },
        "AudioPlayer": {
            "offsetInMilliseconds": 0,
            "playerActivity": "IDLE"
        }
    },
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.0000000-0000-0000-0000-00000000000",
        "timestamp": "2015-05-13T12:34:56Z",
        "dialogState": "COMPLETED",
        "locale": "en-US",
        "intent": {
            "name": "LaundryAlertIntent",
            "confirmationStatus": "NONE",
            "slots": {}
        }
    }
}
{
    "version": "1.0",
    "response": {
        "shouldEndSession": true
    },
    "sessionAttributes": {}
}
```

## Your Environment

* Jovo CLI version used: 2.0.15
* Operating System: Ubuntu Linux 18

**Comment by VoiceFirstTech** [comment]
Yes we were able to fix this by changing the API request from `EU`(in demo)  to `US`

**Comment by jankoenig** [comment]
Oh, thanks! We need to update this in the docs so people know where to look. cc @KaanKC
