### ISSUE TITLE
⚡️ Add Serverless integration

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-framework#40]

**Comment by theBenForce** [comment]
@jankoenig, do you have a plan for how this would work?

**Comment by jankoenig** [comment]
Not yet @theBenForce, I've been playing with the Serverless framework a little more last week and I really like it. Do you have experience with it? My current idea is to allow users to create a `serverless.yml` file based on the `app.json` and then call `serverless deploy` from `jovo deploy`. However, I think the best way to get started is to create some templates that already come with a `serverless.yml`.

**Comment by theBenForce** [comment]
I've only been using it for a couple weeks as well, but I could build a simple template and modify 
`jovo deploy` to call `serverless deploy` when a `serverless.yml` file is in the project directory.

**Comment by theBenForce** [comment]
@owenm33 I haven't had a chance to work on it. I've personally started using AWS SAM and setup pipelines with that so I'm not sure if I'll come back to working with serverless.

Maybe the jovo cli should be configurable to run a command for deployment instead of integrating with a specific tool?

**Comment by jankoenig** [comment]
Finally done in `v4`: https://www.jovo.tech/marketplace/target-serverless
