### ISSUE TITLE
Critical error - Documentation and default template

### ISSUE THREAD

**Issue by hyperhitesh** [jovotech/jovo-framework#403]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ x ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
 In the default template, the MyNameIsIntent should use `this.$inputs["given-name"].value` to return the input name.

## Current Behavior
 In the default template, the MyNameIsIntent uses `this.$inputs.name.value` which gives an undefined value error as the object reference is wrong. It should be given-name, not name.

### Error log
```
If you have an error log, please paste it here.
```

>   Error -----------------------------------------------------------------
> 
>   Message:
>   Cannot read property 'value' of undefined
> 
>   Stack:
>   TypeError: Cannot read property 'value' of undefined
>       at GoogleAction.MyNameIsIntent (G:\Voice Jovo\HelloWorld\src\app.js:37:46)
>       at Function.applyHandle (G:\Voice Jovo\HelloWorld\node_modules\jovo-framework\src\middleware\Handler.ts:217:43)
>       at handle (G:\Voice Jovo\HelloWorld\node_modules\jovo-framework\src\middleware\Handler.ts:46:23)
>       at <anonymous>
> 
>    ----------------------------------------------------------------------
> 
> 
>   Request details:
>   this.$googleAction initialized
>   this.$type: {"type":"INTENT"}
>   this.$session.$data : {}
>   this.$nlu : {"intent":{"name":"MyNameIsIntent"}}
>   this.$inputs : {"given-name":{"name":"given-name","value":"Jake","key":"Jake","id":"Jake"}}
> 
> 

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System: Windows 10

**Comment by jankoenig** [comment]
Hi there! It depends on which "Parameter Name" the parameter has in the Dialogflow Agent. If you take a look at the Jovo Language Model of the default template, the input is called "name", but references the "@sys.given-name" Dialogflow entity: https://github.com/jovotech/jovo-sample-voice-app-nodejs/blob/0da9d20c96d5fc25334d979ebabfee407684bc75/models/en-US.json#L22

How did you create the agent on Dialogflow? If you don't use the Jovo Language Model and the Jovo CLI, and did it by hand, take a look at that part of the Jovo Google Action tutorial, if you scroll down a little, there's a screenshot that shows that the parameter name is "name": https://www.jovo.tech/tutorials/google-action-tutorial-nodejs#create-a-new-intent:-helloworldintent

Hope this helps,
Jan

**Comment by jankoenig** [comment]
Thanks for closing this issue, glad it was resolved! 

If you like what we doing, you can support this project by giving us a star here on GitHub ⭐ or by spreading the word. Thank you 🙌
