### ISSUE TITLE
hasSessionAttributes doesn't check session value on Dialogflow

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-framework#417]
## I'm submitting a...
- [X ] Bug report

## Expected Behavior
For Dialogflow, hasSessionAttributes method should return `false` if the wrong value is set. 
It should be the same has what it happening for Alexa.

On Alexa
```
    hasSessionAttribute(name: string, value?: any): boolean {  // tslint:disable-line
        if (!this.getSessionAttribute(name)) {
            return false;
        }

        if (typeof value !== 'undefined') {
            if (this.getSessionAttribute(name) !== value) {
                return false;
            }
        }

        return true;

    }
```

## Current Behavior

On Dialogflow 
```
    hasSessionAttribute(name: string, value?: any) { // tslint:disable-line

        const sessionContext =_get(this, 'outputContexts').find((context: Context) => {
            return context.name.indexOf('/contexts/session') > -1;
        });

        if (sessionContext) {
            return typeof _get(sessionContext, `parameters.${name}`) !== 'undefined' ;
        }

        return false;
    }
```

## Your Environment

Jovo CLI Version: 2.0.15

Jovo packages of current project:
  jovo-analytics-dashbot: 2.1.0
  jovo-cli: 2.0.15
  jovo-cli-core: 2.0.10
  jovo-cli-deploy-lambda: 2.0.11
  jovo-cli-platform-alexa: 2.0.12
  jovo-cli-platform-google: 2.0.10
  jovo-cms-i18next: 2.1.0
  jovo-core: 2.1.0
  jovo-db-dynamodb: 2.1.0
  jovo-db-filedb: 2.1.0
  jovo-framework: 2.1.0
  jovo-platform-alexa: 2.1.0
  jovo-platform-dialogflow: 2.1.1
  jovo-platform-googleassistant: 2.1.1
  jovo-plugin-debugger: 2.1.0
  jovo-plugin-error-slack: 2.0.1
  jovo-webhook-connector: 2.0.4

**Comment by jankoenig** [comment]
Thanks @QuentinDela. Yes, this is something that needs to be updated

**Comment by jankoenig** [comment]
This should be fixed now: https://github.com/jovotech/jovo-framework/blob/2cea9207e06f938d4cfdd1b59b6ed02993eda7e7/jovo-integrations/jovo-platform-dialogflow/src/core/DialogflowResponse.ts#L162
