### ISSUE TITLE
Physical Goods Google Transaction

### ISSUE THREAD

**Issue by crazzywizard** [jovotech/jovo-framework#421]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

It is supposed to go to ```TRANSACTION_DECISION``` 

## Current Behavior

It responds with your app is not responding after you say yes to creating order

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.1.2
* Operating System:
Ubuntu 18.04

**Comment by jankoenig** [comment]
What happens after you say yes to creating an order? Please share any logs that might be helpful. Thanks

**Comment by zaijacobs** [comment]
> What happens after you say yes to creating an order? Please share any logs that might be helpful. Thanks

Hello, I believe this is a bug? In the Transaction class I found these lines of codes:

`        if (_get(googleAction.$originalRequest || googleAction.$request, 'inputs[0].intent') === 'actions.intent.TRANSACTION_DECISION') {
            _set(googleAction.$type, 'type', 'ON_TRANSACTION');
            _set(googleAction.$type, 'subType', 'COMPLETE_PURCHASE');
        }`

'COMPLETE_PURCHASE' should be replaced with 'TRANSACTION_DECISION'. If I understand correctly, COMPLETE_PURCHASE is only for digital goods.

**Comment by jankoenig** [comment]
Updated the Google Transaction implementation in v3
