### ISSUE TITLE
Detect Cancel?

### ISSUE THREAD

**Issue by Droppix** [jovotech/jovo-framework#426]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ X] Other... Please describe:

## Question
Hi,

When I display a 'Card' with a function 'ask' (see below my code), and I force close my 'Card' on the mobile (with the button close or button Alexa) while Alexa asks a question (long sentence), it's cut off, and the session isn't closed immediately (I don't receive the END() event), which causes me a problem.
```
 QuestionIntent() {
   this.showImageCard(title, content, imageUrl)                                
         .ask(this.$speech, this.$speech);    // shouldEndSession = false
 },

 END() {
 },

```
Is there a way to detect this interruption and close the session properly?

Thanks

**Comment by jankoenig** [comment]
Are you receiving a request? Any logs? As long as there is no request coming into the app, there is nothing we can do, unfortunately.

**Comment by Droppix** [comment]
Unfortunately, no log / events....

**Comment by aswetlow** [comment]
I just tried it myself. Unfortunately not possible to detect it :/

**Comment by jankoenig** [comment]
Thanks @Droppix for raising this issue. We will forward it to Amazon. Hopefully they will add this functionality soon.

Closing this for now.
