### ISSUE TITLE
Problem Firestore with Lambda

### ISSUE THREAD

**Issue by Droppix** [jovotech/jovo-framework#427]
## I'm submitting a...

- [X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I try use Firestore with your [tutorial]( https://www.jovo.tech/tutorials/deploy-to-google-cloud#create-firestore-database), it's works in local (jovo debugger), and not in Lambda.
My Skill work only without 'firestore'.

### Error log
```
Error in AWS Lambda
...
REPORT RequestId: 4cd0e6e6-f0cd-4d30-81df-b44305ce63b3	Duration: 3003.02 ms	Billed Duration: 3000 ms 	Memory Size: 128 MB	Max Memory Used: 97 MB	
2019-03-20T16:49:16.399Z 4cd0e6e6-f0cd-4d30-81df-b44305ce63b3 Task timed out after 3.00 seconds
```

## Your Environment
* Jovo Framework version used: 2.1.x
* Operating System:Lambda

**Comment by jankoenig** [comment]
Does this help? https://github.com/jovotech/jovo-framework/issues/418#issuecomment-473872650

**Comment by Droppix** [comment]
Unfortunately no, moreover the log on lambda doesn't say much.

**Comment by KaanKC** [comment]
Looks like the task simply timed out. Try to increase it in the `Basic Settings` section of your Lambda function

**Comment by Droppix** [comment]
Works! Thanks

**Comment by jankoenig** [comment]
Great!

**Comment by joe-pellegrino** [comment]
> Looks like the task simply timed out. Try to increase it in the `Basic Settings` section of your Lambda function

@jankoenig took me about 30 minutes to find this lol, maybe its worth adding to the request-promise tutorial.
