### ISSUE TITLE
Add human-readable IntentLogging

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-framework#43]
As suggested by @peternann, there should be a nice and human-readable way to log incoming requests that include information that's helpful for debugging and testing (intents, states, and values), but less cluttered than just logging the full requests.

I usually do it like this, but this misses some of the information and displays other that might not be interesting:

```js
app.setConfig({
    requestLogging: true,
    requestLoggingObjects: ['request'],
   // Other configurations
});
```

@peternann also suggested it to be auto-enabled.

**Comment by rv-ekramer** [comment]
👍
