### ISSUE TITLE
Expanded support for SSML

### ISSUE THREAD

**Issue by jnthnwn** [jovotech/jovo-framework#431]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

There should be support for additional elements of [SSML](https://developers.google.com/actions/reference/ssml), as far as it's supported by either platform.

Certain sentences, words, or possibly sessions should have a programmatic way to add elements such as `prosody` or `sub` to better describe how to speak.

For example:
```
// for an entire sentence
let prosody = { rate: 'slow', pitch: '-2st' };
this.$speech.addText('hello world');
this.$speech.prosody(prosody);
this.tell(this.$speech);

// or for part of a sentence:
this.$speech.addText('hello', { prosody });
this.$speech.addText('world');
this.tell(this.$speech);
```

**Comment by jankoenig** [comment]
Thank you. Yes, this is a great suggestion. I think something like this would also be a great opportunity for a community contribution/pull request if anyone wants to help 💪

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
