### ISSUE TITLE
`ON_SIGN_IN` issues, bot keeps leaving conversation once account is linked

### ISSUE THREAD

**Issue by dyampols** [jovotech/jovo-framework#435]
![Capture](https://user-images.githubusercontent.com/29102596/54934840-8f524b80-4ef5-11e9-967d-8bd507d8034b.PNG)

`ON_SIGN_IN`  not working for me. Conversation / session ends  after Account linking is successful. I get the desired response and then 'my test app' left the conversation. How do I keep the session from terminating?

**Comment by leogiroux** [comment]
Hi did you find a solution solution to share with us I got the same behaviour.
