### ISSUE TITLE
Jovo build with Multiple Alexa Interfaces

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#436]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Running `jovo build` should take all **interfaces** from `project.js` and copy them to **interfaces array** in `platforms/alexaSkill/skill.json 

![image](https://user-images.githubusercontent.com/40079313/54947180-16142200-4f10-11e9-8a60-3ba879a15737.png)

## Current Behavior

If you have **more than one interface listed** `jovo build` will:
* only add the last listed interface to `skill.json`
* delete all other interfaces from `skill.json`

![image](https://user-images.githubusercontent.com/40079313/54947232-2a581f00-4f10-11e9-9cbf-eac3162bf461.png)

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.0.15
* Operating System: Linux Ubuntu

**Comment by jankoenig** [comment]
They need to be added like this:

```js
"interfaces": [
    {
        "type": "INTERFACE_X"
    },
    {
        "type": "INTERFACE_Y"
    {
]
```

**Comment by jankoenig** [comment]
Did this work for you @VoiceFirstTech ?
