### ISSUE TITLE
Which method for updating?

### ISSUE THREAD

**Issue by Droppix** [jovotech/jovo-framework#437]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X ] Other... Please describe:

## Expected Behavior

Once the Skill (v1.0) is deployed (AWS lambda) on the Amazon store, and therefore used by users, what is the method to continue to develop on the same Skill (new version) in order to make improvements  (new Intents for example, ...) without breaking the EndPoint declaration configuration on Amazon for my tests?
Is it necessary to create a new project?
What would be the right working method?

## Your Environment
* Jovo Framework version used: 2.1.x

**Comment by jankoenig** [comment]
Hi there. I would probably use version management like Git and work on a different `branch` and use a separate Lambda function for the development, for example

**Comment by Droppix** [comment]
Ok, but my question is rather how to get a production version (1.0.0) and a development version (1.1.0), with the management of the "EndPoint" on the Alexa project,  because you can't have 2 EndPoints on the same project.

So if I want to keep one version in production (without breaking the EndPoint), and another in development, should I create a new project?

**Comment by jankoenig** [comment]
Yes, we usually use different projects for `dev` and `prod`. Take a look at this video about staging with Jovo: https://www.youtube.com/watch?v=1fOsfy7crqU

**Comment by Droppix** [comment]
Okay, sorry I didn't see your tutorial.

Thanks.

**Comment by jankoenig** [comment]
No problem!

If you like what we doing, you can support this project by giving us a star here on GitHub ⭐ or by spreading the word. Thank you 🙌 We also have a community forum here: https://community.jovo.tech/
