### ISSUE TITLE
CanFulfillIntentRequest does not return valid response

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#438]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Sending the response,` this.canFulfillRequest();` should return the following response:
```
'invocationResponse': {
    'body': {
         'response': {
            'canFulfillIntent': {
                'canFulfill': 'YES' 
            }
        }   
    }
}
```

## Current Behavior

Instead of the expected response I receive:
```
"invocationResponse": {
	"body": {
		"version": "1.0",
		"response": {
			"canFulfillIntent": {}
		},
		"sessionAttributes": {}
	}
},
```

I commented in-depth in the Jovo Forums here: https://community.jovo.tech/t/docs-alexa-canfulfillintentrequest/107/2?u=voice_first

I also replicated the bug in a new Jovo Alexa Skill. I documented the creation in a screencast here: https://youtu.be/vf8OCFZ-f-I

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.0.15
* Operating System: Linux Ubuntu

**Comment by aswetlow** [comment]
Thank you for the detailed bug report. Found and fixed the bug. We will publish an update later today.

**Comment by aswetlow** [comment]
It's fixed. Please update your project.
