### ISSUE TITLE
Add SSML Check

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-framework#448]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Garrett Vargas (@gsdriver) published a great package called `ssml-check` which allows to check for valid SSML in the response (for both Alexa and Google Assistant) before it is sent out. I think this could be a great time-saver to add this to the framework: https://github.com/gsdriver/ssml-check-core/

Here is a post where he describes his process: https://medium.com/@garrettvargas/how-to-find-errors-in-your-ssml-responses-49a81d150ed7

## Current Behavior

Right now, bad SSML isn't discovered before the response is sent out, causing the app to break while users are interacting with it. Most of the time, the error logs aren't very helpful, either.

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by aditya-giri** [comment]
I'd like to pick this up if that's okay.

**Comment by jankoenig** [comment]
That would be great! Thanks @aditya-giri 👍

**Comment by aditya-giri** [comment]
I'd need a little help getting started though. Can you point me in the
right direction?

**Comment by StephaneC** [comment]
@aditya-giri Did you look at [http://garrettvargas.com/ssml.html](http://garrettvargas.com/ssml.html)  
You could add ssml validator  as an utils class or directly when adding ssml to tell/ask?  
Why not in the `toSSML` from `SpeechBuilder`: [/SpeechBuilder.ts](https://github.com/jovotech/jovo-framework/blob/master/jovo-core/src/util/SpeechBuilder.ts)  
cc @jankoenig

**Comment by jankoenig** [comment]
Yes, I would probably do an SSML check in the `platform.output` middleware that turns the Jovo abstracted`$output` object into a platform specific response JSON

**Comment by aditya-giri** [comment]
Hey guys, sorry but I've been busy and probably won't be able to work on this at the moment. Someone else can pick this up instead.

**Comment by StephaneC** [comment]
@jankoenig Why not add it in the `ask`\`tell`methods of [the JOCO class](https://github.com/jovotech/jovo-framework/blob/master/jovo-core/src/core/Jovo.ts).

If not correct ssml, an exception can be thrown.

**Comment by aswetlow** [comment]
I close this issue due to incativity.
