### ISSUE TITLE
Difference between jovo and BotTalk

### ISSUE THREAD

**Issue by pj1527** [jovotech/jovo-framework#454]
I want to develop a voice interaction service and integrate it with my already existing app, I came across jovo and BotTalk to develop it but I am not sure which one to go ahead with and I also do not fully understand the difference between them.

I know its not the forum to ask such question but I just thought that who better to ask then people who use it.

**Comment by jankoenig** [comment]
Hi @pj1527!

Jovo is a developer framework (you write and own the code) and Bottalk is an online service (you write the app based on markup language and they host it).

There are so many differences that I believe the best way to see what suits you better is to take a look at both quickstart guides for an understanding how the tools work:
* https://www.jovo.tech/docs/quickstart
* https://docs.bottalk.de/quickstart/

I think the best place to discuss things like this (in comparison to our GitHub issues) is the Jovo Community Forum: https://community.jovo.tech/
