### ISSUE TITLE
conversation.clearDb() Missing db/tests file. 

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#455]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Running `await conversation.clearDb();` should clear user and session data from conversation

## Current Behavior

I receive an error of missing files in `db/tests` I was unable to find any documentation on this folder on the Jovo website.

![image](https://user-images.githubusercontent.com/40079313/55648368-2056db80-57ae-11e9-8325-2f59aa794e4c.png)

### Error log
```
Can't find db/tests/tov3we.json

      at Conversation.clearDb (node_modules/jovo-core/src/Conversation.ts:134:19)

```

## Your Environment

![image](https://user-images.githubusercontent.com/40079313/55648439-51cfa700-57ae-11e9-976a-e3ea03661029.png)

* Jovo Framework version used: 2.2.0
* Operating System: Ubuntu Linux

**Comment by KaanKC** [comment]
Hey @VoiceFirstTech,

the `db/tests/` folder contains the `json` files, created for the `FileDb` integration for your tests. Each user has their own file, with the file's name being the random user id, which gets generated for each test by default.

When you call `conversation.clearDb()`, the system checks whether the `json` file exists or not. If it does, the file will be deleted, if not it throws the error you received.

So the error is saying that you're trying to delete a file that doesn't exist.

Also, I was not able to reproduce the error with the tests inside the example folder [here](https://github.com/jovotech/jovo-framework/tree/master/examples/javascript/unit-testing).

**Comment by jankoenig** [comment]
That's a good point though @KaanKC, we should probably not throw an error when the file doesn't exist. What do you think?

**Comment by aswetlow** [comment]
`conversation.$user.$data` and `conversation.clearDb()` work only with the FileDb integration so far.

**Comment by aswetlow** [comment]
Oh sorry, I misunderstood the issue. We found the problem and will publish an update later today.

**Comment by aswetlow** [comment]
Done.
