### ISSUE TITLE
Valid characters in entities getting removed 

### ISSUE THREAD

**Issue by mderrien29** [jovotech/jovo-framework#457]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
When building with `jovo build`, jovo is removing the character `'` from entities synonyms. This behavior is only present in Dialogflow, models in Alexa are unaffected. 

## Expected Behavior
As Dialogflow and Alexa both allow it, jovo shouldn't remove this character. It's also problematic in some languages (and as usual, french is one of those). 

Maybe the build stage only check for characters and prints a warning ?

## Your Environment

* Jovo Framework version used: 2.2
* Operating System: Ubuntu

**Comment by aswetlow** [comment]
Oops, sorry. This issue got lost.

@janober fixed it. Please update your Jovo CLI
