### ISSUE TITLE
Carousel items have incorrect format for Actions on Google API v2

### ISSUE THREAD

**Issue by jnthnwn** [jovotech/jovo-framework#458]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

In lists and carousels, Jovo should produce the following structure for option items to Actions on Google:
```
{
    "optionInfo": {
        "key": "MATH_AND_PRIME"
    },
    "title": "Title of the First List Item"
},
```

## Current Behavior

Currently, the structure looks like:
```
{
    "key": "MATH_AND_PRIME"
    "title": "Title of the First List Item"
},
```
Leading to the following `UnparseableJsonResponse`:
```
API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT' error: "(carousel_select.items[1]) key: Cannot find field.".
```

## Your Environment

* Jovo Framework version used: 2.1.5
* Operating System: macOS

**Comment by aswetlow** [comment]
Hm, can't reproduce, using the [Google Assistant examples project](https://github.com/jovotech/jovo-framework/tree/master/examples/javascript/02_googleassistant/cards).

I don't get any  error messages. That's the relevant part of my response object.

List:
```json
{
		"optionInfo": {
				"key": "Listitem2key",
				"synonyms": []
		},
		"title": "Show a Carousel",
		"description": "Carousel"
},
{
		"optionInfo": {
				"key": "Listitem3key",
				"synonyms": []
		},
		"title": "Show a Table",
		"description": "Table"
}
```

Carousel:
```json
 {
		"optionInfo": {
				"key": "Carouselitem1key",
				"synonyms": []
		},
		"title": "Show a BasicCard",
		"description": "BasicCard",
		"image": {
				"url": "http://via.placeholder.com/450x350?text=Basic+Card",
				"accessibilityText": "accessibilityText"
		}
},
{
		"optionInfo": {
				"key": "Carouselitem2key",
				"synonyms": []
		},
		"title": "Show a List",
		"description": "Description2",
		"image": {
				"url": "http://via.placeholder.com/450x350?text=Basic+Card",
				"accessibilityText": "accessibilityText"
		}
}

```

Do I miss something?

**Comment by aswetlow** [comment]
Hey @jnthnwn! Did you solve your issue?

**Comment by jnthnwn** [comment]
Hey, sorry for the delayed response! I did fix this error - I believe it was related to how I was calling some of the methods here: https://www.jovo.tech/docs/reference/CarouselItem.html

For example, `carouselItem.setImage(url, accessibilityText)` as documented resulted in the error above, but `carouselItem.setImage({url, accessibilityText})` worked. Similar to `setOpenUrlAction`
