### ISSUE TITLE
Test coverage hack

### ISSUE THREAD

**Issue by renatoalencar** [jovotech/jovo-framework#469]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe: Hack description.

## Expected Behavior

I have to run tests and then generate a coverage report in order to keep tracking on how much of my code is being tested. Jest has built in support for coverage report, but as long as to run tests on Jovo you need to run the Jovo server in separated process, Jest is not able to get any coverage details because any other code beyond the tests is running on the Jest process.

So in order to get some reports I need to dispatch and get every response on the same process. The initial solution I've found was to run the server literally on the same process, but I turns out that this is not an actual good idea.

Jovo has this `Host` abstraction in order to encapsulate the "gateway" used to handle the request, like Express, Google Cloud Function, AWS Lambda, etc. I've figured out that I could use this to dispatch my own self created request (using `requestBuilder`), I just had to override the `httpRequest` method of the `Conversation` class.

## Code snippets

Build my self hacky Host setup:

```js
class TestHost {
    constructor(req, headers) {
        this.$request = req
        this.headers = headers
    }

    getRequestObject() {
        return this.$request
    }

    setResponse(res) {
        return new Promise((resolve) => {
            this.resolve(JSON.stringify(res))
            resolve()
        })
    }

    fail(error) {
        this.reject(JSON.stringify({
            code: 500,
            msg: error.message
        }))
    }

    onResolve(resolve) {
        this.resolve = resolve
        return this
    }

    onReject(reject) {
        this.reject = reject
        return this
    }
}
```

Override the `httpRequest` method:

```js
const { Conversation } = require('jovo-core')

Conversation.httpRequest = function(postData, options) {
    return new Promise((resolve, reject) => {
        const host = new TestHost(JSON.parse(postData), options.headers)
            .onResolve(resolve)
            .onReject(reject)
        app.handle(host)
    })
}
```

I manage to run this writing this to `util.js` file inside my `tests` directory and copying my `config.js` file to the project root. I also set the `logging` configuration to `false` in order to have a cleaner test output, but it can be interesting if I write it into a file instead.

## Your Environment

* Jovo Framework version used: 2.2.1
* Operating System: macOS 10.14.4

**Comment by aswetlow** [comment]
This is a great idea! Feel free to make a PR :)

**Comment by stephen-wilcox** [comment]
Thanks for sharing this, Renato.  I've put something similar into Pull Request #488, adding a separate sendToApp method to the Conversation class.

**Comment by renatoalencar** [comment]
@stephen-wilcox built this, so I'm closing this issue.
