### ISSUE TITLE
CanFulfillIntentRequest does not return valid response with slots

### ISSUE THREAD

**Issue by dyoung-sk** [jovotech/jovo-framework#476]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
In responding to CanFulfillIntent for Intents with slots, we are expecting back a response which looks like this:
```
{
    "version":"1.0",
    "response":{
        "canFulfillIntent": {
            "canFulfill": "YES",
            "slots":{
                "slotName1": {
                    "canUnderstand": "YES",
                    "canFulfill": "YES"
                },
               "slotName2": {
                    "canUnderstand": "YES",
                    "canFulfill": "YES"
                }
            }
        }
    }
}
```

## Current Behavior
Currently, output for intents with slots looks like this when built using the this.canFulfillSlot command prior to this.canFulfillRequest:
```
{
	"version": "1.0",
	"response": {
		"canFulfillIntent": {
			"canFulfill": "YES",
			"slots": {
				"slotName": "color",
				"canUnderstandSlot": "YES",
				"canFulfillSlot": "YES"
			}
		}
	}
}

```

Response looks correct for Intents with no slots
This causes the skill to NOT pass Functional Tests as run from the Alexa Console. Output looks like this:
`This skill implements the Alexa CanFulfillIntentRequest interface, but the CanFulfillIntentRequest interface call’s response is blank or not in the defined structure. We found your endpoint to respond with unsupported format for MyColorIsIntent. `

### Error log
NONE

## Your Environment
* Jovo Framework version used: 2.2.2

**Comment by jankoenig** [comment]
Hi @dyoung-sk, this should be fixed with this commit: https://github.com/jovotech/jovo-framework/commit/39bc93e27d5bd06a108b28620d349ebca4ed88e7 

Could you try it out after doing `jovo update`?

**Comment by dyoung-sk** [comment]
Tested, verified working now

**Comment by jankoenig** [comment]
Great!
