### ISSUE TITLE
TypeError: this.toIntent is not a function

### ISSUE THREAD

**Issue by DzmitryKom** [jovotech/jovo-framework#480]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x ] Other... Please describe:
After upgrading from "jovo-db-filedb": "^2.0.2",
    "jovo-framework": "^2.2.1",
    "jovo-platform-alexa": "^2.0.2",
    "jovo-platform-googleassistant": "^2.0.2",
    "jovo-plugin-debugger": "^2.0.2",
to latest getting: 
toIntent is not a function!!!! and setAlexaHandler not a function ... 
const handlers = {
    LAUNCH() {
        return this.toIntent('HelloIntent');
    },
    HelloIntent() {
        this.ask('Hello, how can I help you today? xxx', 'Please tell me xxxx.');
    },
}
## Expected Behavior

redirects to HelloIntent

### Error log
```

  Hint:
  This might be an issue with upgrading the Jovo packages. Try to run `jovo update` instead of `npm install`

If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 2.x.x
* Operating System:

**Comment by jankoenig** [comment]
Hi @DzmitryKom,

This sometimes happens when there are two conflicting versions of npm modules in your `package-lock.json`. Here are a few steps that can help you solve this:

* Delete your `node_modules` folder
* Delete your `package-lock.json` file
* Do `npm install`
* Only update Jovo packages with `jovo update`, not `npm install`

**Comment by DzmitryKom** [comment]
Hi Jan,
I was updating true jovo update , will try again ... I fix it by reverting
package.json  to previously committed and npm install .
As I sad will try to update again . Thanks for your support.

Dzmitry Komsa

**Comment by jankoenig** [comment]
Thanks!

If you like what we doing, you can support this project by giving us a star here on GitHub ⭐ or by spreading the word. Thank you 🙌 We also have a community forum here: https://community.jovo.tech/
