### ISSUE TITLE
Tree-shakable imports

### ISSUE THREAD

**Issue by Jefftopia** [jovotech/jovo-framework#483]
## I'm submitting a...

- [ ] Bug report
- [X ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
:wave: Requesting tree-shakable imports and exports for Jovo.

e.g.,

`import get from 'lodash.get';` or `const get = require('lodash.get');` rather than `const _ = require('lodash');`.
The latter type of import results in unnecessarily large app bundles.

https://webpack.js.org/guides/tree-shaking/
Also
https://developer.epages.com/blog/tech-stories/typescript-codesplitting-treeshaking/ (edited) 
## Current Behavior
Non-tree-shakable imports ;-) Jovo v2 made a good step forward by offering bundling via Gulp. There is a good opportunity to push this using webpack or @zeit/ncc.

## Your Environment

* Jovo Framework version used: ^2.2.2

**Comment by jankoenig** [comment]
Hey @Jefftopia thanks for the suggestion! Any reason why you closed this?

Thanks,
Jan

**Comment by Jefftopia** [comment]
@jankoenig Ha, well, I looked at a bunch of source files and it looks like most of your imports already _are_ tree-shakable ;-) Happy to keep this open if you think this is worth close examination and audit. 

Here's one import that could be simplified: https://github.com/jovotech/jovo-framework/blob/master/jovo-core/src/Util.ts
