### ISSUE TITLE
problem in database connection jovo

### ISSUE THREAD

**Issue by sarigasurendranms** [jovotech/jovo-framework#486]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I am developing a jovo app for google action and  trying to connect jovo app with mongoDB it doesn't work.I have to check a condition
 if (this.$user.$data.newUser === undefined)
but it is showing that Cannot read property 'newUser' of undefined.

config.js
```
module.exports = {
    logging: true,
 
    intentMap: {
       'AMAZON.StopIntent': 'END',
    },
 
    db: {
    MongoDb: {
      databaseName: 'dbname',
        collectionName: 'collectnName',
        uri: 'mongodb+srv://usrname:psswrd@cluster0-jnnai.mongodb.net/test?retryWrites=true'
    }
  }
 };
 
```
## Current Behavior
when I tested locally it is working fine and datas are entered into the database .But when I execute it in aws lambda it shows error.please help

### Error log
```
{
  "errorMessage": "Cannot read property 'newUser' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "AlexaSkill.LAUNCH (/var/task/app.js:31:29)",
    "Function.applyHandle (/var/task/node_modules/jovo-framework/dist/src/middleware/Handler.js:178:43)",
    "handle (/var/task/node_modules/jovo-framework/dist/src/middleware/Handler.js:38:23)",
    "<anonymous>"
  ]
}
```

## Your Environment

* Jovo Framework version used:Jovo CLI Version: 2.2.3

* Operating System:

**Comment by rubenaeg** [comment]
Hi @sarigasurendranms , are there any datasets in your database originating from aws lambda or is the app not writing anything at all when deployed?

**Comment by rubenaeg** [comment]
If not, this could be a problem with IP whitelisting. If your database only has your local PC IP on its whitelist, connecting on AWS won't work. The easiest solution for this would be to add 0.0.0.0/0 to the IP whitelist.

**Comment by sarigasurendranms** [comment]
The app is not writing anything at all when deployed. I have added the IP address 0.0.0.0/0 to the whitelist now also same error occurs and also time out occurs.
