### ISSUE TITLE
  WARN: Jovo instance is not available. ON_ERROR doesn't work here

### ISSUE THREAD

**Issue by Yashwanthyashwanth** [jovotech/jovo-framework#487]
## Hi, submitting as a

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
I'm new to jovo framework, it is showing webhook execution successful in dialog flow but getting cant handle request object message with code 500 as fulfillment response.

### Error log
```
  Error -----------------------------------------------------------------

  Code:
  ERR_NO_MATCHING_PLATFORM

  Message:
  Can't handle request object.

  Stack:
  Error: Can't handle request object.
      at App.handle (C:\Users\VA Dhanya\assistant1\node_modules\jovo-core\src\BaseApp.ts:197:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  Module:
  jovo-core

  Hint:
  Please add an integration that handles that type of request.

   ----------------------------------------------------------------------


   ----------------------------------------------------------------------

  WARN: Jovo instance is not available. ON_ERROR doesn't work here
```

## Your Environment

* Jovo Framework version used: 2.2.2
* Operating System: windows 10

**Comment by Yashwanthyashwanth** [comment]
I was working with v1 of dialog flow i upgraded that to v2 now it is working.

**Comment by surajraj99** [comment]
@Yashwanthyashwanth Did you ever figure out this problem?

**Comment by gody** [comment]
Same problem here

**Comment by soulshifter** [comment]
Still coming for me.

**Comment by aswetlow** [comment]
Could you post the initialization part of your code?

Something like that:

```
const { App } = require('jovo-framework');
const { Alexa } = require('jovo-platform-alexa');
const { GoogleAssistant } = require('jovo-platform-googleassistant');
const { JovoDebugger } = require('jovo-plugin-debugger');
const { FileDb } = require('jovo-db-filedb');

const app = new App();

app.use(
    new Alexa(),
    new GoogleAssistant(),
    new JovoDebugger(),
    new FileDb()
);

```

**Comment by bc-mpavan** [comment]
I have the same problem. This happens to me when I test from DialogFlow. It should be noted that from Google Assistant and Alexa everything works well.
Any solves?

**Comment by aswetlow** [comment]
Oh, I think, I see the problem now.

If you test your app in Dialog and not in the Google Action Simulator, you have to import and use `jovo-platform-dialogflow`

```
const { Dialogflow } = require('jovo-platform-dialogflow');
app.use(new Dialogflow());
```

**Comment by AshiqN** [comment]
I have an issue while using actions builder simulator for testing, both Alexa and dialog flow is working fine. 
Error is throwing while using actions builder simulator.

Please help

  Error -----------------------------------------------------------------

  Code:
  ERR_NO_MATCHING_PLATFORM

  Message:
  Can't handle request object.

  Stack:
  Error: Can't handle request object.
      at App.handle (C:\Users\ashiq\go\src\leapvoiceserv\node_modules\jovo-core\src\core\BaseApp.ts:229:15)
      at App.handle (C:\Users\ashiq\go\src\leapvoiceserv\node_modules\jovo-framework\src\App.ts:333:5)
      at C:\Users\ashiq\go\src\leapvoiceserv\src\index.ts:19:9

  Module:
  jovo-core

  Hint:
  Please add an integration that handles that type of request.

   ----------------------------------------------------------------------


   ----------------------------------------------------------------------

  WARN: Jovo instance is not available. ON_ERROR doesn't work here
