### ISSUE TITLE
Jovo Debugger does not trigger AUDIOPLAYER.AlexaSkill.PlaybackFinished intent.

### ISSUE THREAD

**Issue by curiousdustin** [jovotech/jovo-framework#495]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Jovo Debugger should trigger AUDIOPLAYER.AlexaSkill.PlaybackFinished just like an Alexa device does.

## Current Behavior
Jovo debugger triggers AUDIOPLAYER.AlexaSkill.Finished instead.

## Your Environment
```
Jovo CLI Version: 2.2.5
Jovo packages of current project:
  jovo-cms-i18next: 2.2.4
  jovo-core: 2.2.3
  jovo-db-filedb: 2.2.3
  jovo-framework: 2.2.5
  jovo-platform-alexa: 2.2.6
  jovo-platform-dialogflow: 2.2.4
  jovo-platform-googleassistant: 2.2.5
  jovo-plugin-debugger: 2.2.3
```

**Comment by jankoenig** [comment]
Thank you for fixing this @curiousdustin 🙌

**Comment by kubycsolutions** [comment]
I seem to be seeing the same kind of malfunction again. Did we lose a patch, or did something else change?
