### ISSUE TITLE
this.$user.delete() does not delete user information

### ISSUE THREAD

**Issue by VoiceFirstTech** [jovotech/jovo-framework#499]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

await this.$user.delete() should delete user information

## Current Behavior

that.$user.delete() does nothing. Our app does not respond.

![Screenshot from 2019-05-11 14-20-00](https://user-images.githubusercontent.com/40079313/57573576-f1a8d200-73f7-11e9-9560-d96f95bda31d.png)

![Screenshot from 2019-05-11 14-20-15](https://user-images.githubusercontent.com/40079313/57573577-f4a3c280-73f7-11e9-9046-3af8ccf9e59a.png)

## Your Environment

* Jovo Framework version used: 2.2.3
* Operating System: Ubuntu Linux
![image](https://user-images.githubusercontent.com/40079313/57573594-2583f780-73f8-11e9-8861-fa2ed2fa0989.png)

**Comment by VoiceFirstTech** [comment]
Note that while our app responds "Success" our customer data is still saved on next session.

**Comment by aswetlow** [comment]
When does it happen?

Locally with FileDb or on Lambda with DynamoDb?
