### ISSUE TITLE
Jovo get and build issue

### ISSUE THREAD

**Issue by zaijacobs** [jovotech/jovo-framework#500]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
`jovo build -p googleAction --reverse  --overwrite` should add the values that belong to the entities in the model file.

## Current Behavior
I remove the model and everything in the platforms folder. Then I run `jovo get googleAction --overwrite` and then `jovo build -p googleAction --reverse  --overwrite`.

When I check the newly create model file, at inputTypes I can see the Entities but none have values: `	"inputTypes": [
		{
			"name": "category"
		},
		{
			"name": "configurable"
		},
		{
			"name": "manufacturer",
			"dialogflow": {
				"isEnum": true
			}
		}
	]` 

But then in the platforms folder I do see the entities and their values. Also in Dialoglfow they are present. Perhaps I am doing something wrong?

## Your Environment

* Jovo Framework version used: 2.2.5
* Operating System: Windows 7

**Comment by aswetlow** [comment]
Hey @zaijacobs!
We just published the fix. Please update the jovo-cli package.
`npm update jovo-cli -g`

**Comment by zaijacobs** [comment]
@aswetlow I can see the values now after updating the jovo-cli package. Thank you.
