### ISSUE TITLE
Add hasAutomotive property to AlexaRequest

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#505]
## I'm submitting a...
- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Add a boolean property to AlexaRequest for hasAutomotive
https://developer.amazon.com/docs/custom-skills/automotive-property-for-alexa-skills.html#how-the-automotive-property-works

## Current Behavior
No Automotive flag

### Error log
None

## Your Environment
* Jovo Framework version used: 2.2.6
* Operating System: Windows 10 Pro

**Comment by aswetlow** [comment]
Added by @natrixx in [PR 506](https://github.com/jovotech/jovo-framework/pull/506). Will publish to NPM later today.
