### ISSUE TITLE
Could not find the route "ON_HEALTH_CHECK" in your handler function.

### ISSUE THREAD

**Issue by ihr-it-projekt** [jovotech/jovo-framework#517]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I got a route not found exception when google make a health request.

i try to add " 'ON_HEALTH_CHECK': "HealthCheckIntent"," in config.js and an Intenent in my app.js. But it does not work.

### Error log
```

Stack:

05:04:18
Error: Could not find the route "ON_HEALTH_CHECK" in your handler function.
Error: Could not find the route "ON_HEALTH_CHECK" in your handler function.

05:04:18
at Function.applyHandle (/var/task/node_modules/jovo-framework/dist/src/middleware/Handler.js:170:19)
at Function.applyHandle (/var/task/node_modules/jovo-framework/dist/src/middleware/Handler.js:170:19)
```

## Your Environment
Lamda function and local.

**Comment by aswetlow** [comment]
Hey @ihr-it-projekt, 
just published the fix on NPM.

The ON_HEALTH_CHECK handler is optional now. You don't have to implement it. You can add it to your handler if you want to react on health check requests.

```javascript
app.setHandler({
    ON_HEALTH_CHECK() {
         // do stuff here
     }
});
```

**Comment by ihr-it-projekt** [comment]
I update with npm update, but still same error. I use your example request found in "node_modules/jovo-platform-dialogflow/sample-request-json/v2/google/HealthCheck.json" 

my package.json looks like:

``
"dependencies": {
    "alexa-verifier-middleware": "^1.0.2",
   ...
    "jovo-framework": "^2.2.8",
    "jovo-platform-alexa": "^2.2.10",
    "jovo-platform-googleassistant": "^2.2.8",
    "jovo-plugin-debugger": "^2.2.7",
   ....
  },

`
Log:
`  Error -----------------------------------------------------------------
  
  Code:
  ERR_NO_ROUTE
  
  Message:
  Could not find the route "ON_HEALTH_CHECK" in your handler function.
  
  Stack:
  Error: Could not find the route "ON_HEALTH_CHECK" in your handler function.
      at Function.applyHandle (C:\Users\Ralf\Desktop\Workspace\have-i-am\node_modules\jovo-framework\dist\src\middleware\Handler.js:171:23)
      at handle (C:\Users\Ralf\Desktop\Workspace\have-i-am\node_modules\jovo-framework\dist\src\middleware\Handler.js:38:23)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  
  Module:
  jovo-framework
  
   ----------------------------------------------------------------------
  
  
  Request details:
  this.$googleAction initialized
  this.$type: {"type":"ON_HEALTH_CHECK","optional":false}
  this.$session.$data : {}
  this.$nlu : {}
  this.$inputs : {}
  
  
   ----------------------------------------------------------------------
  
`

**Comment by ihr-it-projekt** [comment]
Update, i try also jovo update

**Comment by gwythyr** [comment]
i also found the same error in my backend logs, i'm using last versions of jovo libs

**Comment by aswetlow** [comment]
Just published the fix. Could you update and try again?

**Comment by jankoenig** [comment]
Closing this. Feel free to reopen if the issue persists
