### ISSUE TITLE
`$alexaSkill.addDirective` broke google assistant conversation

### ISSUE THREAD

**Issue by gustavopaes** [jovotech/jovo-framework#520]
## I'm submitting a...

- [x] Bug report

## Expected Behavior

I can call `this.$alexaSkill.addDirective` method without check if the conversation come from Alexa or Google Assistant or any other one. The framework need abstract this from me

## Current Behavior

Call `this.$alexaSkill.addDirective` method can't broke Google Assistant webhook calls.

But when I create a Google Assistant conversation, I am getting this message error:

```
Message:
  Cannot read property 'addDirective' of undefined
```

```
app.setHandler({
    async LAUNCH() {
        this.$alexaSkill.addDirective({
            type: 'Alexa.Presentation.APL.RenderDocument',
            version: '1.0',
            document,
            datasources,
        });

        this.ask(speeches.LaunchRequest, speeches.LaunchRequest);
    },
})
```

## Your Environment
* NodeJS: 11.10.0
* Jovo Framework version used: 2.2.8
* Operating System: linux ubuntu 18.04

**Comment by aswetlow** [comment]
Hey @gustavopaes!

Platform-specific calls should be checked. Try this:

```javascript

app.setHandler({
    async LAUNCH() {
        if (this.isAlexaSkill()) {
         this.$alexaSkill.addDirective({
            type: 'Alexa.Presentation.APL.RenderDocument',
            version: '1.0',
            document,
            datasources,
        });
        }
        this.ask(speeches.LaunchRequest, speeches.LaunchRequest);
    },
})
```
