### ISSUE TITLE
Disabling PlugIns in Multi-Stage Environment Leads to error: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#521]
## I'm submitting a...

- [ X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When running multiple stages, would like to be able to use FileDb in `local` stage and DynamoDb in other stages. Use of `enabled` flag in config should control active plugins after a merge has been done of the stage specific config and the main config.

## Current Behavior

In `local` stage, getting error:  Cannot read property 'size' of undefined

**app.js**
```js
const { Jovo } = require('jovo-core');
const { App } = require('jovo-framework');
const { Alexa } = require('jovo-platform-alexa');
const { GoogleAssistant } = require('jovo-platform-googleassistant');

// Plugins
const { JovoDebugger } = require('jovo-plugin-debugger');
const { FileDb } = require('jovo-db-filedb');
const { DynamoDb } = require('jovo-db-dynamodb');
const app = new App();

app.use(
  new Alexa(),
  new GoogleAssistant(),
  new JovoDebugger(),
  new FileDb(),
  new DynamoDb()
);
```

**config.js**
```js
module.exports = {
  db: {
    FileDb: {
      enabled: false,
    },
    DynamoDb: {
      enabled: false,
      tableName: `${process.env.DYNAMODB_USERS_TABLE}`,
    },
  },

  user: {
    context: {
      enabled: true,
    },
  },
};
```

**config.local.js**
```js
require('dotenv').config();

module.exports = {
  db: {
    FileDb: {
      enabled: true,
      pathToFile: '../db/db.json',
    },
  },
};
```

**config.prod.js**
```js
module.exports = {
  db: {
    DynamoDb: {
      enabled: true,
    },
  },
};
```

### Error log
```
  Message:
  Cannot read property 'size' of undefined

  Stack:
  TypeError: Cannot read property 'size' of undefined
      at JovoUser.updateContextData (C:\dev\voice\myorg\myapp\node_modules\jovo-framework\src\middleware\user\JovoUser.ts:594:40)
      at JovoUser.saveDb (C:\dev\voice\myorg\myapp\node_modules\jovo-framework\src\middleware\user\JovoUser.ts:400:18)
      at Middleware.run (C:\dev\voice\myorg\myapp\node_modules\jovo-core\src\Middleware.ts:85:30)
```

## Your Environment

* Jovo Framework version used: 
Jovo CLI Version: 2.2.6

Jovo packages of current project:
  jovo-analytics-dashbot: 2.2.6
  jovo-cms-i18next: 2.2.7
  jovo-core: 2.2.6
  jovo-db-dynamodb: 2.2.6
  jovo-db-filedb: 2.2.6
  jovo-framework: 2.2.8
  jovo-platform-alexa: 2.2.10
  jovo-platform-dialogflow: 2.2.7
  jovo-platform-googleassistant: 2.2.8
  jovo-plugin-debugger: 2.2.7

NOTE: Just recently updated jovo-framework from v2.2.6

* Operating System: Windows 10 Pro

**Comment by rmtuckerphx** [comment]
Rolled back all my jovo modules.

Jovo packages of current project:
  jovo-analytics-dashbot: 2.2.4
  jovo-cms-i18next: 2.2.5
  jovo-core: 2.2.4
  jovo-db-dynamodb: 2.2.4
  jovo-db-filedb: 2.2.4
  jovo-framework: 2.2.6
  jovo-platform-alexa: 2.2.8
  jovo-platform-dialogflow: 2.2.5
  jovo-platform-googleassistant: 2.2.6
  jovo-plugin-debugger: 2.2.5


When running in `local` stage, I don't see anything but an empty array [] in `db.json`

**Comment by aswetlow** [comment]
Hey @rmtuckerphx!

we just published the fix.
