### ISSUE TITLE
Credential Error with GoogleAction deployment to Lambda

### ISSUE THREAD

**Issue by silas546** [jovotech/jovo-framework#527]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Hi, I'm getting a 'Missing credentials in config' error when trying to deploy my Google Action to AWS lambda. I don't have any issues deploying my Alexa Skill. Heres my project.js:

// ------------------------------------------------------------------
// JOVO PROJECT CONFIGURATION
// ------------------------------------------------------------------

module.exports = {
  alexaSkill: {
    nlu: 'alexa',
    manifest: {
      permissions: [
        {
          name: 'alexa::devices:all:geolocation:read'
        }
      ]
    }
  },
  googleAction: {
    nlu: 'dialogflow',
  },
  defaultStage: 'dev',
  stages: {
 
    dev: {
      alexaSkill: {
        endpoint: '<my endpoint>',
        askProfile: 'jovo-silas',
        skillId: '<my skillId>'
      },
      googleAction: {
        nlu: 'dialogflow',
        dialogflow: {
          endpoint: '<api gateway POST endpoint>',
          projectId: '<projectId>',
          keyFile: '<myKeyfile stored in project root>'
        }
      }
    }
  }
};

Let me know if you need more information from this file. I dropped the local stage and have to replace a lot of the values as I'm working on this for a client. Is using an API gateway as an endpoint within my googleAction configuration causing this issue? I saw the other thread where using environmental variables within the ask-cli profile setup is causing issues but I'm not doing that and my Alexa skill has no issues deploying to Lambda anyway.

### Error log
```
jovo deploy -p googleAction --ask-profile jovo-silas  --stage dev 
 
    ✔ Bundle Project(stage: dev)
      ✔ Copy source code to "./bundle"
      ✔ Run "npm install --production"
      ✔ Zip "./bundle" folder
       -> Zip path: /Users/ochsner-mbpro15/OchsnerVoice/bundle.zip
    ❯ Deploying Google Action (stage: dev) ochsnerhealth-ghfiuf
      ✔ Creating file /googleAction/dialogflow_agent.zip
       -> Language model: en-US
       -> Fulfillment Endpoint:
          https://t6dyimpxrj.execute-api.us-east-1.amazonaws.com/test/OchsnerHealth
      ✔ Uploading and restoring agent for project ochsnerhealth-ghfiuf
      ✔ Training started
      ✖ Uploading to lambda
       -> Missing credentials in config
```

## Your Environment

* Jovo Framework version used: 2.2.6
* Operating System: Mac OS

**Comment by aswetlow** [comment]
Hey @silas546!
Sorry for the late response. We fixed that. Please update the CLI.

In your config add this to your `dev`-stage

```
host: {
      lambda: {
         arn: '<LAMBDA-ARN>',  
      }
   },

```

**Comment by silas546** [comment]
Hey Guys,

Thanks for the response. I'm still currently getting the same error after updating jovo cli (node update -g jovo-cli) and making the changes to project.js. Is this stage setup correctly?

`    dev: {
      host: {
        lambda: {
          arn: '<lambda ARN>'
        }
      },
      alexaSkill: {
        endpoint: '<lambda ARN>',
        askProfile: 'jovo-silas',
        skillId: 'amzn1.ask.skill.e02bfc8b-361d-4ede-b158-3847b6886a43'
      },
      googleAction: {
        nlu: 'dialogflow',
        dialogflow: {
          endpoint: '<API Gateway endpoint>',
          projectId: 'ochsnerhealth-ghfiuf',
          keyFile: 'ochsnerhealth-ghfiuf-9b4b85808c04.json'
        }
      }
    }`

**Comment by aswetlow** [comment]
Can you add `--target lambda` to the command line?

` jovo deploy -p googleAction --ask-profile jovo-silas --target lambda --stage dev`

**Comment by silas546** [comment]
Looks like that did it. Seems to work now as long as --target is flagged. Thanks @aswetlow, closing out the ticket
