### ISSUE TITLE
How to use Docker with Jovo Integrations

### ISSUE THREAD

**Issue by dutterbutter** [jovotech/jovo-framework#532]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [x] Other... Please describe:
A suggested approach to using Docker with Jovo framework integrations
## Current Behavior

Docker builds and starts the server **successfully** but I no longer receive replies through Messenger

I am assuming I have to re-configure my webhooks but not really sure? Any suggested approach would be appreciated. 

## Your Environment

> Dockerfile
```
FROM node:10-alpine

# Set the working directory within the container
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app/src

COPY package*.json /usr/src/app/

RUN npm install -g jovo-cli && npm install

COPY . /usr/src/app

EXPOSE 3000

CMD [ "node", "index.js", "--webhook" ]
```
`docker run --env-file .env -p 3000:3000 <image-name>`

* Jovo Framework version used: 1.x.x
```
Jovo CLI Version: 2.2.7

Jovo packages of current project:
  jovo-analytics-chatbase: 2.2.8
  jovo-cms-googlesheets: 2.2.10
  jovo-cms-i18next: 2.2.9
  jovo-core: 2.2.8
  jovo-db-filedb: 2.2.8
  jovo-framework: 2.2.11
  jovo-platform-dialogflow: 2.2.9
  jovo-plugin-debugger: 2.2.9
```
* Operating System:

**Comment by aswetlow** [comment]
Hey @dutterbutter

Did it work before? How do you access your endpoint?

**Comment by dominik-meissner** [comment]
Hi @dutterbutter, my working Docker file looks like this:

```
FROM node:8-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# If you are building your code for production
RUN npm install --only=production

# Bundle app source
COPY . .

# Open Port to outside world
EXPOSE 3000

# Set Environment Vars
ENV JOVO_CWD=/usr/src/app/src

# Run the application
CMD [ "node", "src/index.js", "--webhook" ]
```

**Comment by jankoenig** [comment]
Thanks @dominik-meissner 👍 We should definitely add this to our Docs soon

**Comment by dutterbutter** [comment]
Thanks @dominik-meissner
