### ISSUE TITLE
Dialogflow Agent isNewSession Not Implemented

### ISSUE THREAD

**Issue by BronxBombers** [jovotech/jovo-framework#536]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Calling isNewSession on the DialogflowAgent should return True if a new session, or False otherwise. There is nothing in the dialogflow request that explicitly states its a new session, however it could probably be implicitly determined when there are no output contexts, or something else? Something more complicated than just reading a new session field from the request needs to be implemented.

## Current Behavior
The isNewSession implementation in DialogflowAgent.ts line 52, currently is hard coded to return True every time.

**Comment by jankoenig** [comment]
Thank you for bringing this up @BronxBombers! We need to investigate further, but this is definitely something that should get fixed soon
