### ISSUE TITLE
Unsure how to run Jovo app self-hosted

### ISSUE THREAD

**Issue by orinokai** [jovotech/jovo-framework#543]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:

## Expected Behavior
Hello, I'm trying to run my Jovo app in a docker container on a self-hosted server and use the server URL as the fulfilment endpoint for Google/Alexa.

## Current Behavior
I can get the app started with the `node index.js --webhook` command and I have exposed port 3000, but I cannot get the app to run in either of the test consoles. If I do `curl https://127.0.0.1:3000` then I get a 'curl (35) ... unknown protocol' error. I assume I need to enable SSL on my Jovo app, but I'm not sure how. Any advice greatly appreciated, thanks.

## Your Environment
* Jovo Framework version used: 1.4.10
* Operating System: Debian 9.7 x64

**Comment by jankoenig** [comment]
Maybe this thread is helpful: https://github.com/jovotech/jovo-framework/issues/532

**Comment by aswetlow** [comment]
Hey @orinokai

The local endpoint listens to POST requests.

Here's a working curl example (Alexa LaunchRequest payload):
```bash
curl -d '{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.0000000-0000-0000-0000-00000000000",
    "application": {
      "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.account.AM3B00000000000000000000000"
    }
  },
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
      },
      "user": {
        "userId": "amzn1.account.AM3B00000000000000000000000"
      },
      "device": {
        "deviceId": "amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA",
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      }
    },
    "AudioPlayer": {
      "offsetInMilliseconds": 0,
      "playerActivity": "IDLE"
    }
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "amzn1.echo-api.request.0000000-0000-0000-0000-00000000000",
    "timestamp": "2015-05-13T12:34:56Z",
    "locale": "en-US"
  }
}' -H "Content-Type: application/json" -X POST http://localhost:3000/webhook
```

**Comment by orinokai** [comment]
Thanks so much to you both, that's a great help. I've been able to test the endpoint locally and get it to respond to a POST request. However, as expected, if I try to access the endpoint with `https://` then it fails with a curl 35 error because Node is not configured with SSL certificates. So my question is: if I setup my Jovo app using the [ExpressJS integration](https://www.jovo.tech/docs/hosting/express-js), can I add my certificates and enable SSL? Thanks.

**Comment by aswetlow** [comment]
Good point! It wasn't implemented properly. Just published an update

Add this to your index.js in your project:
```
const fs = require('fs');

// Add this
Webhook.ssl = {
   key: fs.readFileSync('/path/to/cert.key'),
   cert: fs.readFileSync('/path/to/cert.pem'),
};
```

**Comment by orinokai** [comment]
That is fantastic, it works perfectly now. Thanks for the quick update @aswetlow
