### ISSUE TITLE
sendToApp unit test feature issue with google assistant tests

### ISSUE THREAD

**Issue by natrixx** [jovotech/jovo-framework#544]
## I'm submitting a...

- [X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
This issue stems from details found here: https://community.jovo.tech/t/unit-testing-your-plugins/393/4 . I have seen it for awhile, but just now have some time to get it reported. 

Using the new sendToApp unit testing feature, it seems that session data from the last response in a conversation is being saved to the previous responses. 

This happens only for google assistant, and only when using "runtime: app". 

I have a branch with a modified test that can be used to demonstrate the issue:

https://github.com/natrixx/jovo-framework/tree/exampleGoogleSendToAppIssue

1. cd to `examples/javascript/unit-testing`
2. run `npm install`
3. run `jovo run`
4. open another terminal and cd to `examples/javascript/unit-testing`
5. run `npm test -- -f test/sample_sendToApp.test.js`

Note the three failing google tests that should pass. 

## Your Environment

* Operating System: Ubuntu

Jovo CLI Version: 2.2.8

Jovo packages of current project:
  jovo-cli: 2.2.8
  jovo-cli-core: 2.2.5
  jovo-cli-deploy-lambda: 2.2.6
  jovo-cli-platform-alexa: 2.2.7
  jovo-cli-platform-google: 2.2.7
  jovo-cms-googlesheets: 2.2.12
  jovo-cms-i18next: 2.2.11
  jovo-config: 0.1.0
  jovo-core: 2.2.10
  jovo-db-dynamodb: 2.2.10
  jovo-db-filedb: 2.2.10
  jovo-framework: 2.2.13
  jovo-model: 0.1.7
  jovo-model-alexa: 0.1.7
  jovo-model-dialogflow: 0.1.7
  jovo-platform-alexa: 2.2.15
  jovo-platform-dialogflow: 2.2.11
  jovo-platform-googleassistant: 2.2.13
  jovo-plugin-debugger: 2.2.11
  jovo-plugin-error-slack: 2.1.1
  jovo-webhook-connector: 2.2.1

**Comment by aswetlow** [comment]
Hey Nate,

I tried to reproduce it 

```bash
git clone https://github.com/natrixx/jovo-framework.git --branch exampleGoogleSendToAppIssue
```

1. cd to examples/javascript/unit-testing
2. run npm install
3. run jovo run
4. open another terminal and cd to examples/javascript/unit-testing
5. run npm test -- -f test/sample_sendToApp.test.js

My tests pass:
![image](https://user-images.githubusercontent.com/14978292/61473313-7549e680-a986-11e9-9b60-be0fd5676e26.png)

Btw. When you use `runtime: app`, you don't need to run the app in the background. You can skip 3) and 4)

Do I misunderstand something? :)

**Comment by natrixx** [comment]
OMG @aswetlow ! Talk about a rookie mistake! I forgot to actually push my commits yesterday! Sorry! :rofl: 

Steps 3 and 4 I added because I also have tests for not using `runtime:app` that pass.

**Comment by aswetlow** [comment]
Got it! Puh, that was a tricky one. The session data was set as a reference, not as a copy. It was mutated in the second request/response.

Thanks for the finding. Will publish it later today.

**Comment by natrixx** [comment]
ooh great! thanks @aswetlow !

**Comment by aswetlow** [comment]
Done! #nodeployfridays 😂

**Comment by natrixx** [comment]
lol thanks! updated and verified it works here also! Have a great weekend!
