### ISSUE TITLE
Running tests with runtime: 'app' and google-sheets-cms fails

### ISSUE THREAD

**Issue by natrixx** [jovotech/jovo-framework#546]
## I'm submitting a...

- [ X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
```
const conversation = testSuite.conversation({
                    runtime: "app"
                });
```
using the above code on a test for a project that is using the google-sheets-cms integration will not work and you get the error seen below.

### Error log
```
Error -----------------------------------------------------------------
  
  Code:
  ERR_PLUGIN
  
  Message:
  fetch is not a function
  
  Stack:
  Error: fetch is not a function
      at GoogleSheetsCMS.retrieveSpreadsheetData (/home/nate/github/jovo-framework/examples/javascript/google-sheets-cms/node_modules/jovo-cms-googlesheets/src/GoogleSheetsCMS.ts:137:19)
      at <anonymous>
  
  Module:
  jovo-cms-googlesheets
  
  Hint:
  This might be an issue with upgrading the Jovo packages. Try to run `jovo update` instead of `npm install`
  
  Learn more:
  https://www.jovo.tech/docs/installation/upgrading
  
   ----------------------------------------------------------------------
  
  
   ----------------------------------------------------------------------
  
  WARN: Jovo instance is not available. ON_ERROR doesn't work here
  TestHost.fail: 
```

## Your Environment
* Jovo CLI Version: 2.2.8

Jovo packages of current project:
  jovo-cms-googlesheets: 2.2.13
  jovo-cms-i18next: 2.2.12
  jovo-core: 2.2.11
  jovo-db-dynamodb: 2.2.11
  jovo-db-filedb: 2.2.11
  jovo-framework: 2.2.14
  jovo-platform-alexa: 2.2.16
  jovo-platform-dialogflow: 2.2.12
  jovo-platform-googleassistant: 2.2.14
  jovo-plugin-debugger: 2.2.12

* Operating System: ubuntu

**Comment by aswetlow** [comment]
Hey Nate!

Can't reproduce it. Can you provide more info? 

We're still facing the `X is not a function` problem after updates. Could you try to delete `/node_modules` and `package-lock.json`?

**Comment by natrixx** [comment]
Sure thing @aswetlow! I did the delete node_modules bit a couple times and still get the issue. However, I did find that the issue with the error about fetching only happens on private google sheets. Seems to work just fine on public ones. 

Here is some more info:
I have a branch with a modified test that can be used to demonstrate the issue:

https://github.com/natrixx/jovo-framework/tree/exampleFetchIssueCmsSendToApp

1. cd to examples/javascript/unit-testing
2. copy google sheets key (provided privately via slack) to /src/creds/google-sheets.json
3. run npm install
4. run jovo run
5. open another terminal and cd to examples/javascript/unit-testing
6. run npm test -- -f test/sample_sendToApp.test.js

The tests using `runtime: 'app'` should fail, and the others should pass. 

In `config.js` I have left a commented out version of the public sheet you can swap out. Once jovo is restarted with that swap, all tests should pass.

**Comment by aswetlow** [comment]
Puh...took a while... 

The error was thrown by the gaxios package after initializing `fetch` this line:
`const fetch = isbrowser_1.isBrowser() ? window.fetch : node_fetch_1.default;`

`isBrowser()` is true, because of the jest `testEnvironment` configuration. The default value is `jsdom`, but it has to be `node`. (thx to @Veake)

Add this to your `package.json`

```json
"jest": {
    "testEnvironment": "node"
  }
```

I will fix it in the example files in the main repo.
