### ISSUE TITLE
Getting the address card doesnt't work

### ISSUE THREAD

**Issue by sebastianbrunnert** [jovotech/jovo-framework#552]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Code

I exactly putted the code from the docs to my app.js

`// Example
async NeutralSearchIntent() {
    try {
        const countryAndPostalCode = await this.$alexaSkill.$user.getCountryAndPostalCode();

        this.tell(`${countryAndPostalCode.postalCode} in ${countryAndPostalCode.countryCode}`);

    } catch(error) {
        if (error.code === 'NO_USER_PERMISSION') {
            this.$alexaSkill.showAskForCountryAndPostalCodeCard()
                .tell(`Please grant access to your address in the Alexa app.`);
        } else {
            // Do something
        }
    }
},`

### Error log

First i get the message that i have exspected (the ssml is that, what i have inserted and the card is right too). But this is never showen in alexa...in alexa a Invalid response is showen...

`{
	"version": "1.0",
	"response": {
		"shouldEndSession": true,
		"outputSpeech": {
			"type": "SSML",
			"ssml": "<speak>Bitte erlaube dem Flensfinder-Skill auf deinen Standort zugreifen zu können. Wenn du das nicht möchtest, kannst du auch nach Flens in einer bestimmten Stadt fragen.</speak>"
		},
		"card": {
			"type": "AskForPermissionsConsent",
			"permissions": [
				"read::alexa:device:all:address"
			]
		}
	},
	"sessionAttributes": {}
}
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.f2b1e24e-d474-4a9a-9291-a7a6d84c7a10",
		"application": {
			"applicationId": "amzn1.ask.skill.5eb2b731-9d5f-4a30-b614-3cf1cfcc2ea1"
		},
		"user": {
			"userId": "amzn1.ask.account.AFCUZZGQUDMPBZIZS5ZFIJK6YTH5RQHG2ZYMYN455UAZX25O3W77TNXG7U2A5ESXPMGNKX72FTXVGZWZ4EROYUEIPIWPRCJYSQYEKOZOPXTVEWC5J64NF54G4QLFFRS7NQR3K2ZCPEG36EXVHDN5IGAYLJSN2RFLF6S6DEV5GEETIPH5XP3MG5TUU7PHBYFBBIICBWCNITU3N2Q"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.5eb2b731-9d5f-4a30-b614-3cf1cfcc2ea1"
			},
			"user": {
				"userId": "amzn1.ask.account.AFCUZZGQUDMPBZIZS5ZFIJK6YTH5RQHG2ZYMYN455UAZX25O3W77TNXG7U2A5ESXPMGNKX72FTXVGZWZ4EROYUEIPIWPRCJYSQYEKOZOPXTVEWC5J64NF54G4QLFFRS7NQR3K2ZCPEG36EXVHDN5IGAYLJSN2RFLF6S6DEV5GEETIPH5XP3MG5TUU7PHBYFBBIICBWCNITU3N2Q"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AHFRFPGKWT5GTKTHLAAV2IEEI3ICCVPIXNJIHOXWLIH6JZTLKV6TRYDZFUCCMUR3DNA7H4QRJRV7WWG37AQ6DI2Q73RTX2O3SUGQUH5KB75B6L2MFRUAYQBYU3DXHWR7A7IIGVYTSDWDWRPIYR3FA7BSCVMT25BUYLRUCHMNO5S2HXNSXK2SG",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjVlYjJiNzMxLTlkNWYtNGEzMC1iNjE0LTNjZjFjZmNjMmVhMSIsImV4cCI6MTU2NDY2MzI5MywiaWF0IjoxNTY0NjYyOTkzLCJuYmYiOjE1NjQ2NjI5OTMsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFBVk1NeU5jRWJ4ZXM3YTNSNXdCT0VTS2dFQUFBQUFBQURBcGo1bUtHVmRIMnNicmJocGppYk1kR0hvSUhzRkFBUC9LelpHZy9TZDZNWCtscDZqbnpqYVJiRWNZK0tlUjNjTVdjZklRTi8zd1BTWXJkOWlPUXJNZW95Wk1Gb2Exak9QTHd6N2JDcGVvTEVlaHkyZGszM0x4bEVnVndaQzZKNnJsOG8zL0hjLzYyVkN3RTMvbWwvQ3Foa1dxb0dlU2FTelBJRjBqY0x6REtxN1dCZ01IYkI4eUhob2NDNGJad1QzWmVMZVZMUHJYRERBMTZRTTZRYXF2bXRob1FZSG5mRjZHSVRvNzFxZ3BWQWZmZ3R6THdFdXZKQW14UUZUbGJ1U2U2cDNsR0Q5Lzk2VFRzcVVoVHNmU2lRMTRDdFVKKyttUVZ2bFhiRmt1RGIrSkNEVXo4K2Z1K0hGdk1kZmszaGFjdHBIcDAzYnlBYUdocWovdWEvbXZlNzNwVno2VG1vL2xpRzRXNElic0VVajZIL2RhR1lBZFgyNW5SdGVCeGN5b2I5a1djdkVFaUszIiwiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUhGUkZQR0tXVDVHVEtUSExBQVYySUVFSTNJQ0NWUElYTkpJSE9YV0xJSDZKWlRMS1Y2VFJZRFpGVUNDTVVSM0ROQTdINFFSSlJWN1dXRzM3QVE2REkyUTczUlRYMk8zU1VHUVVINUtCNzVCNkwyTUZSVUFZUUJZVTNEWEhXUjdBN0lJR1ZZVFNEV0RXUlBJWVIzRkE3QlNDVk1UMjVCVVlMUlVDSE1OTzVTMkhYTlNYSzJTRyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFGQ1VaWkdRVURNUEJaSVpTNVpGSUpLNllUSDVSUUhHMlpZTVlONDU1VUFaWDI1TzNXNzdUTlhHN1UyQTVFU1hQTUdOS1g3MkZUWFZHWldaNEVST1lVRUlQSVdQUkNKWVNRWUVLT1pPUFhUVkVXQzVKNjRORjU0RzRRTEZGUlM3TlFSM0syWkNQRUczNkVYVkhETjVJR0FZTEpTTjJSRkxGNlM2REVWNUdFRVRJUEg1WFAzTUc1VFVVN1BIQllGQkJJSUNCV0NOSVRVM04yUSJ9fQ.UkBcZocC8lzJS8DduJixrgcYdwmdzx08E8Iwfp8KbLqJM32_h7pCjB9JdnKYOvUIPqeNZk5ADfmSPIlURx53CVln3dunNx4wZE6RKFwNmHuex7I9_ovwS9FXcyLXhGuFUp2KKjOfKJLPY-Wh3jfTW6Ge_rOsQwv8aR4f6ciSQp6DVfsW1HjRGhORbEYhym-Tx_zNU-YlVok3GJDlAgK_DGciAo3b-GSPZgmGAlESSiOGGJWZeQOiQMW7hf3iLQ-hOQ0zC93DXKQVZTsAf02QpHILCsYjnLN5SB6UFraehOdZs2NlBb9jiDTiAMUy8ZjV_8IQYVIkaJZvl1yYgsumPQ"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		}
	},
	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.4b1ba6c0-2fea-4783-94c8-a05fbd479b1a",
		"timestamp": "2019-08-01T12:36:35Z",
		"locale": "de-DE",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "In order to be requested, read::alexa:device:all:address must be declared as permission used by the skill. for requestId amzn1.echo-api.request.63b096b5-27e4-41e7-a6ae-88289f0f7dc1"
		}
	}
}
{
	"version": "1.0",
	"response": {
		"shouldEndSession": true
	},
	"sessionAttributes": {}
}`

## Your Environment

* Jovo Framework version used: latest
* Operating System: Ubuntu 18
* NodeJS version: latest

**Comment by aswetlow** [comment]
The permission must be activated in the ASK Console.
![image](https://user-images.githubusercontent.com/14978292/62524728-6abc9780-b836-11e9-9999-2a21c251e7af.png)

**Comment by sebastianbrunnert** [comment]
Thank you!

**Comment by sebastianbrunnert** [comment]
I dont get an error but i get this output: "undefined in undefined"

**Comment by aswetlow** [comment]
I can reproduce it with an Amazon account (user of the skill) with no data about country and postal code.

Are you testing with an Account where you can edit the address?

**Comment by sebastianbrunnert** [comment]
Thats the issue ._.
i always tested it in the simulator.
Thank you.
