### ISSUE TITLE
Visual Output Cards - Links

### ISSUE THREAD

**Issue by silas546** [jovotech/jovo-framework#557]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Hi All,

Is there a way to post href links via Jovo's default visual output cards? Some of the intent's on my app deliver snippets of content from our blog site, and I'd like to be able to output a link from the post to the user's companion app so they can read more.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by jankoenig** [comment]
Unfortunately, the platforms (Alexa and Google Assistant) don't support links in their cards

**Comment by silas546** [comment]
I figured that was the case from using these in Lex :(

Thanks
