### ISSUE TITLE
Invalid agent.json on deploy

### ISSUE THREAD

**Issue by santhosh77h** [jovotech/jovo-framework#559]
## I'm submitting a...

- [X] Bug report
- [ ] Documentation issue or request
- [ ] Feature request
- [ ] Other... Please describe:

## Expected Behavior

`jovo build -p googleAction --deploy` would create .zip file under googleActions but the problem is `agent.json` which is available in side the .zip where `supportedLanguages` key should have a value `ja` for `ja-JP` 

Sadly we get this error on multi language support actions

I have tested this on ja-JP and en-US

## Current Behavior

But currently we can see that it would create it as ja-JP because of this Dialog Flow would throw an error that ja-JP is not a supported language.

### Inside Dialog Flow we would get error as 
```
Platform does not support ja-JP.
```

## Your Environment

* Jovo CLI Version: 2.2.8
* Jovo-framework: 2.2.14
* Jovo-platform-dialogflow: 2.2.12
* Operating System: Ubuntu 16.04

**Comment by aswetlow** [comment]
Hey @santhosh77h!

I was able to reproduce it. You can change your model filename `ja-JP.json` to `ja.json`. 

But you have to change the `nlu` property if you want to use it with Alexa.

```javascript
 alexaSkill: {
       nlu: {
          name: 'alexa',
          lang: {
             ja: [
                'ja-JP',
              ] 
         }
       }
    },
```
This will map languages to locales. I mostly use it with `en.json` to map it to en-US, en-CA, en-GB etc

**Comment by santhosh77h** [comment]
@aswetlow thanks for the quick response but deployment was not working 
got this error

> ✖ Updating Alexa Skill project for ASK profile profile-dev
         -> askApiUpdateSkill:Skill manifest is not valid.
  Object instance at
            property path "$.manifest.publishingInformation.locales" has no
            property defined


skill.json after build it looks like this 

{
	"manifest": {
		"publishingInformation": {
			"locales": {},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": "https://webhook.jovo.cloud/id_removed"
				}
			}
		},
		"manifestVersion": "1.0",
		"privacyAndCompliance": {
			"allowsPurchases": false,
			"locales": {},
			"isExportCompliant": true,
			"containsAds": false,
			"isChildDirected": false,
			"usesPersonalInfo": false
		}
	}
}

**Comment by aswetlow** [comment]
Hm, do you have the latest version of the cli? `jovo --v`

This is my working setup:

project.js
```javascript
// ------------------------------------------------------------------
// JOVO PROJECT CONFIGURATION
// ------------------------------------------------------------------

module.exports = {
    alexaSkill: {
       nlu: {
          name: 'alexa',
          lang: {
             ja: [
                'ja-JP',
              ],
              'de-DE': [
                 'de-DE'
              ]
         }
       },
    },
    googleAction: {
       nlu: 'dialogflow',
    },
    endpoint: '${JOVO_WEBHOOK_URL}',
};
```
/platforms/alexaSkill/skill.json
```json
{
	"manifest": {
		"publishingInformation": {
			"locales": {
				"de-DE": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"keywords": [
						"hello",
						"world"
					],
					"name": "issue559",
					"description": "Sample Full Description",
					"smallIconUri": "https://via.placeholder.com/108/09f/09f.png",
					"largeIconUri": "https://via.placeholder.com/512/09f/09f.png"
				},
				"en-US": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"keywords": [
						"hello",
						"world"
					],
					"name": "issue559",
					"description": "Sample Full Description",
					"smallIconUri": "https://via.placeholder.com/108/09f/09f.png",
					"largeIconUri": "https://via.placeholder.com/512/09f/09f.png"
				},
				"ja-JP": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"keywords": [
						"hello",
						"world"
					],
					"name": "issue559",
					"description": "Sample Full Description",
					"smallIconUri": "https://via.placeholder.com/108/09f/09f.png",
					"largeIconUri": "https://via.placeholder.com/512/09f/09f.png"
				}
			},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": "https://webhook.jovo.cloud/alex"
				}
			}
		},
		"manifestVersion": "1.0",
		"privacyAndCompliance": {
			"allowsPurchases": false,
			"locales": {
				"de-DE": {
					"privacyPolicyUrl": "http://example.com/policy",
					"termsOfUseUrl": ""
				},
				"en-US": {
					"privacyPolicyUrl": "http://example.com/policy",
					"termsOfUseUrl": ""
				},
				"ja-JP": {
					"privacyPolicyUrl": "http://example.com/policy",
					"termsOfUseUrl": ""
				}
			},
			"isExportCompliant": true,
			"containsAds": false,
			"isChildDirected": false,
			"usesPersonalInfo": false
		}
	}
}
```

Could you delete `/platforms/alexaSkill` and rerun `jovo build` ?

**Comment by santhosh77h** [comment]
Previous JOVO version is `2.2.8` after updating to `2.2.12` JOVO cli was able to create the `skill.json` accurately.
Thank you for the help
