### ISSUE TITLE
Synonyms do not map to the correct value

### ISSUE THREAD

**Issue by probststefan** [jovotech/jovo-framework#560]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Synonyms do not map to the correct value. 

`
{
	"name": "DrinkSelectionIntent",
	"phrases": [
		"{drink}",
		"{drink} bitte",
		"ich würde gerne {drink} trinken",
		"wir trinken {drink}",
		"ich trinke {drink}"
	],
	"inputs": [
		{
			"name": "drink",
			"type": "LIST_OF_DRINKS"
		}
	]
},

...

"inputTypes": [
    {
        "name": "LIST_OF_DRINKS",
        "values": [
            {
            	"value": "Champagner",
            	"synonyms": [
                    "Sekt"
                ]
            },
`

## Current Behavior
I expect the input "Sekt" to be mapped to "Champager" in "this.$inputs". But it returns this:

`
{
  drink: {
    name: 'drink',
    alexaSkill: { name: 'drink', value: 'sekt' },
    value: 'sekt',
    key: 'sekt'
  }
}
`

## Your Environment
* Jovo Framework version used: 2.2.15

**Comment by aswetlow** [comment]
Hey!

the value is mapped from the "said value".  I get `Champagner` in `key`.

What's your `jovo-platform-alexa` version? `jovo -v`

**Comment by probststefan** [comment]
Im running on jovo-platform-alexa: 2.2.17

**Comment by aswetlow** [comment]
Hm, any idea how I could reproduce it?

I tested it with the same version.

**Comment by probststefan** [comment]
Could you publish the code you used to try it out?

**Comment by aswetlow** [comment]
Alexa Language model:
```json
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "meine trink app",
            "intents": [
                {
                    "name": "DrinkSelectionIntent",
                    "slots": [
                        {
                            "name": "drink",
                            "type": "LIST_OF_DRINKS"
                        }
                    ],
                    "samples": [
                        "{drink}",
                        "{drink} bitte",
                        "ich würde gerne {drink} trinken",
                        "wir trinken {drink}",
                        "ich trinke {drink}"
                    ]
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "LIST_OF_DRINKS",
                    "values": [
                        {
                            "name": {
                                "value": "Champagner",
                                "synonyms": [
                                    "Sekt"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

app.js
```javascript
'use strict';

// ------------------------------------------------------------------
// APP INITIALIZATION
// ------------------------------------------------------------------

const { App } = require('jovo-framework');
const { Alexa } = require('jovo-platform-alexa');
const { GoogleAssistant } = require('jovo-platform-googleassistant');
const { JovoDebugger } = require('jovo-plugin-debugger');
const { FileDb } = require('jovo-db-filedb');

const app = new App();

app.use(
    new Alexa(),
    new GoogleAssistant(),
    new JovoDebugger(),
    new FileDb()
);


// ------------------------------------------------------------------
// APP LOGIC
// ------------------------------------------------------------------

app.setHandler({
    LAUNCH() {
        return this.ask('Welches Getränk?');
    },
    DrinkSelectionIntent() {
        console.log(this.$inputs);
        
    },
});

module.exports.app = app;

```

"öffne meine trink app"
"sekt"

console.log(this.$inputs) in DrinkSelectionIntent 
```
{ drink:
   { name: 'drink',
     alexaSkill:
      { name: 'drink',
        value: 'sekt',
        resolutions: [Object],
        confirmationStatus: 'NONE',
        source: 'USER' },
     value: 'sekt',
     key: 'Champagner',
     id: '3df2482b6c2a8670322f9232582d2300' } }
```

**Comment by aswetlow** [comment]
Are you using the jovo debugger?

**Comment by probststefan** [comment]
Yes, i'm using the jovo debugger.
What is the difference between "inputTypes" and "types". I have to name it "inputTypes" otherwise i get this error:  Input type "LIST_OF_DRINKS" must be defined in inputTypes

**Comment by aswetlow** [comment]
Oh, that's the problem here. The debugger doesn't support the mapping of synonyms yet. I will put it on a higher prioritized list, but won't be able to fix it within the next two weeks.

It works fine with the Alexa Simulator. (Install our Chrome Extension for a Jovo Debugger feeling :D https://chrome.google.com/webstore/detail/alexa-skills-kit-simulato/opjjjciodammljgdambcjmljkcjblkkk)

`inputTypes` is used in the Jovo Language Model and it's the equivalent of `types` in the Alexa Language Model.

**Comment by aswetlow** [comment]
We updated the Jovo Debugger. You can add the key or/and id to your requests.
You need to update your project to v 2.2.17 or later.
