### ISSUE TITLE
askApiUpdateSkill:Resource not found

### ISSUE THREAD

**Issue by spham** [jovotech/jovo-framework#569]
hi
for project already create, i wish to redeploy model into alexa console developer.

i make 
```
sylvain> jovo deploy
 
    ✔ Bundle Project
      ✔ Copy source code to "./bundle"
      ✔ Run "npm install --production"
      ✔ Zip "./bundle" folder
       -> Zip path: /Users/sylvain/alexa/lirePodCastSAP/bundle.zip
    ❯ Deploying Alexa Skill 
      ✖ Updating Alexa Skill project for ASK profile default
       -> askApiUpdateSkill:Resource not found.
```

i delete my skill manually in alexa developer .
so i think, it should not update, but recreate.

in fact, is work when i create new project, but for project already exist, and skill was remove in alexa developer, it not work

**Comment by aswetlow** [comment]
Hey!

Set `skillId` to "" in `/platforms/alexaSkill/.ask/config`

**Comment by spham** [comment]
Thanks
