### ISSUE TITLE
Add support to SAP CAI bot platform

### ISSUE THREAD

**Issue by StErMi** [jovotech/jovo-framework#571]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Add support to [SAP CAI](https://cai.tools.sap) bot platform. I would like to help to add support to this additional platform. Is there already a tutorial/example to follow in order to add support to more platform?

**Comment by aswetlow** [comment]
You delivered! Thanks again :)
