### ISSUE TITLE
Add Mycroft support

### ISSUE THREAD

**Issue by 12people** [jovotech/jovo-framework#576]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

[Mycroft](https://mycroft.ai) is the only open-source voice assistant there is. Its user base is relatively small, but it's basically the Linux of voice assistants. I'd like to target it, as a fan of open platforms, but I'd like to target the commonly used platforms as well.

Would you consider adding support for Mycroft as a third platform?

**Comment by jankoenig** [comment]
Thank you @12people, this is definitely something that has crossed our minds before. We just haven't had the time yet to implement it. Maybe this is something we can pull off together with the community?

**Comment by AFRI4N** [comment]
> 
> 
> Thank you @12people, this is definitely something that has crossed our minds before. We just haven't had the time yet to implement it. Maybe this is something we can pull off together with the community?

Thats some good new :1st_place_medal: 

But should't it be more difficult to implement this? Cause mycroft skills are written in python and also not everything is accessed in the cloud (actually u can configure just the stt engine to be processed in the cloud and the other technologies on device). So therefore the application could also be used offline

**Comment by koenvervloesem** [comment]
> Mycroft is the only open-source voice assistant there is.

This is not true. There are a lot of open-source voice assistants. For example, see [Rhasspy](https://rhasspy.readthedocs.io/en/latest/).

**Comment by aswetlow** [comment]
I close this issue due to incativity.

**Comment by krisgesling** [comment]
Yeah, from the Mycroft side it's not something we are ready to prioritize just yet but we are certainly mindful of it. I'll be sure to reach out when we have capacity to contribute.
