### ISSUE TITLE
HTTP 302: GoogleSheets CMS not working

### ISSUE THREAD

**Issue by AFRI4N** [jovotech/jovo-framework#580]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
The integration of a public google sheet as an ObjectArray doesnt work for me. Either its because of the np jovo-cms-googlesheets (which has a [high vulnerability](https://www.npmjs.com/advisories/791)) or it's a different bug

### Error log
npm audit:
```
 High            Improper Authorization

 Package         googleapis

 Patched in      >=39.1.0

 Dependency of   jovo-cms-googlesheets

 Path            jovo-cms-googlesheets > googleapis

 More info       https://npmjs.com/advisories/791
```
Jovo CLI:
```
Error -----------------------------------------------------------------
Code:
ERR_PLUGIN

Message:HTTP Response code 302

Stack:
Error: HTTP Response code 302
at IncomingMessage.res.on (...\node_modules\jovo-cms-googleshts\src\GoogleSheetsCMS.ts:212:10)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1103:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

Module:jovo-cms-spreadsheets

Hint:This might occur when you try to access a private spreadsheet without the permission.
--------------------------------------------------------------------------------------------------------------------------------------------
WARN: Jovo instance is not available. ON_ERROR doesn't work here
```

## Your Environment
* Jovo Framework version used: 2.2.15
* Operating System: Win7
* Jovo CLI Version: 2.2.12
* Jovo packages of current project:
  jovo-cms-googlesheets: 2.2.14
  jovo-cms-i18next: 2.2.13
  jovo-core: 2.2.12
  jovo-db-filedb: 2.2.12
  jovo-framework: 2.2.15
  jovo-platform-alexa: 2.2.17
  jovo-platform-dialogflow: 2.2.13
  jovo-platform-googleassistant: 2.2.15
  jovo-plugin-debugger: 2.2.13

**Comment by jankoenig** [comment]
Hi @AFRI4N, did you do "File > Publish to Web" in your spreadsheet?

**Comment by AFRI4N** [comment]
> 
> 
> Hi @AFRI4N, did you do "File > Publish to Web" in your spreadsheet?

@jankoenig Yes I did so. Have set the drive to ger currently but It is shared as a link everybody can access and view (but not edit)
![grafik](https://user-images.githubusercontent.com/50735002/65328111-d031d100-dbb5-11e9-8629-cfb70e3a2e8e.png)

**Comment by AFRI4N** [comment]
Edit: I had it configured that `anybody with the link` can access the spreadsheet. I changed it to `everyone on the internet`. 

Instead of refering to the sheetname I refered to the file name which seemed to be the problem here. sry for wasting your time

**Comment by jankoenig** [comment]
Ah, thanks for clarifying, @AFRI4N !
