### ISSUE TITLE
Intent defined in intents and dialogflow sections produces incorrect json

### ISSUE THREAD

**Issue by gcasares** [jovotech/jovo-framework#614]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

This language model:

```json
{
   "invocation":"",
   "intents":[
      {
         "name":"Test",
         "phrases":[
            "GlobalPhrase"
         ]
      }
   ],
   "dialogflow":{
      "intents":[
         {
            "auto":true,
            "webhookUsed":true,
            "name":"Test",
            "userSays":[
               "DialogflowPhrase"
            ]
         }
      ]
   }
}

```

Should produce this Test_usersays_en.json running **jovo build -p googleAction** : 

```json
[
   {
      "data":[
         {
            "text":"GlobalPhrase",
            "userDefined":false
         }
      ],
      "isTemplate":false,
      "count":0
   },
   {
      "data":[
         {
            "text":"DialogflowPhrase",
            "userDefined":false
         }
      ],
      "isTemplate":false,
      "count":0
   }
]
```

## Current Behavior

Instead it returns this json:

```json
[
	"DialogflowPhrase"
]			"text": "GlobalPhrase",
				"userDefined": false
			}
		],
		"isTemplate": false,
		"count": 0
	}
]

```
### Error log
```
No error logs.
```

## Your Environment

* Jovo CLI Version: 2.2.12

Jovo packages of current project:
  jovo-cms-i18next: 2.2.16
  jovo-core: 2.2.15
  jovo-db-filedb: 2.2.15
  jovo-framework: 2.2.20
  jovo-platform-alexa: 2.2.22
  jovo-platform-dialogflow: 2.2.17
  jovo-platform-googleassistant: 2.2.20
  jovo-plugin-debugger: 2.2.17

**Comment by aswetlow** [comment]
Hey @gcasares! Thanks for posting!

I found the bug. Concurrent file write doesn't work on a single file :)
Nevertheless, the expected behavior is a little different here:

1) The object in the dialogflow/intents array should look like this:

```
"dialogflow":{
		"intents":[
			{
				"auto":true,
				"webhookUsed":true,
				"name":"Test",
				"userSays":[
					{
						"data": [
							{
								"text": "DialogflowPhrase",
								"userDefined": false
							}
						],
						"isTemplate": false,
						"count": 0
					}
				]
			}
		]
	}
```

2) The platform-specific stuff always overrides the generic part.  The expected behavior is:

```
[
	{
		"data": [
			{
				"text": "DialogflowPhrase",
				"userDefined": false
			}
		],
		"isTemplate": false,
		"count": 0
	}
]
```


I will publish the fix later today. #nodeployfridays :)

**Comment by gcasares** [comment]
Ohhh Okay.

There is a limitation on the length of the Alexa json model, so we define X training phrases for Alexa and we define X+Y training phrases for Dialogflow.

It would be cool if there was a flag to allow the platform-specific stuff to extend the generic part instead of overriding it. So that we don't have to write the X training phrases two times.

**Comment by aswetlow** [comment]
Hm, I understand. It wasn't on the roadmap yet. I will add it.
