### ISSUE TITLE
Dashbot custom analytics integration

### ISSUE THREAD

**Issue by piotrjak** [jovotech/jovo-framework#615]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:
We're using custom Dialogflow integration instead of Google Actions or Alexa Skills and we want to integrate Dashbot. We looked into https://github.com/jovotech/jovo-framework/blob/master/jovo-integrations/jovo-analytics-dashbot/src/DashbotGoogleAssistant.ts to see how the plugin should look like, mirrored the implementation to use dashbot.universal, but Jovo doesn't seem to be aware of it (it doesn't even forward the api key in config).

## Expected Behavior

Logging to Dashbot using custom integration of Jovo Analytics

## Current Behavior

here's how it looks (i'm using js instead of ts)
DashbotDialowflow.js
```
const dashbot = require('dashbot');
const _ = require('lodash');

class DashbotDialogflow {
  constructor(config) {
    this.config = {
      key: '',
    };
    if (config) {
      this.config = _.merge(this.config, config);
    }
    this.track = this.track.bind(this);
  }

  install(app) {
    this.dashbot = dashbot(this.config.key).universal;
    app.on('response', this.track);
  }

  uninstall(app) {
    app.removeListener('response', this.track);
  }

  track(handleRequest) {
    if (!handleRequest.jovo) {
      return;
    }

    if (handleRequest.jovo.constructor.name === 'DialogflowAgent') {
      this.dashbot.logIncoming(handleRequest.host.getRequestObject());
      this.dashbot.logOutgoing(handleRequest.host.getRequestObject(), handleRequest.jovo.$response);
    }
  }
}

module.exports = DashbotDialogflow;
```
jovo.js
```
    jovo.use(
      new Firestore(),
      new Alexa(),
      new GoogleAssistant(),
      new JovoDebugger(),
      new Dialogflow().use(new FacebookMessenger()),
      new GoogleSheetsCMS(),
      new DashbotDialogflow(), // the instance of the class from above
    );
```
config.js
```
module.exports = {
// some other config
  analytics: {
    DashbotDialogflow: {
      key: 'MY_API_KEY',
    },
  },
};

```
### Error log
```
If you have an error log, please paste it here.
```
There are no visible errors yet
Screen from debug what shows that no api key is passed
![image](https://user-images.githubusercontent.com/45995385/68399806-421aa580-0177-11ea-8fb1-78760a251bbb.png)

## Your Environment

* Jovo Framework version used: 2.2.14
* Operating System: macOS Mojave

**Comment by piotrjak** [comment]
Ok, it actually passes the api key to the config. So the issue is that the `track` function isn't triggered after jovo response is sent (I call `jovo.tell('response')` and the response is sent back as HTTP response, but this `track` function is not called)

**Comment by aswetlow** [comment]
Hey @piotrjak!

I modified your code a little and my track method gets called 😕 

Can you try my sample code.

```javascript

const app = new App();
class DashbotDialogflow {
    constructor(config) {
        this.config = {
            key: '',
        };
        if (config) {
            this.config = _.merge(this.config, config);
        }
        this.track = this.track.bind(this);
    }

    install(app) {
        app.on('response', this.track);
    }
    uninstall(app) {
        app.removeListener('response', this.track);
    }
    track(handleRequest) {
        if (!handleRequest.jovo) {
            return;
        }

        console.log('track');
    }
}
app.use(
    new Alexa(),
    new GoogleAssistant(),
    new JovoDebugger(),
    new FileDb(),
    new DashbotDialogflow(),
);
``` 
Does it log "track"?

**Comment by piotrjak** [comment]
it works now. I didn't change anything, but thanks for a very quick reply - I really appreciate it!
