### ISSUE TITLE
Support for APLT

### ISSUE THREAD

**Issue by NovaGL** [jovotech/jovo-framework#618]
## I'm submitting a...
- [ ] Other... Please describe:
- [x] Feature request
- [ ] Bug report
- [ ] Documentation issue or request

Just wanting to know if support for the Echo Dot Clock will be added.
https://developer.amazon.com/blogs/alexa/post/4228a00a-655d-45fe-80aa-f6d4eaf8a441/build-skills-on-echo-dot-with-clock-with-alexa-presentation-language-apl

It would be really cool to see.

**Comment by aswetlow** [comment]
We had a [PR ](https://github.com/jovotech/jovo-framework/pull/606)(by @kouz75) about two weeks ago with a few helper methods.

You could try something like this (not tested)

```javascript

if (this.$alexaSkill.hasAPLTInterface()) {
    this.$alexaSkill.addDirective({
  "type": "Alexa.Presentation.APLT.RenderDocument",
  "token": "developer-provided-string",
  "targetProfile": "FOUR_CHARACTER_CLOCK",
  "document": {
    "version": "1.0",
    "type": "APLT",
    "mainTemplate": {
      "item": {
        "type": "Text",
        "id": "myTextId",
        "textAlign": "right",
        "text": "Hello",
        "overflow": "marquee"
      }
    }
  },
  "datasources": {}
});
}
```

**Comment by NovaGL** [comment]
Thanks, I don't have an Echo Dot Clock atm to test this.

Thanks for this great framework though. I have published a skill using JOVO with APL and Video support.

It's upto you if you want to close this issue.
