### ISSUE TITLE
Reminder API resolving successfully when receiving an error response

### ISSUE THREAD

**Issue by gshenar** [jovotech/jovo-framework#629]
## I'm submitting a...

- [ X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When calling the reminder API, all errors should throw with the error type. However now only the 401's are handled as errors. Other errors such as 400s with bad reminder requests return successfully.

These return a ReminderResponse type, which actually is an error, so right now the workaround is to still add a check if the successful reminder response actually has an 'code' property which would be the error. 

Here are the other error types that should be handled:
https://developer.amazon.com/docs/smapi/alexa-reminders-api-reference.html#error-messages
 
This is where the bug lives:
https://github.com/jovotech/jovo-framework/blob/1f7fedca249b9d9c3018a4c2ba2646c7af378571/jovo-platforms/jovo-platform-alexa/src/services/AlexaReminder.ts#L28

## Current Behavior
Right now if you send a bad request, like a badly formatted time, it will return a 400, which isnt handled by the Jovo api handler code and returns the response as if it was a success. The returned ReminderResponse type doesn't actually have the properties of that interface, it's just the error code from amazon. These errors should have promise.reject called on them too so they can be handled in the error handler by the consumer.

## Your Environment

* Jovo Framework version used: Latest

**Comment by aswetlow** [comment]
Oh, yes. Terrible bug. Fixed it and will publish later today!

**Comment by aswetlow** [comment]
Done.
