### ISSUE TITLE
GetUserId logic broken

### ISSUE THREAD

**Issue by gshenar** [jovotech/jovo-framework#630]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

this.getUserId() and this.$user.GetId() should return the same value

## Current Behavior
Ran into a ton of crazy issues once I implemented skill events. Realized that this.getUserId returns null within skill event since the session object isnt populated. this.$user.getId() works though.

There is a mismatch between the two methods on AlexaSkill and AlexaRequest. As you can see, when the user is on the session its fine. But on AlexaSkill, the userId property is reading from context.user when it should be context.System.user.

https://github.com/jovotech/jovo-framework/blob/1f7fedca249b9d9c3018a4c2ba2646c7af378571/jovo-platforms/jovo-platform-alexa/src/core/AlexaSkill.ts#L144

https://github.com/jovotech/jovo-framework/blob/1f7fedca249b9d9c3018a4c2ba2646c7af378571/jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts#L532

### Error log
N/A

## Your Environment

* Jovo Framework version used: latest

**Comment by KaanKC** [comment]
Good catch. `this.getUserId()` should actually call `this.$user.getId()` instead of accessing the request itself. `this.getUserId()` is actually deprecated.

Will fix it later today. Thanks!

**Comment by aswetlow** [comment]
Fixed and published
