### ISSUE TITLE
:bug: Default Google intent request includes screen capabilities

### ISSUE THREAD

**Issue by IGx89** [jovotech/jovo-framework#640]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Description
If you compare the sample intent requests between Alexa and Google (Dialogflow), you'll see that the Alexa one [doesn't include screen capabilities](https://github.com/jovotech/jovo-framework/blob/master/jovo-platforms/jovo-platform-alexa/sample-request-json/v1/IntentRequest1.json#L24) but the Dialogflow one [does](https://github.com/jovotech/jovo-framework/blob/master/jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/DefaultWelcomeIntent.json#L49,L80) (SCREEN_OUTPUT). That causes problems when using the request builder to build intent requests for unit tests, because there's then no way to create a Dialogflow request that doesn't have a screen interface (JovoRequest has a setScreenInterface method but not a clearScreenInterface method).

## Your Environment
* Jovo Framework version used: 2.2.25
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Good catch! Thank you.
Do you want to make a PR or should I fix it?

**Comment by IGx89** [comment]
Might be better you fix it, I don't have a development environment set up at the moment. No rush though. Thank you!

**Comment by aswetlow** [comment]
Fixed and published
