### ISSUE TITLE
after accountlinking unable to get user accesstoken from alexa console due to skill i/o blank

### ISSUE THREAD

**Issue by siddharthaweb** [jovotech/jovo-framework#642]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x ] Other... Please describe:

## Bug report - 
```
after accountlinking unable to get user accesstoken from alexa console due to skill i/o (alexa console test) is blank. is there any way to debug? 
I think alexa console some how unable to parse response, but jovo cloud(debugger webhook url) return everything properly.
```
## Feature request - 
```
add features to test accountlinking in jovo debuger webhook url.
```

## Your Environment
* Jovo Framework version used: 2.2.14
* Operating System: windows10

**Comment by SStauden** [comment]
Hey, I am currently struggeling with exactly this problem. I successfully set up account linking but I can only test the app in interaction with a user using the Amazon Alexa Console.

I know, that one can set the token in unit testing, but for fast demonstration, this is not an option for me.

It would be nice, to set the accessToken data directly in the debugger or at least set it in the config.js, which is currently not possible.

**Comment by aswetlow** [comment]
Hey @SStauden 

I will add it to the feature requests. This is a workaround for now. Add this to your app.js/app.ts

```
app.hook('after.platform.init', async (error, host, jovo) => {
	jovo.$request.setAccessToken('my-access-token');
});
```
