### ISSUE TITLE
Forever or Service (Init.d) BUG

### ISSUE THREAD

**Issue by marab2** [jovotech/jovo-framework#650]
I've created a init.d service script to keep jovo running, but for unknown reason, the script is working fine with the Jovo Debugger Webhook but it doesn't work with Google Dialog flow, But when I do the manual start for jovo with jovo run, everything works perfect, the Jovo Debbuger Webhook and the Google Dialog. 

Here is a copy of my init.d service script
Attached: https://pastebin.com/Q8ADJJPc

**To conclude, I want anything that keeps Jovo running while my terminal is closed, I tried nohup, I tried forever, but all is leading into the same issue, it works with the online webhook but not Google Dialog.**

**Comment by marab2** [comment]
Please I need urgent solotuin for this, anyone to help?

**Comment by aswetlow** [comment]
Hey @marab2!
You could try pm2 (https://pm2.keymetrics.io/)

`pm2 start index.js --webhook` (not tested)

**Comment by jankoenig** [comment]
Closing this

**Comment by marab2** [comment]
@jankoenig I found the soloution for this. 
On CentOS you have to do the following:-
screen (It's a command to attach console session to a command)
then start Jovo with command

It does work fine in every aspect.
