### ISSUE TITLE
Outdated documentation for Google Assistant - Visual Output

### ISSUE THREAD

**Issue by ismaelgt** [jovotech/jovo-framework#657]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Examples in documentation for [Google Assistant - Visual Output](https://www.jovo.tech/docs/google-assistant/visual-output) work without runtime errors.

## Current Behavior

Examples in documentation for [Google Assistant - Visual Output](https://www.jovo.tech/docs/google-assistant/visual-output) don't work correctly and produce runtime errors.

### Error log

For [Table Card](https://www.jovo.tech/docs/google-assistant/visual-output#table-card), for example:

```
TypeError: GoogleAssistant.Table is not a constructor
```

## Your Environment

* Jovo Framework version used: 2.2.14
* Operating System: MacOS 10.15.3

**Comment by aswetlow** [comment]
Thanks for pointing out. 

This should work:
```
const {
    GoogleAssistant,
    Table
} = require('jovo-platform-googleassistant');
```
```
 const table = new Table()
            .setTitle('Table Title')
            .setImage({
                    url: 'http://via.placeholder.com/250x250?text=Table',
                    accessibilityText: 'accessibilityText'
                })
            .addColumn('header 1','CENTER')
            .addColumn('header 2','LEADING')
            .addColumn('header 3','TRAILING')
            .addRow(['row 1 item 1', 'row 1 item 2', 'row 1 item 3'], false)
            .addRow(['row 2 item 1', 'row 2 item 2', 'row 2 item 3'], true)
            .addRow(['row 3 item 3', 'row 3 item 2', 'row 3 item 3'])
            .addButton('Button Title', 'https://github.com/jovotech/jovo-framework')

        this.$googleAction.showTable(table);
        this.$googleAction.showSuggestionChips(['List', 'Carousel', 'Basic card', 'Table']);
        this.ask('Response with table', '?');
```

**Comment by ismaelgt** [comment]
Thanks! I've submitted a PR that fixes the docs: https://github.com/jovotech/jovo-framework/pull/658
