### ISSUE TITLE
If at all possible, don't delete .git directory during jovo new

### ISSUE THREAD

**Issue by finnbear** [jovotech/jovo-framework#692]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
If I create a new Git repository via a provider like GitHub or GitLab, clone it to my computer, run `jovo new [repo-directory]`, and confirm overwriting the non-empty directory (contains `.git` and `README.md`), the `.git` directory should not be deleted.

## Current Behavior
`.git` gets deleted, meaning access to the remote is lost until the `.git` from a 2nd clone is transplanted in.

This is despite Jovo being git-aware in other ways, mainly creating a `.gitignore` file

* Jovo Framework version used: 3.0
* Operating System: Ubuntu 18.04

**Comment by jankoenig** [comment]
Thank you @finnbear, this is an interesting suggestions.

Haven't considered this because our workflow is usually like this:
* Create a new Jovo project with `jovo new`
* Initialize git repo
