### ISSUE TITLE
In Hello World Templat use "local" gulp

### ISSUE THREAD

**Issue by Londane** [jovotech/jovo-framework#693]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

after npm install bundle should work without external dependencies
maybe change bundle script to
```
"bundle": "node ./node_modules/gulp/bin/gulp.js --gulpfile node_modules/jovo-framework/gulpfile.js build-ts --cwd ./",
```

**Comment by aswetlow** [comment]
I think `npm run ...` will look in the local `/node_modules`. 

I tried this without a global gulp installation and it worked.
```
 "bundle": "gulp --gulpfile node_modules/jovo-framework/gulpfile.js --cwd ./",
```
