### ISSUE TITLE
Strange behaviour when returning null from handler

### ISSUE THREAD

**Issue by RokasVaitkevicius** [jovotech/jovo-framework#700]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When handler is returning `null`, code shouldn't crash with obscure error message. It should either do nothing as when returning `undefined`, or throw a descriptive message explaining why `null` shouldn't be returned.

## Current Behavior

In one of skill events handler I returned `null` as the result of the function and I got an error with message that said this: `Cannot read property 'constructor' of null`.

From this error it is unclear, that it was caused by me, returning `null` from my handler. I don't know if it is by design, if so please explain why is it so, but it is quite strange when you can return `undefined` from handler and get no errors, while `null` causes this issue.

It seems that to fix this, additional `if` statement should be added here: 
https://github.com/jovotech/jovo-framework/blob/eea4371a4925c5ab7bea1357281813055f7a645f/jovo-core/src/plugins/Handler.ts#L96-L106
which would handle a return type of null, by either throwing a descriptive error message, or as `undefined`, just returning nothing.

### Error log
```
Error -----------------------------------------------------------------

  Message:
  Cannot read property 'constructor' of null

  Stack:
  TypeError: Cannot read property 'constructor' of null
      at Function.applyHandle (/../node_modules/jovo-framework/src/middleware/Handler.ts:189:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)

   ----------------------------------------------------------------------
```

**Comment by jankoenig** [comment]
Thanks @RokasVaitkevicius, we'll take a look! Also, feel free to submit a PR for the fix, this doesn't seem like intentional behavior :)
