### ISSUE TITLE
Facebook Messenger verification failing

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#715]
## I'm submitting a...

- [ X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
After adding fb messenger plugin, versification should pass using /get endpoint. 
Response should return ```hub.challenge``` without quotes. 

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Connection: keep-alive
929371381
```

[fb](https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup/)

## Current Behavior
When I'm adding fb platform to default helloword example and try to do challenge webhook is not verified. 
Response body is almost ok as it's returning ```hub.challenge``` but inside quotes. 

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Connection: keep-alive
"929371381"
```

The same is happening when I'm using cloud functions. 

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 3.0.11
* Operating System:

**Comment by aswetlow** [comment]
Hey @Mistic92 
How did you set up your app? Like here? https://github.com/jovotech/jovo-framework/blob/master/examples/typescript/05_facebookmessenger/hello-world/src/app.ts

```
const messenger = new FacebookMessenger({
	pageAccessToken: '<PAGE-ACCESS-TOKEN>',
	verifyToken: 'token123'
});
```
Callback URL: `https://webhook.jovo.cloud/<USER-ID>`
Token: `token123`

That worked for me.

**Comment by Mistic92** [comment]
No, I was using this one https://www.jovo.tech/docs/facebook-messenger

**Comment by aswetlow** [comment]
I don't quite understand it yet. Which part is not working? The webhook validation process?

I tried it with the Jovo Webhook and AWS Lambda via API Gateway. Both worked.
Can you provide more info about your environment?

**Comment by Mistic92** [comment]
Example won't work as Facebook need GET endpoint for verification while in example we support only POST. 

```
Webhook.post('/webhook', async (req: any, res: any) => { // tslint:disable-line
        await app.handle(new ExpressJS(req, res));
    });
```

After adding GET I'm getting error 

```
  Error -----------------------------------------------------------------

  Code:
  ERR_PLUGIN

  Message:
  Error: Request failed with status code 400

  Stack:
  Error: Error: Request failed with status code 400
      at FacebookMessenger.setup (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-platform-facebookmessenger/src/FacebookMessenger.ts:162:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Module:
  FacebookMessenger

   ----------------------------------------------------------------------


   ----------------------------------------------------------------------
```

I'm running on WIndows 10 with WSL2 using jovo run --watch

**Comment by Mistic92** [comment]
In Facebook dev center there is setting for Webhook field version control and the only one version available for me is 6.0 while Jovo try to do requests to 5.0
https://github.com/jovotech/jovo-framework/blob/master/jovo-platforms/jovo-platform-facebookmessenger/src/index.ts#L9

**Comment by aswetlow** [comment]
Oh, I see.

There might be a missing part in the docs and it looks like FB doesn't allow older versions in newly created apps. I tested it with an existing Facebook app where I was able to choose between different versions.

I will take a look later today and come back to you.

**Comment by aswetlow** [comment]
Heyhey @Mistic92 

Finally...We (@m-ripper) fixed it and did some further improvements.

Please update your packages:
`jovo update`

**Comment by Mistic92** [comment]
Thanks, now it's working! And logs are super helpful. You are awesome
