### ISSUE TITLE
jovo get can't access ask-cli

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#722]
## I'm submitting a...

- [ X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
jovo get/deploy should have access to ask-cli as it's installed

## Current Behavior
I'm getting error that I should install ask-cli

### Error log
```
λ jovo deploy
  > Deploying Alexa Skill
    × Creating Alexa Skill project for ASK profile default
      → Please read more: https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html
      Deploying Interaction Model, waiting for build
    Deploying Google Action
 »   Error: There was a problem:
 »   Error: Jovo requires ASK CLI
 »   Please read more: https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html
```

```
λ jovo get
 »   Error: There was a problem:
 »   Error: Jovo requires ASK CLI
 »   Please read more: https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html
```

## Your Environment

* Jovo Framework version used: 3.0.13
* Operating System: Windows 10

**Comment by jankoenig** [comment]
Hi. Amazon just upgraded their ASK CLI to v2.x, which is a breaking change. We're currently working on a fix, until then the Jovo CLI only works for ASK CLI versions <2

You can also go into the platforms folder `platforms/alexaSkill` and use the ASK CLI commands there

**Comment by Mistic92** [comment]
Oh thank you! Will take a look at this

**Comment by Mistic92** [comment]
I tried to use ask deploy from ```platforms/alexaSkill``` but it's giving me Warning and nothing more ```[Warn]: Please make sure you are in the root directory of the project.```. 
Is jovo build still compatible with ask?

**Comment by Mistic92** [comment]
Jovo generated alexa project is not compatible with ask V2. 

https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html

What is the timeline to for update?

**Comment by jankoenig** [comment]
We're working on the fix. Until then, we recommend to downgrade the ASK CLI to v1.7

**Comment by rubenaeg** [comment]
The newest version of the Jovo CLI is supporting ASK CLI v2. You can upgrade using `npm install jovo-cli -g`.

**Comment by Mistic92** [comment]
I updated and now I can't build skill package. 
```
λ jovo build

 jovo build: Build platform-specific language models based on jovo models folder.
   >> Learn more: https://jovo.tech/docs/cli/build

  √ Initializing build process...
    √ Collecting platform configuration from project.js.
      Platforms: alexaSkill, googleAction
    √ Collecting Jovo language model files from ./models folder.
      Locales: en-US
    √ Validating model files.
  √ Initializing build process...
    √ Collecting platform configuration from project.js.
      Platforms: alexaSkill, googleAction
    √ Collecting Jovo language model files from ./models folder.
      Locales: en-US
    √ Validating model files.
      √ en-US
  > Creating Alexa Skill project files
   Path: ./platforms/alexaSkill
    √ Creating Alexa project files
      √ skill.json
    > Creating Alexa Interaction Model
      Path: ./platforms/alexaSkill/interactionModels/custom
      × en-US
        → Cannot find module 'C:\Projects\bot\platforms\alexaSkill\skill-package\interactionModels\custom\en-US.json'
    Creating Google Action project files
   Path: ./platforms/googleAction
 »   Error: There was a problem:
 »   Error: Cannot find module 'C:\Projects\bot\platforms\alexaSkill\skill-package\interactionModels\custom\en-US.json'
```

I don't see any specific warnings in changelog.md which I should do before updating to new cli.

**Comment by rubenaeg** [comment]
If you don't care if something gets overwritten in `./platforms/alexaSkill/`, use `jovo build --clean`.

**Comment by Mistic92** [comment]
I have removed whole folder and still the same.

**Comment by rubenaeg** [comment]
Could you post your `project.js` and your language model here, without any sensitive information? Trying to replicate the bug...

**Comment by Mistic92** [comment]
Can you open DM on Twitter? I'd send you link to secret gist. Can't share there whole model file

**Comment by aswetlow** [comment]
I think this is resolved by now - Re-open if not. Thank you
