### ISSUE TITLE
Missing phrases when build --reverse from Dialogflow

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#725]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
All training phrases from Dialogflow imported into data model as phrases for each language. 

## Current Behavior
Reversed en-us.json file have all intents imported bug missing phrases from Dialogflow. 

We have default language set to ```en``` but it was not working also with ```pl+en```. 
I'm using 
```jovo get googleAction``` and then ```jovo build -p googleAction --reverse```

## Your Environment

* Jovo Framework version used: 3.0.13
* Operating System:

**Comment by Mistic92** [comment]
I tried to update lang in usersays file file and change file name from en to en-us or en_us but it's not working.

**Comment by aswetlow** [comment]
Hey @Mistic92!
Sorry, haven't noticed this issue.

Is it still not working?

**Comment by Mistic92** [comment]
Would need to check as we resigned from reverse build of bots and we are building them from scratch with jovo.

**Comment by aswetlow** [comment]
Thank you for the quick reply.

Closing the thread for now.
