### ISSUE TITLE
Google Actions not working when deploying multiple languages

### ISSUE THREAD

**Issue by jlopezr** [jovotech/jovo-framework#729]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I am having problems when I add multiples languages, i.e en-GB and es-ES. Jovo builds and deploys the intents to the dialogflow console. 

## Current Behavior

The intents work on the intent debugger but when I test it on google actions, it only speaks the launch intent. After this, the rest of intents return error.

### Error log

MalformedResponse
Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: a7923580-f9c9-49d8-bdd5-5ec5a4b99a10 and intentId: 890ff652-913b-4feb-89e3-d9d18a4fbf33. WebhookStatus: message: "Webhook execution successful" ..

## Your Environment

* Jovo Framework version used: 3.0.13

**Comment by aswetlow** [comment]
Oh sorry, this got totally lost somehow. 

Does the webhook get called? What's your response JSON?

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
