### ISSUE TITLE
Extracting a custom slot from a user random input

### ISSUE THREAD

**Issue by davidmatilla17** [jovotech/jovo-framework#736]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x ] Documentation issue or request
- [ ] Other... Please describe:

We have an intent with a custom slot called topic. The values of this slots could be for example:

Sports, Science, Cinema, TV
So our sample Utterances are like this:
{topic}
tell me about {topic}
what do you know about {topic}
i love {topic}

This works correctly if the users uses phrases like the ones in the sample utterances. But, is there a way to achieve the following?

We want the user to be able just to say anything between and after the {topic} . Something like:

{any} {topic} {any} - {what do you think about} {sports} {my friend?}

or

{any} {topic} - {i hate everything related with } {sports}

Is there a way for Alexa Skill to extract the {Topic} from any random phrase?

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
