### ISSUE TITLE
Unexpected .addAudio() behaviour

### ISSUE THREAD

**Issue by GarethBeddis** [jovotech/jovo-framework#737]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

```
this.$speech.addAudio(audioFile1, false)
this.$speech.addAudio(audioFile2, 'Alternative text 2', true)
```

Line one should not output given the `false` condition.

Given the condition `true`, line 2 should output audioFile2 on Alexa, 'Alternative text 2' on Google. 

Going off of the below documentation, alternative text and conditions inside the .addAudio speechbuilder method should work:

> addAudio(url, alternativeText) | Add link to audio file and alternative text for Google Assistant.

[https://www.jovo.tech/docs/output/speechbuilder#features](https://www.jovo.tech/docs/output/speechbuilder#features)

> You can also add a condition as a parameter to any speechBuilder method.
> .addText('Welcome back!', !this.$user.isNewUser());

[https://www.jovo.tech/docs/output/speechbuilder#conditions](https://www.jovo.tech/docs/output/speechbuilder#conditions)

[https://www.jovo.tech/docs/reference/AlexaSpeechBuilder.html](https://www.jovo.tech/docs/reference/AlexaSpeechBuilder.html)

## Current Behavior

Output is:

```
// This ignores condition `false`
'<Audio Response using audioFile1 /> false'

// This accepts the condition `true` but uses both audio and alt. text
`<Audio Response using audioFile2 /> Alternative Text 2'
```

Exact output:

```
<speak><audio src=\"foo.mp3">false</audio> <audio src=\"bar.mp3\">Alternative text 2</audio></speak>
```
### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 3.0.9

**Comment by AndresContreras96** [comment]
Hello, can I take this issue for my first contribution?

**Comment by jankoenig** [comment]
Hey @AndresContreras96, thanks a lot for offering your help! Sure, please let me know if you have any questions :)

Here is more info about setting up the repo for development: https://www.jovo.tech/docs/contributing

**Comment by AndresContreras96** [comment]
@jankoenig Hello, I was learning about Jovo and now I running test to duplicate the behaviour reported, I have a question about the alternative text, I am currently using the debugger with the command jovo run and this alternative text is a response in case audio fails? at the moment I can visualize only in console

**Comment by jankoenig** [comment]
Hi @AndresContreras96,
Alternative Text is used for Google Assistant usage on the phone, for example, where it is necessary to also display visual output next to audio output. You can learn more about setting up a Google Action and testing in the Actions on Google Simulator here: https://www.youtube.com/watch?v=jKujwlF-iO4&t=1s

**Comment by AndresContreras96** [comment]
Hi @jankoenig, I already found the behavior reported in the bug and according to the file speechbuilder.js the parameter text can't be null check, I want to make a little change to allow addAudio behave like this:
this.$speech.addAudio(audioFile1, false)
![image](https://user-images.githubusercontent.com/63315471/85754026-5db8c900-b6d2-11ea-8f50-e448d5bad4d8.png)
My current problem is to run my clone of jovo framework locally, I've already run npm link and I'm receiving this error when I run the debugger:
Message:
  this.toIntent is not a function
  
  Stack:
  TypeError: this.toIntent is not a function
I run jovo update in my project already
