### ISSUE TITLE
Question: webchat userId

### ISSUE THREAD

**Issue by Catharsis68** [jovotech/jovo-framework#76]
Hey guys I've got a question regarding the user id and dialogflow.

Beside my voice Service for Google Assistant I created an additional webchat with the same logic / intents. But if for a webchat there is no user ID provided by dialogflow.
So my question is, can I set the *userId* somehow manually?

Thank you and best  regards, Markus

**Comment by jankoenig** [comment]
Hi Markus, interesting question. We're currently busy planning the launch of Jovo Framework `v1` next week, but will get back to you as soon as possible :)

**Comment by jankoenig** [comment]
Hey @Catharsis68, sorry, this got lost somehow. Did you get this resolved? Closing it for now due to inactivity. Feel free to reopen if this is still an active issue for you
