### ISSUE TITLE
Dynamic entities

### ISSUE THREAD

**Issue by scastrec** [jovotech/jovo-framework#768]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I want to be able to send Dynamic Entities on Alexa and Google through a simple api like:
this.updateEntities(entities).
  

## Current Behavior
I found that dynamic entities for Alexa are [available here](https://github.com/jovotech/jovo-framework/blob/master/jovo-platforms/jovo-platform-alexa/src/core/AlexaResponse.ts)  
I didn't find anything for Assistant. 

That's pretty simple to develop. You can find a sample in this cross lib:
* [Interfaces](https://github.com/StephaneC/ActionSkillLib/blob/master/src/DynamicEntities.ts)
* [Actions implementation](https://github.com/StephaneC/ActionSkillLib/blob/master/src/action/ActionEntities.ts)
* [Alexa implementation](https://github.com/StephaneC/ActionSkillLib/blob/master/src/skill/SkillEntities.ts)

## Your Environment
* Jovo Framework version used: 3.0.18

**Comment by jankoenig** [comment]
Hi @StephaneC,

Take a look at session entities: https://www.jovo.tech/marketplace/jovo-platform-googleassistant#session-entities

Happy to discuss adding an abstracted method

**Comment by StephaneC** [comment]
Thanks @jankoenig  
Can you tell me the rule to regroup one api in the multiplateform part?

**Comment by jankoenig** [comment]
I'm not sure I fully understand your request, could you elaborate? :) Thanks

**Comment by StephaneC** [comment]
As a voice dev, i dislike doing 
`this.googleAction().XXX`and prefere this.XXX`.

I think that stuffs like below could _easily_ be added as this.XXX for alexa and assistant. 
* showBasicCard
* showList
* dynamicEntities
 
So, how can we decide to add it to [Jovo](https://github.com/jovotech/jovo-framework/blob/master/jovo-core/src/core/Jovo.ts) like *ask* and *tell* ?

**Comment by jankoenig** [comment]
You're absolutely right @StephaneC. @aswetlow and I will discuss this with the team

**Comment by StephaneC** [comment]
@jankoenig Thanks. If you want me to add it, come back to me. If not, this issue could be close;

**Comment by aswetlow** [comment]
Since we now support many platforms, it is becoming increasingly difficult to abstract functions that work for all platforms.

How should we define the behavior of functions that are not available for a platform, like `showList`. Feels wrong to add it, but keep it empty.

Open for a discussion. We definitely can and need to improve it.

**Comment by jankoenig** [comment]
I think graceful fallbacks or ignores could work. On Google Assistant voice-only speakers, carousels, lists, are ignored as well and only displayed on visual devices. If we make sure we're thoughtful in our docs, we could make this work, at least for the basic stuff like cards etc

**Comment by m-ripper** [comment]
This has been implemented via [output templates](https://www.jovo.tech/docs/output#output-templates) in v4: https://www.jovo.tech/docs/entities#dynamic-entities
