### ISSUE TITLE
Outdated testing docs

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#772]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [X] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Example code works and there is an option to change config for tests

## Current Behavior
https://www.jovo.tech/docs/unit-testing#conversation-configuration

I'm trying to use testing docs example code but when doing copy 1:1 I'm getting error that config is not correct
```ts
// Example: Use different PORT for the Jovo Webhook
const conversationConfig = {
    httpOptions: { 
        port: PORT,
    },
};
const conversation = testSuite.conversation(conversationConfig);
```
```
Argument of type '{ httpOptions: { port: number; }; }' is not assignable to parameter of type 'ConversationConfig'.
  Types of property 'httpOptions' are incompatible.
    Type '{ port: number; }' has no properties in common with type 'AxiosRequestConfig'.ts(2345)
```

**Comment by aswetlow** [comment]
Sorry, this got lost. 

This is fixed now, correct?

httpOptions is of type AxiosRequestConfig (https://github.com/axios/axios#request-config)

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
