### ISSUE TITLE
DynamoDB is not created/used (worked previously)

### ISSUE THREAD

**Issue by MartinPindel** [jovotech/jovo-framework#773]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

On requests to my lambda, a DynamoDB table should be created for user data and user data should be writting in there.

## Current Behavior

On requests to my lambda, no DynamoDB table is created/used for user data. (The code worked previously: All data was saved in a automatically created DynamoDB)

I already set back all dependencies to the time, when everything worked, but this didn't solve the problem.
Neither helped reinstalling all dependencies.

The code is similar to the DynamoDB tutorial (found here: [https://www.jovo.tech/tutorials/add-dynamodb-database](https://www.jovo.tech/tutorials/add-dynamodb-database))
In the app.js
```
const { App } = require('jovo-framework');
const { DynamoDb } = require('jovo-db-dynamodb');

const app = new App();

...

app.use(
    ...
    new DynamoDb()
);
...
```
And in the config.js:
```
...
db: {
   DynamoDb: {
      tableName: 'TableName'
   }
}
...
```

### Error log
There are no errors in the logs.

## Your Environment

* Jovo Framework version used: 3.0.18
* Jovo DynamoDB version used: 3.0.17
* Operating System: Windows 10

I am building for Google Assistant only and have also the debugger in use.

**Comment by aswetlow** [comment]
Did it start not working after an update?

**Comment by MartinPindel** [comment]
Honestly I can't really tell. I tested the user data some time ago, when everything worked (about 3 to 4 weeks ago).
Since then I had no real user data to store. But there was never any error or warning, so I didn't think about something like this. Yesterday i rolled back the last updates, but this didn't solve the problem.

**Comment by MartinPindel** [comment]
After debugging I found the problem.
There was an old stage-config in my local bundle folder, containing another database-setup. This file was not deleted by `jovo build`, after removing all stages in my project. Removing the file worked.
