### ISSUE TITLE
Google Analytics send() Error after upgrade

### ISSUE THREAD

**Issue by freiSMS** [jovotech/jovo-framework#778]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
When running `npm update` in my skill jovo-plugin-googleAnalytics should fetch the latest working version of universal-analytics.

## Current Behavior
`npm update` increased my universal-analyitcs version from 0.4.20 to 0.4.21. Afterwards google anlytics returned a 404 error in the callback from the `send()` method in each request. 
I was able to fix this for the moment by accessing the package.json-lock file and setting the universal analytics version to 0.4.20. I think the universal-analytics changes were mainly for updating from `request` to request-native`. But this was the first upgrade till two years. So maybe there are some more changes.

## Your Environment
* Jovo Framework version used: 3.0.19
* Operating System: Ubuntu 20.04

**Comment by AdnanDL** [comment]
Can confirm this is happening to me as well
```
Stack:
  Error
      at module.exports.Visitor.visitor.pageview (/Users/adnanaga/Documents/UPMC/UPMC/node_modules/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts:72:15)
      at onFinish (/Users/adnanaga/Documents/UPMC/UPMC/node_modules/universal-analytics/lib/index.js:418:10)
      at nextIteration (/Users/adnanaga/Documents/UPMC/UPMC/node_modules/universal-analytics/lib/index.js:448:23)
      at IncomingMessage.<anonymous> (/Users/adnanaga/Documents/UPMC/UPMC/node_modules/native-request/index.js:79:3)
      at IncomingMessage.emit (events.js:202:15)
      at endReadableNT (_stream_readable.js:1129:12)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
  
  Module:
  jovo-analytics-googleanalytics
```

**Comment by freiSMS** [comment]
did my fix work for you @AdnanDL ?

**Comment by freiSMS** [comment]
easiest fix for me was to install the analytics package jovo is using: `npm i --save universal analytics` and change the version increment setting to stop with version 0.4.20 in the package.json
![grafik](https://user-images.githubusercontent.com/20289566/86721066-ebc37680-c025-11ea-9e27-fa17bba550c0.png)

**Comment by aswetlow** [comment]
`npm update` can be tricky sometimes. 

I don't have a perfect solution for update issues like this. I think, I got the best results updating third party packages manually like @freiSMS does.

**Comment by aswetlow** [comment]
Oh I probably misunderstood the issue.

Please use the approach of @freiSMS. We will publish a quick fix soon.

**Comment by AdnanDL** [comment]
Yep @freiSMS I used your trick here to get it to work for me!

**Comment by dominik-meissner** [comment]
In Version 0.4.23 of universal-analytics they have reverted back to the (outdated) request package. So it seems they introduced a Bug with the 0.4.21 release. All should be working as before now. No need for version pinning in package.json at the moment.
