### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by nileenash** [jovotech/jovo-framework#779]
I installed jovo-cli. But run jovo  -v I get 

### Error log
```
/usr/bin/env: ‘node\r’: No such file or directory

```

## Your Environment

* Jovo Framework version used: jovo-cli@3.0.15
* Operating System: linux 18.04

**Comment by aswetlow** [comment]
Could you re-install the cli and run the command again?

**Comment by nileenash** [comment]
re-installed. But run jovo -v get same message 

/usr/bin/env: ‘node\r’: No such file or directory

**Comment by aswetlow** [comment]
Weird, I can't reproduce it. 

What's your node version?

**Comment by nileenash** [comment]
my node version is ´v8.10.0´

**Comment by aswetlow** [comment]
Can you update and retry it again?

**Comment by aswetlow** [comment]
Does it work? Please reopen if there's still a problem.
