### ISSUE TITLE
Invalid enum value:   ›   "alexa::device:all:address:read"

### ISSUE THREAD

**Issue by PrasadPotale** [jovotech/jovo-framework#780]
Getting following error during Jovo deploy
›
 ›   [ERR] askApiUpdateSkill:Skill manifest is not valid.
 ›   
 ›   Module:   jovo-cli-platform-alexa
 ›   Hint:     String instance at property path 
 ›   "$.manifest.permissions[1].name" has invalid enum value: 
 ›   "alexa::device:all:address:read". Please refer to public documentation for 
 ›   the list of allowed values.
 ›

I did checked and this is allowed value on Alexa, following is Project.js file

module.exports = {
  alexaSkill: {
    nlu: 'alexa',
    manifest: {
      permissions: [
        {
          name: 'alexa::devices:all:geolocation:read'
        },
        {
          name: 'read::alexa:device:all:address'
        }
      ]
    }
  },
  googleAction: {
    nlu: 'dialogflow',
  },
  endpoint: '${JOVO_WEBHOOK_URL}',
};

**Comment by aswetlow** [comment]
`read::alexa:device:all:address` is not valid. try this `alexa::profile:address:read`

https://community.jovo.tech/t/add-permissions-under-manifest-in-skill-json/866/5

**Comment by PrasadPotale** [comment]
> alexa::profile:address:read

Thanks @aswetlow  for quick reply, I'm still getting issue for new value too
"$.manifest.permissions[1].name" has invalid enum value: 
 ›   "alexa::profile:address:read". Please refer to public documentation for 
 ›   the list of allowed values.
 ›

**Comment by PrasadPotale** [comment]
@aswetlow thanks for the link, found the correct value from the link that you shared,
alexa::devices:all:address:full:read

https://developer.amazon.com/en-US/docs/alexa/smapi/skill-manifest.html#permissions
