### ISSUE TITLE
DynamoDB: User Data Item Not Deleted from 'AlexaSkillEvent.SkillDisabled'

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#782]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The User Data Item should be deleted from the database.

## Current Behavior

The record is not deleted from the database.

The code in DynamoDb.delete is called including:
```
return this.docClient.delete(deleteItemInput).promise();
```
But the item is still in the database.

The code is:
```
  ON_EVENT: {
    'AlexaSkillEvent.SkillDisabled'() {
      // Remove user from the database when the skill is disabled
      // if the user re-enables the skill, they will have a new userId anyway
      this.$user.delete();
    },
```

The database configuration is:

```
    DynamoDb: {
      enabled: true,
      tableName: `${process.env.DYNAMODB_TABLE}`,
      prefixPrimaryKeyWithPlatform: true,
      primaryKeyColumn: 'PK',
      primaryKeyPrefix: 'JOVOUSER#',
      sortKeyColumn: 'SK',
      sortKey: 'JOVO#USERDATA',
    },
```

But I don't think it is the composite primary key (PK + SK) but possibly due to it being called from 'AlexaSkillEvent.SkillDisabled'()

### Error log
```
No log
```

## Your Environment

```
Jovo CLI Version: 3.0.8

Jovo packages of current project:
  jovo-analytics-dashbot: 3.0.22
  jovo-cms-i18next: 3.0.17
  jovo-community-plugin-sentry: 1.5.1
  jovo-component-get-phone-number: 3.0.1
  jovo-core: 3.0.17
  jovo-db-dynamodb: 3.0.18
  jovo-db-filedb: 3.0.18
  jovo-framework: 3.0.19
  jovo-platform-alexa: 3.0.22
  jovo-plugin-debugger: 3.0.17
  jovo-plugin-error-slack: 3.0.0
  jovo-plugin-speechmarkdown: 1.6.0
```
* Operating System: Windows 10

I am testing this using the Jovo Webhook for local debugging: `jovo run --inspect 3003`

**Comment by dominik-meissner** [comment]
Hi Mark,

this needs to be an async operation (on dynamoDB).

Try `await this.$user.delete();`
I will update the docs then.

Best,
Dominik.

**Comment by aswetlow** [comment]
Closing. Please re-open if it's not solved.
