### ISSUE TITLE
InvalidCharInSamples : for Spanish language on Alexa deploy

### ISSUE THREAD

**Issue by PrasadPotale** [jovotech/jovo-framework#785]
I'm not sure if this issue is specific to Jovo but I'm trying to support spanish language, for that i have added es-MX.json file in the models, getting following error during deploy,

sectionInvalidCharInSamples: "víctimas?" in the sample utterance
 ›   of only unicode characters, spaces, periods for abbreviations, underscores, possessive apostrophes, and hyphens.

Any help how can i have special characters in the model file?

**Comment by aswetlow** [comment]
Hey @PrasadPotale, sorry..this one got lost.

It's the question mark. The spanish special character `í` works.

**Comment by aswetlow** [comment]
Closing this one. Please re-open, If the problem persists.
