### ISSUE TITLE
Dialogflow events

### ISSUE THREAD

**Issue by scastrec** [jovotech/jovo-framework#800]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Dialogflow enables to trigger [events](https://cloud.google.com/dialogflow/docs/events-overview?hl=en). 
I'd like to be able to specify the event to trigger with someting like : 
`
this.$dialogflowAgent.setEvent(myEvent);
`
 

## Current Behavior
There is maybe already a way to do this with Jovo but I didn't find it in the doc.

**Comment by StephaneC** [comment]
I'm working on it and will submit a PR soon for the Dialogflow integration.

**Comment by aswetlow** [comment]
Awesome. Thank You!

**Comment by Mistic92** [comment]
Hi, do you have any update? We'd use this feature too:)

**Comment by scastrec** [comment]
@Mistic92 I had not enough time to work on it.    
If someone else want to take this, feel free.

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
