### ISSUE TITLE
Dialogflow contexts

### ISSUE THREAD

**Issue by scastrec** [jovotech/jovo-framework#801]
## I'm submitting a...
- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Jovo tech contains his own state management with ```followUpState```.   
But, Dialogflow has his own contexts which enables intent detection in the NLU tool.   
I'd like to be able to use Dialogflow contexts with the dialogflow plugin.

**Comment by StephaneC** [comment]
I could write a simple code in the dialogflow integration [here](https://github.com/jovotech/jovo-framework/blob/master/jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts) but it would miss the opportunity to make it works for Google Actions too.  
A way to map the ```followUpState``` and add contexts too for Dialogflow (id needed) could be an option.

**Comment by StephaneC** [comment]
Found addOutputContext/getOutputContext in googleassistant platform.
I have to investigate this.

**Comment by Mistic92** [comment]
We were looking at this recently too:D We can use jovo to set Dialogflow context when using GA platform so at least we have base to take a looks how it can be done.

**Comment by Mistic92** [comment]
Hi, how is work going. Do you have fork with changes?

**Comment by StephaneC** [comment]
@Mistic92 I missed time to investigate further.

**Comment by Mistic92** [comment]
Do you have any docs? Maybe we'll find some time to add contexts to Dialogflow as NLU

**Comment by StephaneC** [comment]
I started working on adding Event in Dialogflow and Actions on this branch : https://github.com/StephaneC/jovo-framework/pull/new/dev-800   (not finished yet)
It should be similar for contexts. The dialogflow doc could be found here : https://www.googleapis.com/discovery/v1/apis/dialogflow/v2beta1/rest

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
