### ISSUE TITLE
"reason": "missing certificate url"

### ISSUE THREAD

**Issue by siddharthaweb** [jovotech/jovo-framework#807]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## src/index.js
'use strict';
const { WebhookVerified: Webhook, ExpressJS } = require('jovo-framework');
const { app } = require ('./app.js');
// ------------------------------------------------------------------
// HOST CONFIGURATION
// ------------------------------------------------------------------

// ExpressJS (Jovo Webhook)
if (process.argv.indexOf('--webhook') > -1) {
    const port = process.env.JOVO_PORT || 3000;
    Webhook.jovoApp = app;
    Webhook.listen(port, () => {
        console.info(`Local server listening on port ${port}.`);
    });
   Webhook.post('/webhook_alexa', async (req, res) => {
         //Webhook.post(['/webhook','/webhook_alexa'], async (req, res) => {
        await app.handle(new ExpressJS(req, res));
    });
}

// AWS Lambda
exports.handler = async (event, context, callback) => {
    await app.handle(new Lambda(event, context, callback));
};

## Need help to solve the following
How to solve "missing certificate URL"?

## Current Behavior
Our development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority.
https://hostname/webhook_alexa
{
"status": "failure",
"reason": "missing certificate url"
}

## Your Environment
Jovo CLI Version: 3.0.8

Jovo packages of current project:
  jovo-cms-i18next: 2.2.0
  jovo-core: 2.2.0
  jovo-db-filedb: 2.2.0
  jovo-framework: 2.2.1
  jovo-platform-alexa: 2.2.1
  jovo-platform-dialogflow: 2.2.0
  jovo-platform-googleassistant: 2.2.1
  jovo-plugin-debugger: 2.2.0

**Comment by aswetlow** [comment]
Sorry for the late reply.

Did you add the certificate files?

```
const fs = require('fs');

// Add this
Webhook.ssl = {
   key: fs.readFileSync('/path/to/cert.key'),
   cert: fs.readFileSync('/path/to/cert.pem'),
};
```

**Comment by aswetlow** [comment]
I close this due to inactivity. Please re-open it if the problem persists.
