### ISSUE TITLE
SpeechBuilder ESCAPE_AMPERSAND url bug

### ISSUE THREAD

**Issue by toreyjs** [jovotech/jovo-framework#816]
## Expected Behavior
urls in <audio> tags in SSML should always be called how they are passed in

## Current Behavior
Urls with ampersands (&) don't work as they are replaced with "and". While there is a "SpeechBuilder.ESCAPE_AMPERSAND", it seems like an error to me to have this effect urls (in <audio> tags) where ampersands are special characters, especially by default.

Example:
`my.site/link?foo=0&bar=1`
currently becomes
`my.site/link?foo=0andbar=1`

## Your Environment
* Jovo Framework version used: 3.0.23
* Operating System: Windows

**Comment by aswetlow** [comment]
Hey, it's kind of code debt from v1. 

You can deactivate the replacement:

```
// app.js
const {SpeechBuilder} = require('jovo-framework');
SpeechBuilder.ESCAPE_AMPERSAND = false; 
```

**Comment by toreyjs** [comment]
I already set it to false, just seemed weird it was doing it for URLs as well where the behavior would be quite unexpected. I feel it should at least throw a warning or something if inside an audio tag.

**Comment by jankoenig** [comment]
I agree. I think we should deprecate this feature with `3.1` and turn it off by default. Would be a breaking change which would be easy to fix though. What do you think @aswetlow?

**Comment by aswetlow** [comment]
Sorry, this one got lost. 

Yes, we should change the default value with the next release. 

And yes, we could also prevent escaping `&` in `addAudio` at all

**Comment by aswetlow** [comment]
Quickfix: I updated the regex. It won't replace the ampersand between quotes. This means it won't be replaced in urls.

We will publish the fix tomorrow.

**Comment by aswetlow** [comment]
Done.
