### ISSUE TITLE
ERR_NO_MATCHING_PLATFORM for requests coming from the Actions Console

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-framework#821]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I'm testing the action from the Actions Console and the set webhook is the jovo one. In the terminal I can see that the request is received, but it looks like to not be recognized by Jovo. This is my configuration:
```
const { App } = require('jovo-framework');
const { Alexa } = require('jovo-platform-alexa');
const { GoogleAssistant } = require('jovo-platform-googleassistant');

const app = new App();

app.use(
    new Alexa(),
    new GoogleAssistant()
);

app.setHandler(....);
```
Also, how does `intentMap` work with Conversational Actions? Should I use the intent name (actions.intent.MAIN) or the corresponding handler name?

## Current Behavior

Everytime jovo receives a request, it crashes with the following error.

### Error log
```
Code:
  ERR_NO_MATCHING_PLATFORM

  Message:
  Can't handle request object.

  Stack:
  Error: Can't handle request object.
      at App.handle (D:\Projects\AlexaSkill\the-noise-shop\node_modules\jovo-core\src\core\BaseApp.ts:229:15)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at App.handle (D:\Projects\AlexaSkill\the-noise-shop\node_modules\jovo-framework\src\App.ts:333:5)
      at D:\Projects\AlexaSkill\the-noise-shop\src\index.js:18:9

  Module:
  jovo-core

  Hint:
  Please add an integration that handles that type of request.
```

## Your Environment

* Jovo Framework version used: 3.0.24
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 

Conversational Actions are not supported yet, but we're working on it.

**Comment by acerbisgianluca** [comment]
@aswetlow Ok, thanks! I had to switch to Conversational Action because Dialogflow gives me "Precondition check failed" everytime I try to test the Google Assistant integration inside Dialogflow console. Have you ever experienced this?

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 

Can I close this issue? 

Here's the tutorial: https://www.jovo.tech/tutorials/google-conversational-actions-getting-started

**Comment by acerbisgianluca** [comment]
> Hey @acerbisgianluca 
> 
> Can I close this issue? 
> 
> Here's the tutorial: https://www.jovo.tech/tutorials/google-conversational-actions-getting-started
> 
> 

Yup. Thank you for your amazing work!

**Comment by mig82** [comment]
I'm facing this same problem while trying to follow along this video (https://youtu.be/jKujwlF-iO4). I'm not sure I understand what the solution is. Can someone please explain? I'm just doing what's in the video. 
```
$ jovo -v
Jovo CLI Version: 3.2.1
```
