### ISSUE TITLE
[TypeScript] Add UserData type for $user.$data to use instead of being Data type

### ISSUE THREAD

**Issue by toreyjs** [jovotech/jovo-framework#825]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Description
My issue is with `$data: Data;` in `interface User` (found [here](https://github.com/jovotech/jovo-framework/blob/master/jovo-framework/src/index.ts#L58)), which uses `Data` directly instead of having something like "UserData" which inherits from `Data`, similar to the implementation of JovoData, AppData, and SessionData.

The reason this matters for me is because I'd like to use module augmentation to add fields / typing for each of theses data types (also nice for autocomplete). But when I try to do this with User data, it currently effects all the other types since user data uses just the base type, `Data`.

example of what I can do with SessionData but not UserData (since it doesn't exist):
```typescript
interface MySessionData { foo?:string };
declare module 'jovo-core/dist/src/Interfaces' {
	interface SessionData extends MySessionData {}
}
```

optionally I'd love a built-in way to do this that also disallows using non-defined fields (so that I don't accidentally call `$user.$data.foo` instead of `$session.$data.foo` for example) as module augmentation only lets me narrow down fields, but that's not as important (and I'm not exactly sure how that could be achieved anyways, without removing `[key: string]: any;` which would then force everyone to use module augmentation).

**Comment by m-ripper** [comment]
Hello @toreyjs,

Thanks for the feature-request. 
With the 3.1 update, this feature is now available.

**Comment by toreyjs** [comment]
Thank you!
