### ISSUE TITLE
MongoDB Database Error When Persisting Session to DB

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework#833]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I should be able to configure both MongoDB as the database and set to persist session values to the database with no errors.

## Current Behavior

When you configure to persist session data to the database:

// config.js
```
  user: {
    context: {
      enabled: true,
    },
    metaData: {
      enabled: true,
    },
    sessionData: {
      enabled: true,
      data: true,
    },
  },
```

And set the database to Mongo:
// config.js
```
    MongoDb: {
      enabled: true,
      databaseName: 'development',
      collectionName: 'voiceuserdata',
      uri: `${process.env.MONGODB_CONNECTION_URL}`,
    },

```

Then the data is persisted with a key of `$data`:

```
      "session": {
        "M": {
          "$data": {
            "M": {
 
```

But this causes an error in Mongo.

### Error log
```
  Error -----------------------------------------------------------------

  Code:
  ERR_PLUGIN

  Message:
  The dollar ($) prefixed field '$data' in 'userData.session.$data' is not valid for storage.

  Stack:
  Error: The dollar ($) prefixed field '$data' in 'userData.session.$data' is not valid for storage.
      at MongoDb.save (C:\dev\voice\xxx\xxx-voice\node_modules\jovo-db-mongodb\dist\src\MongoDb.js:89:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  Module:
  jovo-db-mongodb

  Hint:
  Make sure the configuration you provided is valid.

  Learn more:
  https://www.jovo.tech/docs/databases/mongodb
```

## Your Environment

* Jovo Framework version used: 3.1.3
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Thank you, we will make the field name configurable. Otherwise, it could break existing apps.

**Comment by aswetlow** [comment]
We will publish the fix tomorrow.
