### ISSUE TITLE
Add support for SkillConnections API events

### ISSUE THREAD

**Issue by ghost** [jovotech/jovo-framework#846]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Currently, after sending a directive for any of the SkillConnections skills, such as the printing skill, the Jovo doesn't support the SessionResumedHandler event that is returned. Exposing that event for general use is necessary to be able to use any of the SkillConnections. 

## Current Behavior

The session resumed event can't be caught without the extra steps of watching for the request type in Jovo hooks. It works but as they add more skills that are available to use in that API it would be nice to have that event available out of the box. Otherwise, it is missed and the session cannot be resumed after coming back from the connected skill. 

## Your Environment

* Jovo Framework version used: 3.0.31
* Operating System: macOS Catalina, node v12.x

**Comment by aswetlow** [comment]
Yes, makes sense. We will discuss it internally.

**Comment by aswetlow** [comment]
Unfortunately, we won't support this for Jovo v3. Although it's easily integrated into v4 projects.
