### ISSUE TITLE
APL for audio - Devices not supported

### ISSUE THREAD

**Issue by leogiroux** [jovotech/jovo-framework#849]
Hi everyone,

I'm using Jovo to develop an alexa skill but I'm facing an issue to execute an `addAplDirective`.

**Js Code**
`this.$alexaSkill.addAplDirective({
      type: 'Alexa.Presentation.APLA.RenderDocument',
      token: 'hi',
      document: require('../apla/documents/testDocument'),
      datasources: {
        params: {
          test: formatSSMLwithBalise(this, 'ceci est un test audio', 'alexa'),
        }, 
      },
    });`
**Document**
`module.exports = {
  type: 'APLA',
  version: '0.8',
  description: 'This document demonstrates key components used to create audio responses.',
  mainTemplate: {
    parameters: [
      'payload',
    ],
    item: {
      type: 'Sequencer',
      description: 'The Sequencer component plays a series of audio clips one after another.',
      items: [
        {
          type: 'Speech',
          contentType: 'SSML',
          content: '${payload.params.test}',
        },
        {
          type: 'Audio',
          source: 'https://www.jovo.tech/audio/LshHeoze-a67e020ead100a4d3818cf35e31c879d.mp3',
        },
      ],
    },
  },
};`

On my Echo show 8 everything goes well, I can play text and audio, but on an Echo dot 3 without the clock display nothing happen just a silence during a few seconds, on an Echo dot 3 with the clock display it is working.
Even the speech text is not played so I guess It is not the mp3 encoding which is not working.

Do you think that the issue come from the device himself or APLa from the jovo method `addAplDirective` is bugged ?
I'm  trying to reach Alexa team too.

Thanks

**Comment by aswetlow** [comment]
Hey @leogiroux 

Not 100% sure, but I think APLA is not supported on non-visual devices like the echo dot 3 (without the clock).
Could you post the request json (from the Echo Dot with the clock and the one without the clock)? We could compare the property for the supported interfaces.

**Comment by leogiroux** [comment]
Hi @aswetlow ! 

I've try on the both device and this is the apla directive log on the device that is working : 
**WORKING DEVICE**
{
  "version": "1.0",
  "response": {
    "shouldEndSession": false,
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> </speak>"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak> </speak>"
      }
    },
    "directives": [
      {
        "type": "Alexa.Presentation.APLA.RenderDocument",
        "token": "playNextSample",
        "document": {
          "type": "APLA",
          "version": "0.9",
          "description": "This document demonstrates key components used to create audio responses.",
          "mainTemplate": {
            "parameters": [
              "payload"
            ],
            "item": {
              "type": "Sequencer",
              "description": "The Sequencer component plays a series of audio clips one after another.",
              "items": [
                {
                  "type": "Speech",
                  "contentType": "SSML",
                  "when": "${payload.params.isFirstSession == true && payload.params.fromNext == false}",
                  "content": "${payload.params.niceName}"
                },
                {
                  "type": "Speech",
                  "contentType": "SSML",
                  "when": "${payload.params.isFirstSession == true && payload.params.fromNext == false}",
                  "content": "${payload.params.start}"
                },
                {
                  "type": "Speech",
                  "contentType": "SSML",
                  "content": "${payload.params.presentSample}"
                },
                {
                  "type": "Audio",
                  "description": "The Audio component plays the provided audio file, such as an MP3 file. See docs for more information.",
                  "source": "${payload.params.sample}",
                  "filter": [
                    {
                      "type": "Volume",
                      "amount": 0.5
                    },
                    {
                      "type": "FadeOut",
                      "duration": 2000
                    }
                  ]
                },
                {
                  "type": "Speech",
                  "contentType": "SSML",
                  "content": "${payload.params.variantNext}"
                }
              ]
            }
          }
        },
        "datasources": {
          "params": {
            "fromNext": false,
            "isFirstSession": true,
            "start": "<speak>Les extraits vont défiler au hasard, si tu souhaites passer à l'extrait suivant, dis « Alexa suivant ».</speak>",
            "niceName": "<speak><prosody pitch=\"high\"> C'est stylé !</prosody> <break time=\"0.1s\"/> C'est un monde illimité de divertissement audio qui s'ouvre à toi, léo ! Découvrons les extraits de nos meilleurs contenus de la semaine !</speak>",
            "presentSample": "<speak>C'est parti pour l'extrait de </speak>",
            "sample": "https://files.sybel.com/series/TIpk8ZkLSy/sample/946c66a128f0e6303308d1ab45371b82",
            "variantNext": "<speak><prosody pitch=\"high\">Pas mal ! non ?</prosody> <break time=\"0.1s\"/> Ça te dit qu'on l'écoute ? <break time=\"0.1s\"/> ou au suivant ?</speak>"
          }
        }
      }
    ]
  },

**NO WORKING DEVICE**
{
  "version": "1.0",
  "response": {
    "shouldEndSession": false,
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> </speak>"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak> </speak>"
      }
    }
  },
  "sessionAttributes": {
    "isFirstSession": true,
    "_JOVO_STATE_": "EXTRACT_FLOW",
    "isSamplePlaying": true,
    "sampleFlowPlayer": {
      "series": [
        "IADhtDBf2q",
        "DPq0DqX9c7"
      ],
      "index": 1
    }
  }
}

So as you can see the directive section is not present, and I have found some article and post that say APLA is available for all alexa devices  :/ 
https://forums.developer.amazon.com/questions/233492/is-apl-supported-on-echo-dot-3rd-gen-which-has-no.html
https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2020/07/apl-for-audio
APL for audio is supported on all Alexa devices like Echo devices and third-party devices.

Do you have any idea ? Maybe there is a part in the jovo code that check the compatibility with APL device that block the APLA feature ? Thanks :)

**Comment by aswetlow** [comment]
Thanks! Yes, in the meantime I also found the blogpost about APL-A. 
It's a bug on our side. Working on a fix.

**Comment by leogiroux** [comment]
Thanks man ! You are the best :D

I guess this is this line ;) 

https://github.com/jovotech/jovo-framework/blob/f911f3bed60faa8f9395084dc22257558345236c/jovo-platforms/jovo-platform-alexa/src/modules/AplPlugin.ts#L120

you merge an APL document haha which block the APLA for unsupported APL devices.

**Comment by leogiroux** [comment]
Nice thanks :) When do you think it's gonna be live ?

**Comment by aswetlow** [comment]
Struggling with a few other issues in this release. Will do it tomorrow.

**Comment by leogiroux** [comment]
Thanks man !

**Comment by aswetlow** [comment]
Fixed. Please run `jovo update`

**Comment by leogiroux** [comment]
It is working thanks for your quick reaction :D
