### ISSUE TITLE
Support GetDeviceName for conversational actions

### ISSUE THREAD

**Issue by gshenar** [jovotech/jovo-framework#867]
## I'm submitting a...

- [ X ] Bug report
- [ X ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
GetDeviceName should return device name for conversational actions in a similar way to how legacy actions work.

## Current Behavior
GetDeviceName is not implemented 
https://github.com/jovotech/jovo-framework/blob/11f2c51ea7b63c6fe8603f9451632c142e12532b/jovo-platforms/jovo-platform-googleassistantconv/src/core/ConversationalActionRequest.ts#L45

### Error log
See code link above

## Your Environment
* Jovo Framework version used: Latest
* Operating System: N/A

**Comment by aswetlow** [comment]
Thanks, will refactor and add missing functions within the next two weeks.
