### ISSUE TITLE
Migration document link is broken

### ISSUE THREAD

**Issue by xbootnek** [jovotech/jovo-framework#872]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ x] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
"With the update to Jovo v2, we changed the way you can access input values. Please read more below, or take a look at our migration document." The Migration document link gives a 404 error.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by aswetlow** [comment]
Hey @xbootnek 

Thank you!
