### ISSUE TITLE
Use Jovo on AutoCode

### ISSUE THREAD

**Issue by NovaGL** [jovotech/jovo-framework#880]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

Hi, 
I currently have Jovo working great on Glitch but I want to move over to Autocode as it's much faster. Can you tell me how I could do that?

https://autocode.com/

**Comment by aswetlow** [comment]
Hey @NovaGL 

I haven't worked with Glitch or Autocode. Can't help you with that, but I'm curious how a Jovo project on Glitch looks like.

**Comment by NovaGL** [comment]
It works quite well a bit slow now. There is a jovo repo on Glitch thought you guys created it.

It's just a node project and express server
