### ISSUE TITLE
Account Linking failing for Google's Conversational Actions

### ISSUE THREAD

**Issue by Voice-First-AI** [jovotech/jovo-framework#884]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Account Linking should popup a sign-in card in the Google Assistant app for Conversational Actions.

## Current Behavior

We receive error message that account linking is not supported on Conversational actions.

### Error log
```
Message:
  Not supported in Google Assistant Conversational Actions.
  Stack:
  Error: Not supported in Google Assistant Conversational Actions.
```
![live-your-song-conversatinal-actions-no-account-link](https://user-images.githubusercontent.com/40079313/103819896-4e2f1b00-5039-11eb-80fa-ff389ba306ed.png)

Here's our code to send the sign-in request:
![google action error](https://user-images.githubusercontent.com/40079313/103819943-669f3580-5039-11eb-887f-1636de9af825.PNG)

## Your Environment

* Jovo CLI Version: 3.2.1
* Jovo packages of current project:
 * jovo-core: 3.3.0
*  jovo-db-filedb: 3.3.0
*  jovo-db-platformstorage: 3.3.0
*  jovo-framework: 3.3.0
*  jovo-model: 0.1.15
*  jovo-model-nlpjs: 0.1.1
*  jovo-nlu-nlpjs: 3.3.0
*  jovo-platform-alexa: 3.3.0
*  jovo-platform-core: 3.3.0
*  jovo-platform-googleassistantconv: 3.3.0
*  jovo-platform-web: 3.3.0
*  jovo-plugin-debugger: 3.3.0
* Operating System: Windows 10

**Comment by tnpaul** [comment]
This issue seems to be closed but I don't see any resolution here. I am currently facing exactly the same issue. Could anyone help here.
