### ISSUE TITLE
run signature Alexa

### ISSUE THREAD

**Issue by zigou13** [jovotech/jovo-framework#886]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I have errors during the skill run, what is the solution?
![Capture](https://user-images.githubusercontent.com/32574412/105633127-2c1a0300-5e57-11eb-959f-804f89cc5a73.PNG)

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: Jovo CLI Version: 3.2.1
* Operating System:

**Comment by aswetlow** [comment]
How did you set up your endpoint?

Skill validation/Skills in production don't work with the Jovo Webhook (on purpose).

This error should not occur on Lambda. If you use any other cloud/hosting provider, the skill has to verify the Alexa requests. 
https://www.jovo.tech/docs/hosting/express-js#verification

**Comment by zigou13** [comment]
Hello,
the problem is fixed, I use AWS;)
https://www.jovo.tech/tutorials/deploy-lambda-cli
