### ISSUE TITLE
Change metadata streaming

### ISSUE THREAD

**Issue by zigou13** [jovotech/jovo-framework#889]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X ] Other... Please describe:

## Your Environment

* Jovo Framework version used: 3
* Operating System:

Hello,
is it possible to change on a streaming stream the setTitle () and setSubtitle () to update the songs live API ?

**Comment by aswetlow** [comment]
Hey @zigou13 

Need more context here. Are you using the Alexa Audioplayer?

**Comment by zigou13** [comment]
Yes I am using Alexa Audioplayer, I want to update setTitle () and setSubtitle VIA API PHP.
is it possible to update both functions?

**Comment by aswetlow** [comment]
I'm not sure I understand this correctly.
You set the metadata before you call the play function

https://www.jovo.tech/docs/v1/amazon-alexa/audioplayer#set-track-metadata
```javascript
this.alexaSkill().audioPlayer()
    .setTitle('First Track')
    .setSubtitle('A simple subtitle')
    .addArtwork('https://www.somewhere.com/image.png')
    .addBackgroundImage('https://www.somewhere.com/background.jpg')
    // The above method calls need to be before play()
    .play(url, token);
```

What do you mean by "API PHP"?

**Comment by zigou13** [comment]
I have found my answer, for the moment this is not possible.
https://forums.developer.amazon.com/questions/233299/updating-audioplayer-interface-metadata-while-play-1.html
