### ISSUE TITLE
Google Analytics Error

### ISSUE THREAD

**Issue by zigou13** [jovotech/jovo-framework#891]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

### Error log
`Cannot read property 'lastUsedAt' of undefined

  Stack:
  TypeError: Cannot read property 'lastUsedAt' of undefined
      at GoogleAnalytics.saveStartStateAndLastUsed (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\jovo-analytics-googleanalytics\src\GoogleAnalytics.ts:32:53)
      at Middleware.run (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\jovo-core\src\core\Middleware.ts:85:20)
      at Middleware.run (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\jovo-core\src\core\Middleware.ts:63:62)
      at App.handle (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\jovo-core\src\core\BaseApp.ts:274:41)
      at App.handle (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\jovo-framework\src\App.ts:333:5)
      at C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\src\index.js:20:5
  
   ----------------------------------------------------------------------

  
  Request details:
  this.$alexaSkill initialized
  this.$type: {"type":"LAUNCH"}
  this.$session.$data : {}
  this.$nlu : {}
  this.$inputs : {}

  
   ----------------------------------------------------------------------

  unhandledRejection
  {}
  Error: Request failed with status code 500
      at createError (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\core\createError.js:16:15)
      at settle (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\adapters\http.js:236:11)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at createError (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://localhost:3000/webhook","method":"post","data":"{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2021-01-31T23:43:35.145Z\",\"locale\":\"en-US\"}}","headers":{"Accept":"application/json","Content-Type":"application/json","jovo-debugger":true,"User-Agent":"axios/0.19.2","Content-Length":1009},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
  Error: Request failed with status code 500
      at createError (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\core\createError.js:16:15)
      at settle (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (C:\Users\jerome\Desktop\GoogleAnalysticsPlayer\node_modules\axios\lib\adapters\http.js:236:11)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at createError (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\jerome\\Desktop\\GoogleAnalysticsPlayer\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://localhost:3000/webhook","method":"post","data":"{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2021-01-31T23:43:35.145Z\",\"locale\":\"en-US\"}}","headers":{"Accept":"application/json","Content-Type":"application/json","jovo-debugger":true,"User-Agent":"axios/0.19.2","Content-Length":1009},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`
```
If you have an error log, please paste it here.
`

## Your Environment
<!--- Include as many relevant details about the environment where the bug was discovered -->
* Jovo Framework version used: 3.3.1
* Operating System:
 jovo-analytics-googleanalytics: 3.3.1
  jovo-core: 3.3.1
  jovo-db-filedb: 3.3.1
  jovo-framework: 3.3.1
  jovo-platform-alexa: 3.3.1
  jovo-platform-dialogflow: 3.3.1
  jovo-plugin-debugger: 3.3.2

**Comment by dominik-meissner** [comment]
Maybe you haven't enabled metadata.

Add this to your config.js

` user: {
    metaData: true,
  },`

More info here:
https://www.jovo.tech/docs/data/user

**Comment by zigou13** [comment]
Yes it's good,
thank you my friend
