### ISSUE TITLE
Add error handling to logging integrations

### ISSUE THREAD

**Issue by techpeace** [jovotech/jovo-framework#897]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

There are [some reports on Twitter](https://twitter.com/marktucker/status/1359686452146098176) of analytics integrations throwing errors. I noticed that the referenced integration could use some error handling in case the external API calls fail:

https://github.com/jovotech/jovo-framework/blob/1c6f608c051d2a2bc331e579069ca4e865a5ccdc/jovo-integrations/jovo-analytics-dashbot/src/DashbotDialogflow.ts#L38-L44

Handling request errors will prevent the larger skill from erroring out in that case.

I'm going to submit a PR that attempts to address this. Let me know if its sounds like a good plan:

- [ ] Check on all analytics integrations and find those missing error handling logic
- [ ] Import `Log` and either use `try`/`catch` (or `.catch` if the relevant API supports promises) to catch and log any analytics request errors

**Comment by aswetlow** [comment]
Awesome! Thank you @techpeace

**Comment by rmtuckerphx** [comment]
Yes! Great idea.

**Comment by rmtuckerphx** [comment]
Here is the error I had the other day with Dashbot. They are looking into it, but it would be good to have exception handling on the Jovo plugin side as well.

```
2021-02-11T01:41:45.694Z c9aeef87-992d-495b-ae5c-26588be09905 ERROR Unhandled Promise Rejection 

{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "FetchError: network timeout at: https://tracker.dashbot.io/track?apiKey=XXXXXX&type=incoming&platform=alexa&v=10.4.5-npm",
  "reason": {
    "errorType": "FetchError",
    "errorMessage": "network timeout at: https://tracker.dashbot.io/track?apiKey=XXXXXX&type=incoming&platform=alexa&v=10.4.5-npm",
    "name": "FetchError",
    "message": "network timeout at: https://tracker.dashbot.io/track?apiKey=XXXXXX&type=incoming&platform=alexa&v=10.4.5-npm",
    "type": "request-timeout",
    "stack": [
      "FetchError: network timeout at: https://tracker.dashbot.io/track?apiKey=XXXXXX&type=incoming&platform=alexa&v=10.4.5-npm",
      " at Timeout._onTimeout (/var/task/node_modules/node-fetch/index.js:126:13)",
      " at listOnTimeout (internal/timers.js:554:17)",
      " at processTimers (internal/timers.js:497:7)"
    ]
  },
  "promise": {},
  "stack": [
    "Runtime.UnhandledPromiseRejection: FetchError: network timeout at: https://tracker.dashbot.io/track?apiKey=XXXXXX&type=incoming&platform=alexa&v=10.4.5-npm",
    " at process.<anonymous> (/var/runtime/index.js:35:15)",
    " at process.emit (events.js:326:22)",
    " at process.EventEmitter.emit (domain.js:483:12)",
    " at processPromiseRejections (internal/process/promises.js:209:33)",
    " at processTicksAndRejections (internal/process/task_queues.js:98:32)",
    " at runNextTicks (internal/process/task_queues.js:66:3)",
    " at listOnTimeout (internal/timers.js:523:9)",
    " at processTimers (internal/timers.js:497:7)"
  ]
}
```

**Comment by techpeace** [comment]
As part of this work, I noticed that [the VoiceHero website no longer resolves](http://www.voicehero.ai/), and it [looks like they haven't tweeted since 2019](https://twitter.com/voiceheroai?lang=en).

Does anybody know if they're still around? If not, we could drop `jovo-analytics-voicehero`.

**Comment by rmtuckerphx** [comment]
VoiceHero project is no more.
