### ISSUE TITLE
Drop VoiceHero integration package

### ISSUE THREAD

**Issue by techpeace** [jovotech/jovo-framework#899]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:

[VoiceHero no longer exists](https://github.com/jovotech/jovo-framework/issues/897#issuecomment-778901544), so the `jovo-analytics-voicehero` can be dropped.

**Comment by aswetlow** [comment]
Thanks, will deprecate the package.
