### ISSUE TITLE
Missing types for OnRequest & OnResponse params

### ISSUE THREAD

**Issue by allanmelo** [jovotech/jovo-framework#904]
## I'm submitting a...
- [x] Documentation issue or request

## Expected Behavior

OnRequest & OnResponse listeners receive a parameter called "jovo", where we can call "getRequestObject()" and "getResponseObject()" methods. So far, that is exactly what is being said in the documentation.

The problem is that there are no types to define this "jovo" parameter, which can make it work perfectly when programming with Typescript.

Searching inside the lib, I found a "Host" entity that invokes "getRequestObject" and that can be used to match typos. However, it cannot be used in "getResponseObject", which gives an error because it is a method that does not exist. Also, I didn't find anything internally that could be used to represent the "getResponseObject".

### Error log
<img width="587" alt="Captura de Tela 2021-02-23 às 19 17 36" src="https://user-images.githubusercontent.com/16151423/108915550-cc587880-760b-11eb-9809-f1504a042615.png">

## Your Environment
jovo-framework: 3.0.15,
jovo-platform-googleassistant: 3.0.15,
jovo-plugin-debugger: 3.0.14
typescript: 4.1.5
node: 14.15.3
macOs Catalina 10.15.7 (19H2)

**Comment by aswetlow** [comment]
Thanks, yes the typings were missing. It's fixed and will be published with the next release.

The parameter is of type `HandleRequest' 

```
app.onRequest((handleRequest: HandleRequest) => {
	console.log(handleRequest.host.$request);
});
```

**Comment by allanmelo** [comment]
Thanks, @aswetlow . Buy how about this "getResponseObject"? I searched the code and found no mention of this method. :(

**Comment by aswetlow** [comment]
I think it's a method we used in an older version of the framework.

**Comment by aswetlow** [comment]
Closing this now. Please re-open if you have further questions.
