### ISSUE TITLE
   High            Server-Side Request Forgery

### ISSUE THREAD

**Issue by Nathanofzion** [jovotech/jovo-framework#908]
## I'm submitting a...

- [/ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior

  High            Server-Side Request Forgery
  Package         axios

  Patched in      >=0.21.1

  Dependency of   @cloudflare/wrangler [dev]

  Path            @cloudflare/wrangler > binary-install > axios

  More info       https://npmjs.com/advisories/1594

found 1 high severity vulnerability in 588 scanned packages
  1 vulnerability requires manual review. See the full report for details

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by aswetlow** [comment]
Hey @Nathanofzion 

Where did you get this warning? We upgraded this dependency vulnerability  a few weeks ago

**Comment by Nathanofzion** [comment]
Hello @aswetlow 

This was just a report I was getting in dev env, in a different project. However if it was an issue on your side a d it’s fixed great. 👍🏽
