### ISSUE TITLE
Can't pass parameters (inputs or other data) threough Jovo Web

### ISSUE THREAD

**Issue by bramses** [jovotech/jovo-framework#911]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When we call `client.createRequest()` on the web (Vue or vanilla), we should be able to pass in other parameters, such as inputs.

## Current Behavior

No data is sent, it seems in the `jovo-framework`, data is forced to be an empty object.

https://github.com/jovotech/jovo-framework/blob/ccdc44f89eca355c64ea33bc6370b95405216313/jovo-clients/jovo-client-web/src/Client.ts#L286

Hook on `router`:
```
try {
    console.log(`platform hook :: inputs >>>`)
    console.log(jovo.$inputs)
  } catch (err) {
    console.log('there was a error in router')
    console.error(error, err)
  }
// platform hook :: inputs >>>
// {}
````

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 3.5.0
* Operating System: Windows 10

**Comment by m-ripper** [comment]
Hello there, 

first of all thanks for the bug-report. 

I do not quite remember why we chose to allow passing `type` and `body` only to `createRequest`. \
But I might change it in the near future to allow the other parameters as well.

Currently, you can still modify the request-object though: `createRequest` returns an object that you can modify. \
If you want to pass some inputs you could do the following:
```ts
const clientRequest = client.createRequest({ type: RequestType.Intent, body: { text: 'hello' } });
clientRequest.request.nlu = {
  inputs: { name: { key: 'Foo', value: 'Foo' } }
};
const response = await clientRequest.send();
```
If this doesn't work for you or if you have any questions, just let me know.

**Comment by m-ripper** [comment]
Hi there, 
the `WebPlatform` by default does not use the inputs passed in the request, this is something that is probably improvable as well. During development, we mostly assumed that Nlu-integrations were going to be used but I see the advantage of avoiding them as well. 

What you can do though, is create a plugin for the `WebPlatform` which does exactly that. 

Example:
```ts
interface Config extends PluginConfig {}

export class RequestNlu implements Plugin {
  config: Config = {};

  install(webPlatform: WebPlatform) {
    webPlatform.middleware('$nlu')!.use(this.nlu.bind(this));
    webPlatform.middleware('$inputs')!.use(this.inputs.bind(this));
  }

  async nlu(webApp: WebApp) {
    const webRequest = webApp.$request as WebAppRequest;

    let intentName = 'DefaultFallbackIntent';
    if (webRequest.getIntentName()) {
      intentName = webRequest.getIntentName()!;
    } else if (webApp.$type.type === EnumRequestType.LAUNCH) {
      intentName = 'LAUNCH';
    } else if (webApp.$type.type === EnumRequestType.END) {
      intentName = 'END';
    }

    webApp.$nlu = {
      intent: {
        name: intentName,
      },
    };
  }

  async inputs(webApp: WebApp) {
    const webRequest = webApp.$request as WebAppRequest;

    if (webApp.$type.type === EnumRequestType.INTENT) {
      webApp.$inputs = webRequest.getInputs();
    } else if (
      webApp.$type.type === EnumRequestType.LAUNCH ||
      webApp.$type.type === EnumRequestType.END
    ) {
      webApp.$inputs = {};
      return;
    }
  }
}
```
And then install it to the `WebPlatform`:
```ts
const webPlatform = new WebPlatform();

app.use(webPlatform);

webPlatform.use(new RequestNlu());
```

I hope this helps.

**Comment by bramses** [comment]
I'll try this out and comment with findings. Thank you for your help!
