### ISSUE TITLE
Conv-Action: cant leave custom Scene

### ISSUE THREAD

**Issue by NLueg** [jovotech/jovo-framework#920]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

It should be possible to leave a custom scene to normally use the action after using slot filling

## Current Behavior

It's currently not possible to leave a custom scene.
I currently use the scene for slot filling as described in the examples: https://github.com/jovotech/jovo-framework/tree/34cff96fc81dfff540fae75df41b9e19e7bf0668/examples/typescript/02_googleassistantconv/scenes

It works pretty well but I want to use other actions (so I respond with `jovo.ask(...)` instead of `jovo.tell(...)` which doens't work. Every intend which is called after it always has the scene inside the request which leads to request duplication.
So basically the intend is really always called twice by Google Action which is a quite strange behaviour but okey this is not the problem of the framework. The problem is, that I never get back to the `START_CONVERSATION` scene.

This is the value of the `scene` inside the request:

```json
    "scene": {
        "name": "CollectingDataScene",
        "slotFillingStatus": "FINAL",
        "slots": {
            "message_content": {
                "mode": "REQUIRED",
                "status": "SLOT_UNSPECIFIED",
                "updated": false,
                "value": "fdghghf"
            }
        }
    },
```

I think it is because the slot status is `SLOT_UNSPECIFIED`. As in the example, the scene ends after the slots have the status `FILLED`. But I actually have no ideas how to get to this state.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Operating System: Windows
* jovo-framework: "^3.5.1"
* jovo-platform-googleassistantconv: "^3.5.2"

**Comment by dominik-meissner** [comment]
Hi Nico,
 
I experienced a similar issue and i created a new custom scene "BlankScene". After my slot filling i redirected to the BlankScene (`this.$googleAction.setNextScene('BlankScene';`). I think there is no way to get back to the `START_CONVERSATION` scene. Duplicate requests are gone then as well.

Nope this helps!
Dominik

**Comment by dominik-meissner** [comment]
@jankoenig I think this is not a framework issue. Its Google Conversational Actions design.

**Comment by jankoenig** [comment]
Thanks! Maybe it could be an option to let Jovo add a `MainScene` by default in the way @m-ripper described?

**Comment by aswetlow** [comment]
I close this issue due to inactivity.
