### ISSUE TITLE
How to use Alexa Timer?

### ISSUE THREAD

**Issue by rohankhudedev** [jovotech/jovo-framework#935]
## I'm submitting a...

- [x] Feature request

I cant see [alexa timer](https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-timers-overview.html#add-timers-to-your-skill) feature anywhere in document. How to use timer? Where user will set timer of 5/10/15 minutes and do asked activities in between. User can increase time for another 5/10. User can ask how much time is left.

**Comment by aswetlow** [comment]
Hey @rohankhudedev, it's not supported yet. I put it on our list.

**Comment by rohankhudedev** [comment]
It's there I figured it out later in [example ](https://github.com/jovotech/jovo-framework/tree/master/examples/javascript/01_alexa/timer-api) given in jovo framework. Its not documented. [Jovo.tech developers](https://www.jovo.tech/) is not documented well

**Comment by aswetlow** [comment]
hahaha, I wasn't aware that it's already implemented. By me 😂
