### ISSUE TITLE
Jovo build error for custom input types on alexa and assistant

### ISSUE THREAD

**Issue by freiSMS** [jovotech/jovo-framework#937]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I want to have a type in my model which is different on googleAction and the alexaPlatform. Therefore the type "TestType" is defined twice in my model.js - in the alexa specific part and the google action specific part. It is not defined in the neutral "inputTypes". When I run the jovo build command the slots should build for both platforms with their custom values.

## Current Behavior
Google Conversational Actions are working correctly for me. Inside the platforms/googleAction folder the "TestType" is generated. Alexa build will throw an error:  
`[ERR] /models/en.json - Input type "TestType" must be defined in inputTypes`
*Workarround:*
If I add a neutral instance of the type like this the build works:
```
  inputTypes: [
    {
      name: "TestType",
      values: [{ value: "" }],
    },
  ],
```

### Error log
```
[ERR] /models/en.json - Input type "TestType" must be defined in inputTypes
```

## Your Environment

* Jovo Framework version used: 3.51
* Jovo CLI 3.2.1
* Operating System: Ubuntu

**Comment by m-ripper** [comment]
Closing this for now due to being potentially outdated.

If the problem reappears, feel free to reopen the issue.
