### ISSUE TITLE
Send custom headers from JovoWebClient

### ISSUE THREAD

**Issue by mig82** [jovotech/jovo-framework#976]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I'd like to be able to send a custom header in the requests sent through `JovoWebClient`. Ideally the `createRequest` function should allow me to specify custom headers.

## Current Behavior
There appears to be no place to specify custom headers.

## Your Environment

* Jovo Framework version used: 3.5.2

**Comment by aswetlow** [comment]
Here's a link to my answer in the community forum.

https://community.jovo.tech/t/add-custom-header-to-jovowebclient/1668
